// Maps NPC name (as used in section content npc_speak steps) to { slug, emoji }.
// Needed in the chat where only the name string is available.
// Keep in sync with the backend character slugs.

export const CHARACTER_AVATARS: Record<string, { slug: string; emoji: string }> = {
  // Spanish PT -> ES cast
  "Don Miguel el Campesino": { slug: "don_miguel", emoji: "👨‍🌾" },
  "Miguel el Campesino": { slug: "miguel", emoji: "🧑‍🌾" },
  "Rosa la Panadera": { slug: "rosa_panadera", emoji: "👩‍🍳" },
  "Ernesto": { slug: "ernesto", emoji: "🪓" },
  "El Mercader": { slug: "mercader", emoji: "🍊" },
  "El Vigilante del Mercado": { slug: "vigilante", emoji: "💂" },
  "Señora Carmen": { slug: "senora_carmen", emoji: "👩" },
  "Sofía": { slug: "sofia", emoji: "⚡" },
  "María": { slug: "maria", emoji: "🌿" },
  "Doña Lucía": { slug: "dona_lucia", emoji: "👵" },
  "El Alcalde": { slug: "alcalde", emoji: "⚖️" },
  "El Inspector": { slug: "inspector", emoji: "🧾" },
  "Catalina": { slug: "catalina", emoji: "✨" },
  "Rodrigo": { slug: "rodrigo", emoji: "💰" },
  "James": { slug: "james", emoji: "📖" },
  "Valentina": { slug: "valentina", emoji: "🕯️" },
  "Don Miguel": { slug: "don_miguel", emoji: "👨‍🌾" },
  "Miguel": { slug: "miguel", emoji: "🧑‍🌾" },
  "Rosa": { slug: "rosa_panadera", emoji: "👩‍🍳" },
  "Mercader": { slug: "mercader", emoji: "🍊" },
  "El Vigilante": { slug: "vigilante", emoji: "💂" },
  "Carmen": { slug: "senora_carmen", emoji: "👩" },
  "Alcalde": { slug: "alcalde", emoji: "⚖️" },
  "Inspector": { slug: "inspector", emoji: "🧾" },

  // German EN -> DE cast
  "Elias der Bauer": { slug: "bauer_elias", emoji: "🌾" },
  "Elias": { slug: "bauer_elias", emoji: "🌾" },
  "Otto": { slug: "otto", emoji: "🧑‍🌾" },
  "Hanna die Baeckerin": { slug: "hanna_baeckerin", emoji: "🥖" },
  "Hanna": { slug: "hanna_baeckerin", emoji: "🥖" },
  "Friedrich": { slug: "friedrich", emoji: "🪓" },
  "Der Markthaendler": { slug: "markthaendler", emoji: "🍎" },
  "Der Waechter": { slug: "waechter", emoji: "💂" },
  "Greta": { slug: "greta", emoji: "🗝️" },
  "Lina": { slug: "lina", emoji: "✒️" },
  "Marta die Heilerin": { slug: "marta_heilerin", emoji: "🌿" },
  "Marta": { slug: "marta_heilerin", emoji: "🌿" },
  "Klara": { slug: "klara", emoji: "👵" },
  "Der Vogt": { slug: "vogt", emoji: "⚖️" },
  "Der Inspektor": { slug: "inspektor", emoji: "🧾" },
  "Joao der Andere": { slug: "joao", emoji: "📜" },

  // Italian PT -> IT cast
  "Antonio il Contadino": { slug: "antonio_contadino", emoji: "🌾" },
  "Antonio": { slug: "antonio_contadino", emoji: "🌾" },
  "Nico": { slug: "nico", emoji: "🧑‍🌾" },
  "Giulia la Fornaia": { slug: "giulia_fornaia", emoji: "🥖" },
  "Giulia": { slug: "giulia_fornaia", emoji: "🥖" },
  "Pietro": { slug: "pietro", emoji: "🪓" },
  "Il Mercante": { slug: "mercante", emoji: "🍎" },
  "La Guardia": { slug: "guardia", emoji: "💂" },
  "Bianca": { slug: "bianca", emoji: "🗝️" },
  "Chiara": { slug: "chiara", emoji: "✒️" },
  "Lucia la Guaritrice": { slug: "lucia_guaritrice", emoji: "🌿" },
  "Lucia": { slug: "lucia_guaritrice", emoji: "🌿" },
  "Donna Elena": { slug: "donna_elena", emoji: "👵" },
  "Elena": { slug: "donna_elena", emoji: "👵" },
  "Il Podesta": { slug: "podesta", emoji: "⚖️" },
  "L'Ispettore": { slug: "ispettore", emoji: "🧾" },
  "Mateusz l'Altro": { slug: "mateusz", emoji: "📜" },

  // Future Italian Catalina equivalent.
  "Sally": { slug: "sally", emoji: "✨" },
};
