import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: "center",
    padding: SPACING.lg,
    paddingVertical: 40,
  },
  glow: {
    alignSelf: "center",
    backgroundColor: "rgba(20, 184, 166, 0.08)",
    borderRadius: 360,
    height: 360,
    marginBottom: -360,
    marginTop: -80,
    width: 360,
  },
  shell: {
    alignSelf: "center",
    gap: SPACING["2xl"],
    maxWidth: 440,
    width: "100%",
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  logo: {
    height: 32,
    width: 112,
  },
  progress: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textAlign: "right",
  },
  progressBar: {
    backgroundColor: COLORS.gray200,
    borderRadius: RADIUS.full,
    height: 4,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: COLORS.primary,
    height: 4,
  },
  panel: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    gap: SPACING["2xl"],
    padding: 28,
    shadowColor: COLORS.gray900,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 24,
  },
  heading: {
    gap: 4,
  },
  title: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    lineHeight: 24,
  },
  subtitle: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    marginTop: 4,
  },
  label: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  section: {
    gap: 10,
  },
  stack: {
    gap: SPACING.sm,
  },
  card: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    borderWidth: 2,
    flexDirection: "row",
    gap: SPACING.md,
    minHeight: 58,
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
  },
  selected: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primary,
  },
  cardTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  cardCopy: {
    flex: 1,
    gap: 2,
  },
  cardDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.xs,
    fontWeight: "500",
  },
  flag: {
    borderRadius: 4,
    height: 17,
    width: 26,
  },
  levelGrid: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  levelPill: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.full,
    borderWidth: 2,
    flex: 1,
    gap: 2,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 10,
  },
  levelCode: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  levelLabel: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.xs,
    fontWeight: "600",
  },
  levelSelectedLabel: {
    color: COLORS.primary,
  },
  levelDetail: {
    color: COLORS.gray400,
    fontSize: 10,
    fontWeight: "600",
  },
  dayGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  day: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.full,
    borderWidth: 2,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  dayText: {
    color: COLORS.gray400,
    fontSize: 11,
    fontWeight: "700",
  },
  selectedDay: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  selectedDayText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: "700",
  },
  pillText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.sm,
    fontWeight: "600",
  },
  selectedPillText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "600",
  },
  dayError: {
    color: COLORS.error,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
  },
  sessionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  session: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.full,
    borderWidth: 2,
    paddingHorizontal: 18,
    paddingVertical: SPACING.sm,
  },
  estimate: {
    backgroundColor: COLORS.gray50,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    gap: 4,
    padding: SPACING.lg,
  },
  estimateTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  estimateDetail: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "600",
  },
  footer: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.lg,
  },
  back: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 52,
    width: 52,
  },
  submit: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    flex: 1,
    flexDirection: "row",
    gap: SPACING.sm,
    justifyContent: "center",
    minHeight: 52,
  },
  submitText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: "700",
  },
});
