import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingTop: SPACING["3xl"],
  },
  header: {
    gap: 4,
  },
  eyebrow: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  title: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "800",
    lineHeight: 36,
  },
  subtitle: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    lineHeight: 20,
  },
  monthNav: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACING.sm,
    padding: 6,
  },
  monthButton: {
    alignItems: "center",
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  monthLabel: {
    color: COLORS.gray700,
    flex: 1,
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "capitalize",
  },
  stats: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  metric: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flex: 1,
    padding: SPACING.md,
  },
  metricValue: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "800",
    textAlign: "center",
  },
  metricLabel: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    marginTop: 4,
    textAlign: "center",
    textTransform: "uppercase",
  },
  segmented: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    flexDirection: "row",
    gap: 4,
    padding: 4,
  },
  segment: {
    alignItems: "center",
    borderRadius: RADIUS.xs,
    flex: 1,
    height: 38,
    justifyContent: "center",
  },
  activeSegment: {
    backgroundColor: COLORS.white,
  },
  segmentText: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
  },
  activeSegmentText: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
  },
  panel: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.md,
    padding: SPACING.md,
  },
  panelHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACING.sm,
    justifyContent: "space-between",
  },
  panelTitle: {
    color: COLORS.gray900,
    flex: 1,
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    lineHeight: 24,
  },
  activeBadge: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.full,
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
  },
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  legendItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  legendDot: {
    borderRadius: RADIUS.full,
    height: 10,
    width: 10,
  },
  legendBorder: {
    borderColor: COLORS.gray300,
    borderWidth: 1.5,
  },
  legendText: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
  },
  calendar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  weekday: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "uppercase",
    width: 38,
  },
  day: {
    alignItems: "center",
    borderRadius: RADIUS.sm,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  today: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  completed: {
    backgroundColor: COLORS.success,
  },
  dayText: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    lineHeight: 14,
  },
  completedText: {
    color: COLORS.white,
  },
  countText: {
    color: COLORS.white,
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 10,
  },
  emptyCard: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    padding: SPACING.lg,
  },
  emptyTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    lineHeight: 20,
    marginTop: 4,
    textAlign: "center",
  },
  state: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  stateText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
    marginTop: 4,
    textAlign: "center",
  },
});
