import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING, getAdventureColors } from "@linguaflow/shared-core";

const adventureTheme = getAdventureColors("ES", "dark");

export const styles = StyleSheet.create({
  container: {
    backgroundColor: adventureTheme.bgFrom,
    flex: 1,
  },
  topbar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: SPACING.md,
    paddingTop: SPACING["3xl"],
  },
  backButton: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 9,
  },
  backText: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  sectionLabel: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  chat: {
    flex: 1,
  },
  chatContent: {
    gap: SPACING.md,
    padding: SPACING.md,
  },
  recap: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    padding: SPACING.md,
  },
  recapTitle: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  recapText: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.sm,
    lineHeight: 22,
    marginTop: SPACING.xs,
  },
  recapNow: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    marginTop: SPACING.sm,
  },
  scene: {
    backgroundColor: adventureTheme.goldAccentSoft,
    borderRadius: RADIUS.sm,
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    padding: SPACING.md,
    textAlign: "center",
  },
  narrative: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    lineHeight: 26,
  },
  narrativeBox: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  npc: {
    alignSelf: "flex-start",
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    maxWidth: "88%",
    padding: SPACING.md,
  },
  npcName: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    marginBottom: SPACING.xs,
    textTransform: "uppercase",
  },
  npcLine: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
    lineHeight: 24,
  },
  translation: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    lineHeight: 21,
    marginTop: SPACING.xs,
  },
  player: {
    alignSelf: "flex-end",
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    maxWidth: "88%",
    padding: SPACING.md,
  },
  correct: {
    alignSelf: "flex-end",
    backgroundColor: adventureTheme.goldAccentSoft,
    borderRadius: RADIUS.sm,
    maxWidth: "88%",
    padding: SPACING.md,
  },
  wrong: {
    alignSelf: "flex-end",
    backgroundColor: adventureTheme.surfaceMid,
    borderRadius: RADIUS.sm,
    maxWidth: "88%",
    padding: SPACING.md,
  },
  answerText: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  reveal: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
    textAlign: "center",
  },
  vocab: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  footer: {
    backgroundColor: adventureTheme.surfaceMid,
    gap: SPACING.sm,
    padding: SPACING.md,
    paddingBottom: SPACING.lg,
  },
  footerPrompt: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
  },
  choice: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    padding: SPACING.md,
  },
  choiceText: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: adventureTheme.goldAccent,
    borderRadius: RADIUS.sm,
    minHeight: 48,
    justifyContent: "center",
    paddingHorizontal: SPACING.md,
  },
  primaryText: {
    color: adventureTheme.ctaText,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  inputRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  input: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.sm,
    color: COLORS.gray900,
    flex: 1,
    minHeight: 48,
    paddingHorizontal: SPACING.md,
  },
  inputButton: {
    alignItems: "center",
    backgroundColor: adventureTheme.goldAccent,
    borderRadius: RADIUS.sm,
    justifyContent: "center",
    paddingHorizontal: SPACING.md,
  },
  summary: {
    alignItems: "center",
    gap: SPACING.md,
    padding: SPACING.lg,
  },
  complete: {
    alignItems: "center",
    backgroundColor: adventureTheme.bgFrom,
    flex: 1,
    gap: SPACING.md,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  completeTitle: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "700",
    textAlign: "center",
  },
  trophyBadge: {
    alignItems: "center",
    backgroundColor: adventureTheme.goldAccentSoft,
    borderColor: adventureTheme.goldAccent,
    borderRadius: 48,
    borderWidth: 1,
    height: 96,
    justifyContent: "center",
    shadowColor: adventureTheme.goldAccent,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    width: 96,
  },
  trophyIcon: {
    fontSize: 46,
  },
  starRow: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "900",
    letterSpacing: 0,
  },
  meta: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    textAlign: "center",
  },
  wordChip: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.full,
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  itemEmoji: {
    fontSize: 58,
    position: "absolute",
    top: 38,
    zIndex: 3,
  },
  chestReveal: {
    alignItems: "center",
    height: 132,
    justifyContent: "center",
    marginBottom: SPACING.sm,
    position: "relative",
    width: 170,
  },
  chestLid: {
    color: adventureTheme.goldAccent,
    fontSize: 34,
    fontWeight: "900",
    position: "absolute",
    top: 40,
    transform: [{ rotate: "-8deg" }],
  },
  chestBox: {
    color: "#d97706",
    fontSize: 84,
    position: "absolute",
    top: 52,
  },
  chestSparkLeft: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE["2xl"],
    left: 24,
    position: "absolute",
    top: 22,
  },
  chestSparkRight: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE["2xl"],
    position: "absolute",
    right: 18,
    top: 14,
  },
});
