import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  areaText: { flex: 1, gap: 2 },
  flag: { borderRadius: RADIUS.xs, height: 17, width: 26 },
  modalBackdrop: { backgroundColor: "rgba(0,0,0,0.42)", flex: 1, justifyContent: "flex-end", padding: SPACING.md },
  modalPanel: { backgroundColor: COLORS.white, borderRadius: RADIUS.lg, maxHeight: "88%", padding: SPACING.lg },
  modalHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: SPACING.md },
  modalTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.xl, fontWeight: "700" },
  modalClose: { backgroundColor: COLORS.gray100, borderRadius: RADIUS.sm, paddingHorizontal: SPACING.md, paddingVertical: 8 },
  modalCloseText: { color: COLORS.gray700, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  modalContent: { gap: SPACING.md },
  modalLabel: { color: COLORS.gray400, fontSize: FONT_SIZE.xs, fontWeight: "700", textTransform: "uppercase" },
  modalCard: { alignItems: "center", borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 2, flexDirection: "row", gap: SPACING.md, padding: SPACING.md },
  modalSelected: { backgroundColor: COLORS.primaryLight, borderColor: COLORS.primary },
  modalCardTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  modalCardDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  modalDayGrid: { flexDirection: "row", justifyContent: "space-between" },
  modalDay: { alignItems: "center", borderColor: COLORS.gray200, borderRadius: RADIUS.full, borderWidth: 2, height: 40, justifyContent: "center", width: 40 },
  modalDaySelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  modalDayText: { color: COLORS.gray500, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  modalDaySelectedText: { color: COLORS.white, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  modalSelectedText: { color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  modalPillGrid: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.sm },
  modalPill: { borderColor: COLORS.gray200, borderRadius: RADIUS.full, borderWidth: 2, paddingHorizontal: SPACING.md, paddingVertical: 10 },
  modalPrimary: { alignItems: "center", backgroundColor: COLORS.primary, borderRadius: RADIUS.md, minHeight: 48, justifyContent: "center" },
  modalPrimaryText: { color: COLORS.white, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  disabled: { opacity: 0.55 },
  dayError: { color: COLORS.error, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  confirmRow: { flexDirection: "row", gap: SPACING.sm },
  cancelButton: { alignItems: "center", backgroundColor: COLORS.gray100, borderRadius: RADIUS.sm, flex: 1, minHeight: 44, justifyContent: "center" },
  cancelText: { color: COLORS.gray700, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  dangerButton: { alignItems: "center", backgroundColor: "#dc2626", borderRadius: RADIUS.sm, flex: 1, minHeight: 44, justifyContent: "center" },
  dangerButtonText: { color: COLORS.white, fontSize: FONT_SIZE.sm, fontWeight: "700" },
});
