# Generated by Django 5.0.6 on 2026-05-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_dailystreak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=80)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('native', models.CharField(blank=True, max_length=120)),
                ('lang_code', models.CharField(blank=True, max_length=5)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('prata', 'Prata'), ('ouro', 'Ouro'), ('diamante', 'Diamante'), ('esmeralda', 'Esmeralda')], default='bronze', max_length=12)),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('user', 'word_id')},
            },
        ),
    ]
