# Generated by Django 5.0.6 on 2026-05-11 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_add_phase_section_and_word_mastery_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdventureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_key', models.CharField(max_length=80)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-set_at'],
                'unique_together': {('user', 'flag_key')},
            },
        ),
    ]
