# Generated by Django 5.0.6 on 2026-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_wordmastery_error_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmastery',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordmastery',
            name='ever_correct',
            field=models.BooleanField(default=False),
        ),
    ]
