import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.gray50,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingBottom: SPACING["3xl"],
  },
  heroCard: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    padding: SPACING.xl,
  },
  heroTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  levelPill: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.full,
    color: COLORS.primaryHover,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  percent: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
  },
  languageRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.lg,
  },
  flag: {
    borderRadius: 4,
    height: 24,
    width: 32,
  },
  languageTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "700",
    lineHeight: 34,
  },
  languagePath: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    marginTop: 4,
  },
  progressMeta: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "600",
    marginTop: SPACING.sm,
  },
  progressTrack: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.full,
    height: 8,
    marginTop: SPACING.lg,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    height: 8,
  },
  phrases: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "600",
    marginTop: SPACING.sm,
  },
  primaryAction: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    justifyContent: "center",
    marginTop: SPACING.lg,
    minHeight: 48,
    overflow: "hidden",
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
  },
  primaryActionText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
    textAlign: "center",
  },
  statsGrid: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.md,
    flexDirection: "row",
    gap: 1,
    overflow: "hidden",
  },
  statCard: {
    backgroundColor: COLORS.white,
    flex: 1,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.lg,
  },
  statValue: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
    lineHeight: 26,
  },
  statValueAccent: {
    color: COLORS.primary,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
    lineHeight: 26,
  },
  statLabel: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    marginTop: 6,
  },
  routineCard: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    padding: SPACING.lg,
  },
  routineLabel: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  routineTitle: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    marginTop: SPACING.sm,
  },
  routineDetail: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "500",
    marginTop: 2,
  },
  state: {
    alignItems: "center",
    backgroundColor: COLORS.gray50,
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  stateTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
    textAlign: "center",
  },
  stateDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    marginTop: SPACING.sm,
    textAlign: "center",
  },
});
