import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: { backgroundColor: COLORS.white, flex: 1 },
  content: { gap: SPACING.md, padding: SPACING.lg, paddingBottom: SPACING["3xl"] },
  header: { gap: SPACING.md },
  eyebrow: { color: COLORS.primary, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  title: { color: COLORS.gray900, fontSize: FONT_SIZE["3xl"], fontWeight: "700", lineHeight: 34 },
  subtitle: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "600" },
  reviewPill: { alignSelf: "flex-start", borderColor: COLORS.gray200, borderRadius: RADIUS.full, borderWidth: 1, color: COLORS.gray600, fontSize: FONT_SIZE.sm, fontWeight: "700", paddingHorizontal: SPACING.md, paddingVertical: 8 },
  tabs: { backgroundColor: COLORS.gray100, borderColor: COLORS.gray200, borderRadius: RADIUS.sm, borderWidth: 1, flexDirection: "row", gap: SPACING.xs, padding: SPACING.xs },
  tab: { alignItems: "center", borderRadius: 6, flex: 1, minHeight: 42, justifyContent: "center" },
  activeTab: { alignItems: "center", backgroundColor: COLORS.white, borderRadius: 6, flex: 1, minHeight: 42, justifyContent: "center" },
  tabText: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  activeTabText: { color: COLORS.primary, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  hero: { backgroundColor: COLORS.primaryLight, borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, gap: SPACING.sm, padding: SPACING.lg },
  iconBubble: { alignItems: "center", backgroundColor: COLORS.primary, borderRadius: RADIUS.full, height: 44, justifyContent: "center", width: 44 },
  card: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, gap: SPACING.md, padding: SPACING.lg },
  cardHeader: { alignItems: "flex-start", flexDirection: "row", gap: SPACING.md, justifyContent: "space-between" },
  cardHeaderText: { flex: 1, gap: 3 },
  cardLabel: { color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700", textTransform: "uppercase" },
  cardTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.xl, fontWeight: "700" },
  cardDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  description: { color: COLORS.gray600, fontSize: FONT_SIZE.sm, fontWeight: "500", lineHeight: 20 },
  heroActions: { gap: SPACING.sm, marginTop: SPACING.sm },
  action: { backgroundColor: COLORS.primary, borderRadius: RADIUS.sm, color: COLORS.white, fontSize: FONT_SIZE.sm, fontWeight: "700", overflow: "hidden", paddingHorizontal: SPACING.md, paddingVertical: 12, textAlign: "center" },
  actionButton: { alignItems: "center", backgroundColor: COLORS.primary, borderRadius: RADIUS.sm, minHeight: 44, justifyContent: "center", paddingHorizontal: SPACING.md },
  actionText: { color: COLORS.white, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  secondaryAction: { alignItems: "center", backgroundColor: COLORS.white, borderColor: COLORS.gray200, borderRadius: RADIUS.sm, borderWidth: 1, minHeight: 44, justifyContent: "center" },
  secondaryActionText: { color: COLORS.primary, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  disabled: { opacity: 0.5 },
  countPill: { backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.full, color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700", paddingHorizontal: 10, paddingVertical: 8 },
  phraseRow: { backgroundColor: COLORS.gray50, borderColor: COLORS.gray200, borderRadius: RADIUS.sm, borderWidth: 1, gap: SPACING.xs, padding: SPACING.md },
  phraseSource: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  phraseTarget: { color: COLORS.gray900, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  emptyDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "600" },
  reviewCard: { alignItems: "center", borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, flexDirection: "row", gap: SPACING.md, padding: SPACING.lg },
  reviewIcon: { alignItems: "center", backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.full, height: 38, justifyContent: "center", width: 38 },
  trail: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, gap: SPACING.md, padding: SPACING.lg },
  moduleCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.sm, borderWidth: 1, overflow: "hidden" },
  moduleHeader: { backgroundColor: COLORS.gray50, gap: 2, padding: SPACING.md },
  moduleLabel: { color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700", textTransform: "uppercase" },
  moduleTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.base, fontWeight: "700" },
  lessonRow: { alignItems: "center", borderTopColor: COLORS.gray200, borderTopWidth: 1, flexDirection: "row", gap: SPACING.sm, padding: SPACING.md },
  currentLesson: { backgroundColor: COLORS.primaryLight },
  lessonIcon: { color: COLORS.primary, fontSize: FONT_SIZE.lg, fontWeight: "700", width: 24 },
  lessonTitle: { color: COLORS.gray800, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  lessonCount: { color: COLORS.gray500, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  reviewPage: { alignItems: "center", backgroundColor: COLORS.white, flex: 1, gap: SPACING.md, justifyContent: "center", padding: SPACING.lg },
  reviewOptions: { gap: SPACING.sm, width: "100%" },
  optionButton: { backgroundColor: COLORS.primary, borderRadius: RADIUS.sm, padding: SPACING.md },
  optionText: { color: COLORS.white, fontSize: FONT_SIZE.base, fontWeight: "700" },
  reviewInput: { flexDirection: "row", gap: SPACING.sm, width: "100%" },
  input: { borderColor: COLORS.gray200, borderRadius: RADIUS.sm, borderWidth: 1, flex: 1, minHeight: 44, paddingHorizontal: SPACING.md },
  smallButton: { alignItems: "center", backgroundColor: COLORS.primary, borderRadius: RADIUS.sm, justifyContent: "center", paddingHorizontal: SPACING.md },
  secondaryButton: { backgroundColor: COLORS.gray100, borderRadius: RADIUS.sm, paddingHorizontal: SPACING.md, paddingVertical: 10 },
  secondaryText: { color: COLORS.gray700, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  lessonRunnerCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.lg, borderWidth: 1, gap: SPACING.sm, padding: SPACING.lg, width: "100%" },
  runnerPhrase: { color: COLORS.gray900, fontSize: FONT_SIZE["2xl"], fontWeight: "700" },
  runnerTarget: { color: COLORS.primary, fontSize: FONT_SIZE["2xl"], fontWeight: "700" },
  state: { alignItems: "center", backgroundColor: COLORS.white, flex: 1, justifyContent: "center", padding: SPACING.lg },
  stateText: { color: COLORS.gray600, fontSize: FONT_SIZE.base },
});
