export interface CharacterAvatarMeta {
  slug: string;
  emoji?: string;
}

export const CHARACTER_AVATARS: Record<string, CharacterAvatarMeta> = {
  "Don Miguel el Campesino": { slug: "don_miguel" },
  "Miguel el Campesino": { slug: "miguel" },
  "Rosa la Panadera": { slug: "rosa" },
  Ernesto: { slug: "ernesto" },
  "El Mercader": { slug: "mercader" },
  "El Vigilante del Mercado": { slug: "vigilante" },
  "Senora Carmen": { slug: "senora_carmen" },
  "Señora Carmen": { slug: "senora_carmen" },
  Sofia: { slug: "sofia" },
  "Sofía": { slug: "sofia" },
  Maria: { slug: "maria" },
  "María": { slug: "maria" },
  "Dona Lucia": { slug: "dona_lucia" },
  "Doña Lucía": { slug: "dona_lucia" },
  "El Alcalde": { slug: "alcalde" },
  "El Inspector": { slug: "inspector" },
  Catalina: { slug: "catalina" },
  Rodrigo: { slug: "rodrigo" },
  James: { slug: "james" },
  Valentina: { slug: "valentina" },
  "Don Miguel": { slug: "don_miguel" },
  Miguel: { slug: "miguel" },
  Rosa: { slug: "rosa" },
  Mercader: { slug: "mercader" },
  "El Vigilante": { slug: "vigilante" },
  Carmen: { slug: "senora_carmen" },
  Alcalde: { slug: "alcalde" },
  Inspector: { slug: "inspector" },

  "Elias der Bauer": { slug: "bauer_elias" },
  Elias: { slug: "bauer_elias" },
  Otto: { slug: "otto" },
  "Hanna die Baeckerin": { slug: "hanna_baeckerin" },
  Hanna: { slug: "hanna_baeckerin" },
  Friedrich: { slug: "friedrich" },
  "Der Markthaendler": { slug: "markthaendler" },
  "Der Waechter": { slug: "waechter" },
  Greta: { slug: "greta" },
  Lina: { slug: "lina" },
  "Marta die Heilerin": { slug: "marta_heilerin" },
  Marta: { slug: "marta_heilerin" },
  Klara: { slug: "klara" },
  "Der Vogt": { slug: "vogt" },
  "Der Inspektor": { slug: "inspektor" },
  "Joao der Andere": { slug: "joao" },
  Katharina: { slug: "katharina" },

  "Antonio il Contadino": { slug: "antonio_contadino" },
  Antonio: { slug: "antonio_contadino" },
  Nico: { slug: "nico" },
  "Giulia la Fornaia": { slug: "giulia_fornaia" },
  Giulia: { slug: "giulia_fornaia" },
  Pietro: { slug: "pietro" },
  "Il Mercante": { slug: "mercante" },
  "La Guardia": { slug: "guardia" },
  Bianca: { slug: "bianca" },
  Chiara: { slug: "chiara" },
  "Lucia la Guaritrice": { slug: "lucia_guaritrice" },
  Lucia: { slug: "lucia_guaritrice" },
  "Donna Elena": { slug: "donna_elena" },
  Elena: { slug: "donna_elena" },
  "Il Podesta": { slug: "podesta" },
  "L'Ispettore": { slug: "ispettore" },
  "Mateusz l'Altro": { slug: "mateusz" },
  Sally: { slug: "sally" },
};

export function getCharacterAvatar(name: string): CharacterAvatarMeta | undefined {
  return CHARACTER_AVATARS[name];
}
