# Generated by Django 5.0.6 on 2026-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_studymodule_scenario_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='studymodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
