# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_alter_scenario_options_alter_studymodule_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="objective",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="lesson",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="exercise_notes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
