import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingTop: SPACING["3xl"],
  },
  userCard: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACING.md,
    padding: SPACING.md,
  },
  avatar: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    color: COLORS.white,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    height: 54,
    overflow: "hidden",
    paddingTop: 13,
    textAlign: "center",
    width: 54,
  },
  userText: {
    flex: 1,
  },
  username: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.lg,
    fontWeight: "700",
  },
  email: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
  },
  logout: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 9,
  },
  logoutText: {
    color: COLORS.gray700,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  card: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  label: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  cardTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
  },
  cardDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
  },
  progress: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.full,
    height: 8,
    marginTop: SPACING.sm,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: COLORS.primary,
    height: "100%",
  },
  goalCard: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  goalTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  historyLink: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: SPACING.md,
    paddingVertical: 12,
    textAlign: "center",
  },
  secondaryAction: {
    alignSelf: "flex-start",
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    marginTop: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 9,
  },
  secondaryActionText: {
    color: COLORS.gray700,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  dangerOutline: {
    alignSelf: "flex-start",
    borderColor: "#fecaca",
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    marginTop: SPACING.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  dangerText: {
    color: "#dc2626",
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  addArea: {
    alignItems: "center",
    borderColor: COLORS.gray300,
    borderRadius: RADIUS.sm,
    borderStyle: "dashed",
    borderWidth: 1,
    minHeight: 46,
    justifyContent: "center",
  },
  addAreaText: {
    color: COLORS.gray700,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  modalBackdrop: {
    backgroundColor: "rgba(0,0,0,0.42)",
    flex: 1,
    justifyContent: "flex-end",
    padding: SPACING.md,
  },
  modalPanel: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    maxHeight: "88%",
    padding: SPACING.lg,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  modalTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
  },
  modalClose: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 8,
  },
  modalCloseText: {
    color: COLORS.gray700,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  modalContent: {
    gap: SPACING.md,
  },
  modalLabel: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  modalCard: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  modalSelected: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primary,
  },
  modalCardTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  modalCardDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
  },
  modalDayGrid: {
    flexDirection: "row",
    gap: 6,
  },
  modalDay: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: "center",
  },
  modalDayText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
  },
  modalSelectedText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
  },
  modalPillGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  modalPill: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
  },
  modalPrimary: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    minHeight: 48,
    justifyContent: "center",
  },
  modalPrimaryText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  disabled: {
    opacity: 0.55,
  },
  confirmRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  cancelButton: {
    alignItems: "center",
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  cancelText: {
    color: COLORS.gray700,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#dc2626",
    borderRadius: RADIUS.sm,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  dangerButtonText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  state: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  stateText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.base,
  },
});
