import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: { backgroundColor: COLORS.white, flex: 1 },
  content: { gap: SPACING.md, padding: SPACING.lg, paddingBottom: SPACING["3xl"] },
  userCard: { alignItems: "center", borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, flexDirection: "row", gap: SPACING.lg, padding: SPACING.lg },
  avatar: { backgroundColor: COLORS.primary, borderRadius: RADIUS.full, color: COLORS.white, fontSize: FONT_SIZE.xl, fontWeight: "700", height: 54, lineHeight: 54, textAlign: "center", width: 54 },
  userText: { flex: 1, minWidth: 0 },
  username: { color: COLORS.gray900, fontSize: FONT_SIZE.lg, fontWeight: "700" },
  email: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  member: { color: COLORS.gray400, fontSize: FONT_SIZE.xs, marginTop: 2 },
  courseCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, padding: SPACING.lg },
  courseHeader: { alignItems: "flex-start", flexDirection: "row", gap: SPACING.lg },
  courseText: { flex: 1, gap: SPACING.xs },
  cardTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.xl, fontWeight: "700" },
  badgeRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: SPACING.sm },
  langBadge: { backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.full, color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700", paddingHorizontal: 10, paddingVertical: 2 },
  levelBadge: { color: COLORS.gray400, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  divider: { backgroundColor: COLORS.gray100, height: 1, marginVertical: SPACING.lg },
  routineRow: { alignItems: "center", flexDirection: "row", gap: SPACING.sm },
  routineText: { color: COLORS.gray600, flex: 1, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  linkText: { color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  weekCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, padding: SPACING.lg },
  weekHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  sectionLabel: { color: COLORS.gray400, fontSize: FONT_SIZE.xs, fontWeight: "700", textTransform: "uppercase" },
  weekGrid: { flexDirection: "row", gap: SPACING.xs, marginTop: SPACING.md },
  weekDay: { alignItems: "center", flex: 1, gap: SPACING.xs },
  weekDate: { borderRadius: RADIUS.sm, color: COLORS.gray300, fontSize: FONT_SIZE.xs, fontWeight: "700", height: 36, lineHeight: 36, textAlign: "center", width: "100%" },
  plannedDay: { backgroundColor: COLORS.gray100, color: COLORS.gray600 },
  completedDay: { backgroundColor: COLORS.primary, color: COLORS.white },
  weekLabel: { color: COLORS.gray300, fontSize: 9, fontWeight: "700", textTransform: "uppercase" },
  listCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, overflow: "hidden" },
  areaRow: { alignItems: "center", borderTopColor: COLORS.gray100, borderTopWidth: 1, flexDirection: "row", gap: SPACING.sm, padding: SPACING.md },
  areaText: { flex: 1, gap: 2 },
  areaTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  areaDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.xs, fontWeight: "500" },
  useButton: { backgroundColor: COLORS.primary, borderRadius: RADIUS.sm, paddingHorizontal: SPACING.md, paddingVertical: 8 },
  useButtonText: { color: COLORS.white, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  trashButton: { alignItems: "center", borderColor: "#fecaca", borderRadius: RADIUS.sm, borderWidth: 1, height: 32, justifyContent: "center", width: 32 },
  addArea: { alignItems: "center", borderColor: COLORS.gray300, borderRadius: RADIUS.md, borderStyle: "dashed", borderWidth: 1, flexDirection: "row", gap: SPACING.md, padding: SPACING.lg },
  addIcon: { alignItems: "center", backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.full, height: 36, justifyContent: "center", width: 36 },
  addAreaTitle: { color: COLORS.gray900, fontSize: FONT_SIZE.sm, fontWeight: "700" },
  addAreaDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.xs, fontWeight: "500" },
  planCard: { borderColor: COLORS.gray200, borderRadius: RADIUS.md, borderWidth: 1, gap: SPACING.sm, padding: SPACING.lg },
  planRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  planName: { color: COLORS.gray900, fontSize: FONT_SIZE.base, fontWeight: "700" },
  planDetail: { color: COLORS.gray500, fontSize: FONT_SIZE.sm, fontWeight: "500" },
  upgradeButton: { backgroundColor: COLORS.primaryLight, borderRadius: RADIUS.sm, paddingHorizontal: SPACING.md, paddingVertical: 9 },
  upgradeText: { color: COLORS.primary, fontSize: FONT_SIZE.xs, fontWeight: "700" },
  signOut: { alignItems: "center", borderColor: "#fecaca", borderRadius: RADIUS.sm, borderWidth: 1, minHeight: 46, justifyContent: "center" },
  signOutText: { color: "#dc2626", fontSize: FONT_SIZE.sm, fontWeight: "700" },
  flag: { borderRadius: RADIUS.xs, height: 17, width: 26 },
  flagLarge: { borderRadius: RADIUS.xs, height: 32, width: 48 },
  state: { alignItems: "center", backgroundColor: COLORS.white, flex: 1, justifyContent: "center", padding: SPACING.lg },
  stateText: { color: COLORS.gray600, fontSize: FONT_SIZE.base },
});
