from apps.adventure.models import AdventureItem


SOURCE_LANGUAGE = {"code": "EN", "name": "English", "is_ready": False}
TARGET_LANGUAGE = {"code": "DE", "name": "Deutsch", "is_ready": True}

CHAPTER = {
    "slug": "de-a1-t1",
    "level": "A1",
    "order": 2,
    "title": "Das Dorf",
    "subtitle": "T1 - The arrival",
    "background": "de_dorf",
    "boss_name": "Der Vogt",
    "boss_intro": (
        "The official who controls the village seal. Nobody passes toward the northern road "
        "without his mark, and he does not grant marks freely."
    ),
    "reward_name": "Siegel des Dorfes",
    "reward_description": (
        "Pressed into red wax. Proof that you survived the village and learned its rules."
    ),
}

SCENARIOS = [
    ("de-social", "Social", "Greetings, names, politeness, and first contact."),
    ("de-orte", "Places", "Directions, buildings, and movement through the village."),
    ("de-essen", "Food", "Food, drink, hunger, and tavern scenes."),
    ("de-markt", "Market", "Prices, numbers, trades, and permissions."),
    ("de-gesundheit", "Health", "Body, illness, remedies, and care."),
    ("de-arbeit", "Work", "Jobs, routines, tools, and obligations."),
    ("de-geschichte", "Memory", "Past, secrets, family, and the letter."),
    ("de-pruefung", "Trial", "Conflict, proof, authority, and the boss phase."),
]

PHRASES = [
    ("Hello", "Hallo", "de-social"),
    ("Good morning", "Guten Morgen", "de-social"),
    ("Good evening", "Guten Abend", "de-social"),
    ("Goodbye", "Auf Wiedersehen", "de-social"),
    ("See you soon", "Bis bald", "de-social"),
    ("My name is", "Ich heisse", "de-social"),
    ("What is your name?", "Wie heisst du?", "de-social"),
    ("Please", "Bitte", "de-social"),
    ("Thank you", "Danke", "de-social"),
    ("Yes", "Ja", "de-social"),
    ("No", "Nein", "de-social"),
    ("Friend", "Freund", "de-social"),
    ("Stranger", "Fremder", "de-social"),
    ("Step by step", "Schritt fuer Schritt", "de-social"),
    ("Where is it?", "Wo ist es?", "de-orte"),
    ("Here", "Hier", "de-orte"),
    ("There", "Dort", "de-orte"),
    ("Left", "Links", "de-orte"),
    ("Right", "Rechts", "de-orte"),
    ("The market", "Der Markt", "de-orte"),
    ("The square", "Der Platz", "de-orte"),
    ("The gate", "Das Tor", "de-orte"),
    ("The road", "Der Weg", "de-orte"),
    ("The forest", "Der Wald", "de-orte"),
    ("I am hungry", "Ich habe Hunger", "de-essen"),
    ("I am thirsty", "Ich habe Durst", "de-essen"),
    ("Water", "Wasser", "de-essen"),
    ("Bread", "Brot", "de-essen"),
    ("Soup", "Suppe", "de-essen"),
    ("Apple", "Apfel", "de-essen"),
    ("I want to eat", "Ich moechte essen", "de-essen"),
    ("It is good", "Es ist gut", "de-essen"),
    ("The table", "Der Tisch", "de-essen"),
    ("How much does it cost?", "Wie viel kostet das?", "de-markt"),
    ("Expensive", "Teuer", "de-markt"),
    ("Cheap", "Billig", "de-markt"),
    ("I want to buy", "Ich moechte kaufen", "de-markt"),
    ("Money", "Geld", "de-markt"),
    ("Coin", "Muenze", "de-markt"),
    ("One", "Eins", "de-markt"),
    ("Two", "Zwei", "de-markt"),
    ("Three", "Drei", "de-markt"),
    ("Permission", "Erlaubnis", "de-markt"),
    ("I am sick", "Ich bin krank", "de-gesundheit"),
    ("It hurts here", "Es tut hier weh", "de-gesundheit"),
    ("Remedy", "Medizin", "de-gesundheit"),
    ("Rest", "Ruhe", "de-gesundheit"),
    ("Hand", "Hand", "de-gesundheit"),
    ("Head", "Kopf", "de-gesundheit"),
    ("Tired", "Muede", "de-gesundheit"),
    ("Better", "Besser", "de-gesundheit"),
    ("Smith", "Schmied", "de-arbeit"),
    ("Baker", "Baeckerin", "de-arbeit"),
    ("Guard", "Waechter", "de-arbeit"),
    ("Work", "Arbeit", "de-arbeit"),
    ("I come from far away", "Ich komme von weit her", "de-arbeit"),
    ("I must go", "Ich muss gehen", "de-arbeit"),
    ("I can help", "Ich kann helfen", "de-arbeit"),
    ("I do not remember", "Ich erinnere mich nicht", "de-geschichte"),
    ("My past", "Meine Vergangenheit", "de-geschichte"),
    ("Secret", "Geheimnis", "de-geschichte"),
    ("Danger", "Gefahr", "de-geschichte"),
    ("Truth", "Wahrheit", "de-geschichte"),
    ("Lie", "Luege", "de-geschichte"),
    ("Brother", "Bruder", "de-geschichte"),
    ("I heard it", "Ich habe es gehoert", "de-geschichte"),
    ("Test", "Pruefung", "de-pruefung"),
    ("Show", "Zeigen", "de-pruefung"),
    ("Respect", "Respekt", "de-pruefung"),
    ("Judgment", "Urteil", "de-pruefung"),
    ("Authority", "Macht", "de-pruefung"),
    ("Welcome", "Willkommen", "de-pruefung"),
    ("Seal", "Siegel", "de-pruefung"),
    ("Fire", "Feuer", "de-pruefung"),
]

PHASES = [
    {"number": 1, "phase_type": "story", "title": "Awakening in the Field", "scenario_slug": "de-social", "phrase_count": 8, "key_words": ["hallo", "ich heisse", "fremder", "bauer", "gut"], "focus": "first contact", "grammar": "ich bin / ich heisse", "new": [("hello", "Hallo"), ("my name is", "Ich heisse"), ("stranger", "Fremder")]},
    {"number": 2, "phase_type": "story", "title": "The Village Wakes", "scenario_slug": "de-essen", "phrase_count": 8, "key_words": ["brot", "wasser", "hunger", "durst"], "focus": "food and need", "grammar": "haben for hunger/thirst", "new": [("bread", "Brot"), ("water", "Wasser"), ("I am hungry", "Ich habe Hunger")]},
    {"number": 3, "phase_type": "story", "title": "The Dirt Road", "scenario_slug": "de-orte", "phrase_count": 8, "key_words": ["wald", "stein", "fluss", "hier", "dort"], "focus": "places outside the walls", "grammar": "der/die/das first exposure", "new": [("the forest", "der Wald"), ("the stone", "der Stein"), ("here", "hier")]},
    {"number": 4, "phase_type": "story", "title": "The Market", "scenario_slug": "de-markt", "phrase_count": 8, "key_words": ["eins", "zwei", "drei", "teuer", "billig"], "focus": "numbers and prices", "grammar": "Wie viel kostet das?", "new": [("one", "eins"), ("two", "zwei"), ("three", "drei")]},
    {"number": 5, "phase_type": "story", "title": "The First Spark", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["feuer", "angst", "laufen", "halt"], "focus": "first manifestation of the living word", "grammar": "imperatives", "new": [("fire", "Feuer"), ("fear", "Angst"), ("run", "Lauf!")]},
    {"number": 6, "phase_type": "story", "title": "What Lina Saw", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["licht", "funke", "lampe"], "focus": "Lina joins after seeing the gift", "grammar": "present tense: ich gehe, du kommst", "new": [("light", "Licht"), ("spark", "Funke"), ("lamp", "Lampe")]},
    {"number": 7, "phase_type": "story", "title": "A Normal Day", "scenario_slug": "de-orte", "phrase_count": 8, "key_words": ["links", "rechts", "platz", "tor"], "focus": "navigation and suspicion", "grammar": "verb-second word order", "new": [("left", "links"), ("right", "rechts"), ("gate", "Tor")]},
    {"number": 8, "phase_type": "story", "title": "The Healer", "scenario_slug": "de-gesundheit", "phrase_count": 8, "key_words": ["krank", "medizin", "hand", "kopf"], "focus": "Marta joins the group", "grammar": "accusative exposure: den/die/das", "new": [("sick", "krank"), ("remedy", "Medizin"), ("hand", "Hand")]},
    {"number": 9, "phase_type": "story", "title": "Four at the Table", "scenario_slug": "de-essen", "phrase_count": 8, "key_words": ["suppe", "tisch", "essen", "trinken"], "focus": "the group becomes a unit", "grammar": "moechte + infinitive", "new": [("soup", "Suppe"), ("table", "Tisch"), ("I would like", "Ich moechte")]},
    {"number": 10, "phase_type": "story", "title": "The Watchman's Shadow", "scenario_slug": "de-arbeit", "phrase_count": 8, "key_words": ["waechter", "arbeit", "erlaubnis"], "focus": "institutional pressure appears", "grammar": "negation: nicht / kein", "new": [("guard", "Waechter"), ("work", "Arbeit"), ("permission", "Erlaubnis")]},
    {"number": 11, "phase_type": "story", "title": "The Town Hall", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["vogt", "siegel", "urteil"], "focus": "authority names the rules", "grammar": "future intent: ich werde / ich gehe", "new": [("seal", "Siegel"), ("judgment", "Urteil"), ("authority", "Macht")]},
    {"number": 12, "phase_type": "story", "title": "Three Days", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["gestern", "heute", "morgen", "gehoert"], "focus": "time and memory pressure", "grammar": "perfect exposure: ich habe gehoert", "new": [("yesterday", "gestern"), ("today", "heute"), ("I heard", "ich habe gehoert")]},
    {"number": 13, "phase_type": "story", "title": "Otto's Family", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["familie", "mein", "dein", "sein"], "focus": "family vocabulary and belonging", "grammar": "possessives: mein/dein/sein", "new": [("family", "Familie"), ("my", "mein"), ("your", "dein")]},
    {"number": 14, "phase_type": "review", "title": "Dinner at Marta's", "scenario_slug": "de-essen", "phrase_count": 8, "key_words": ["der", "die", "das", "gut"], "focus": "third review and articles", "grammar": "article review", "new": [("the bread", "das Brot"), ("the soup", "die Suppe"), ("the table", "der Tisch")]},
    {"number": 15, "phase_type": "story", "title": "The First Witness", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["zeuge", "hoch", "klein", "wahr"], "focus": "someone confirms the gift", "grammar": "adjectives without deep endings", "new": [("witness", "Zeuge"), ("true", "wahr"), ("small", "klein")]},
    {"number": 16, "phase_type": "story", "title": "Greta's Warning", "scenario_slug": "de-markt", "phrase_count": 8, "key_words": ["kaufen", "geld", "muenze", "warnung"], "focus": "Greta controls information at the market", "grammar": "modal verb: wollen", "new": [("money", "Geld"), ("coin", "Muenze"), ("I want", "Ich will")]},
    {"number": 17, "phase_type": "story", "title": "The Mark", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["zeichen", "schon", "noch nicht"], "focus": "the old sign appears", "grammar": "schon / noch nicht", "new": [("mark", "Zeichen"), ("already", "schon"), ("not yet", "noch nicht")]},
    {"number": 18, "phase_type": "story", "title": "Elias Remembers", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["erinnern", "vergangenheit", "geheimnis"], "focus": "mentor reveals old knowledge", "grammar": "koennen / muessen", "new": [("remember", "erinnern"), ("past", "Vergangenheit"), ("secret", "Geheimnis")]},
    {"number": 19, "phase_type": "review", "title": "The Letter Opens", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["brief", "zurueck", "kommst"], "focus": "fourth review and first letter word", "grammar": "separable-style movement: zurueckkommen", "new": [("letter", "Brief"), ("you return", "du kommst zurueck"), ("north", "Norden")]},
    {"number": 20, "phase_type": "story", "title": "The Inspector", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["inspektor", "muss", "gehen"], "focus": "outside pressure arrives", "grammar": "muss + infinitive", "new": [("I must", "Ich muss"), ("go", "gehen"), ("inspector", "Inspektor")]},
    {"number": 21, "phase_type": "story", "title": "Facing Marta", "scenario_slug": "de-gesundheit", "phrase_count": 8, "key_words": ["wenn", "kraut", "helfen"], "focus": "hard questions inside the group", "grammar": "wenn clauses exposure", "new": [("when/if", "wenn"), ("herb", "Kraut"), ("help", "helfen")]},
    {"number": 22, "phase_type": "story", "title": "Greta's Truth", "scenario_slug": "de-geschichte", "phrase_count": 8, "key_words": ["wahrheit", "luege", "umschlag"], "focus": "truth about the sealed letter", "grammar": "truth/lie contrast", "new": [("truth", "Wahrheit"), ("lie", "Luege"), ("envelope", "Umschlag")]},
    {"number": 23, "phase_type": "story", "title": "Before the Vogt", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["wenn", "zeigen", "respekt"], "focus": "terms of the coming trial", "grammar": "conditional exposure with wenn", "new": [("show", "zeigen"), ("respect", "Respekt"), ("if", "wenn")]},
    {"number": 24, "phase_type": "story", "title": "The Eve", "scenario_slug": "de-arbeit", "phrase_count": 8, "key_words": ["soll", "bereit", "morgen"], "focus": "last preparation before judgment", "grammar": "sollen / should", "new": [("should", "soll"), ("ready", "bereit"), ("tomorrow", "morgen")]},
    {"number": 25, "phase_type": "boss", "title": "Judgment at the Gate", "scenario_slug": "de-pruefung", "phrase_count": 8, "key_words": ["siegel", "bruder", "willkommen"], "focus": "boss trial, village seal, brother reveal", "grammar": "A1 synthesis", "new": [("seal", "Siegel"), ("brother", "Bruder"), ("welcome", "Willkommen")]},
]

CHARACTERS = [
    ("bauer_elias", "Elias der Bauer", "Bauer", "🌾", "ally", True, 1, 1, "An older farmer near the village fields. Slow, careful, and protective.", "Schritt fuer Schritt, Freund."),
    ("otto", "Otto", "Bauernsohn", "🧑‍🌾", "ally", True, 1, 2, "Elias's son, quick in the streets and willing to bridge broken English for the stranger.", "Stay near me, stranger. People here talk fast."),
    ("hanna_baeckerin", "Hanna die Baeckerin", "Baeckerin", "🥖", "npc", False, 1, 3, "A warm baker with flour on her sleeves and a sharp ear for gossip.", "Guten Morgen. Brot ist noch warm."),
    ("friedrich", "Friedrich", "Holzfaeller", "🪓", "npc", False, 3, 4, "A quiet woodcutter who knows the river path and old signs in the bark.", "Der Wald hoert mehr, als Menschen sagen."),
    ("markthaendler", "Der Markthaendler", "Haendler", "🍎", "npc", False, 4, 5, "A calculating seller who weighs coins, apples, and silence.", "Drei Aepfel, zwei Muenzen."),
    ("waechter", "Der Waechter", "Waechter", "💂", "npc", False, 5, 6, "The market guard who blocks doors and asks for papers.", "Erlaubnis oder Tor. Mehr gibt es nicht."),
    ("greta", "Greta", "Nachbarin", "🗝️", "npc", False, 4, 7, "A neighbor who notices every debt and every rumor in the village.", "Danke ist ein kleines Wort, aber es oeffnet Tueren."),
    ("lina", "Lina", "Schreiberin", "✒️", "ally", False, 6, 8, "A young scribe who sees the living word ignite a lamp and decides to believe.", "Worte haben Gewicht. Deine Worte haben Feuer."),
    ("marta_heilerin", "Marta die Heilerin", "Heilerin", "🌿", "ally", False, 8, 9, "A healer with bitter herbs and older knowledge than she admits.", "Krankheit luegt selten. Menschen schon."),
    ("klara", "Klara", "Mutter", "👵", "npc", False, 13, 10, "Otto's mother, the family voice in the house before the trial hardens.", "Iss erst. Fragen koennen warten."),
    ("vogt", "Der Vogt", "Vogt", "⚖️", "boss", False, 11, 11, "The official who turns village law into a weapon.", "Ein Fremder bleibt nur, wenn das Dorf es erlaubt."),
    ("inspektor", "Der Inspektor", "Inspektor", "🧾", "npc", False, 20, 12, "An outsider in uniform, colder than the local guard and harder to read.", "Ich stelle Fragen. Sie antworten."),
    ("joao", "Joao der Andere", "Anderer Fremder", "📜", "npc", False, 19, 13, "A Portuguese trace in the records, neither English nor German, tied to the old letter.", "Some strangers arrive before you. Some leave messages."),
]

PHASE1_ITEMS = [
    {"slug": "frisches_brot", "emoji": "B", "name": "Frisches Brot", "word_id": "de_brot", "item_tag": AdventureItem.TAG_COMIDA, "action": AdventureItem.ACTION_USAR, "source_character_slug": "hanna_baeckerin", "order": 1, "lore": "Warm from Hanna's oven. The first kind thing the village gives you."},
    {"slug": "apfel_vom_feld", "emoji": "A", "name": "Apfel vom Feld", "word_id": "de_apfel", "item_tag": AdventureItem.TAG_COMIDA, "action": AdventureItem.ACTION_USAR, "source_character_slug": "bauer_elias", "order": 2, "lore": "Small, red, and bruised on one side. Elias gives it without ceremony."},
    {"slug": "wasser_aus_dem_brunnen", "emoji": "W", "name": "Wasser aus dem Brunnen", "word_id": "de_wasser", "item_tag": AdventureItem.TAG_BEBIDA, "action": AdventureItem.ACTION_USAR, "source_character_slug": None, "order": 3, "lore": "Cold well water with a clean mineral taste."},
    {"slug": "kupfermuenze", "emoji": "M", "name": "Kupfermuenze", "word_id": "de_muenze", "item_tag": AdventureItem.TAG_MONEDA, "action": AdventureItem.ACTION_ENTREGAR, "source_character_slug": "otto", "order": 4, "lore": "A small coin that has passed through many village hands."},
]

CHEST_POOL = [
    {"slug": "taschenmesser", "emoji": "K", "name": "Taschenmesser", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_ARMA, "lore": "A folding knife, useful for bread, rope, or sealed paper."},
    {"slug": "roggenbrot", "emoji": "B", "name": "Roggenbrot", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMIDA, "lore": "Dense rye bread that survives a long walk."},
    {"slug": "tonkrug", "emoji": "J", "name": "Tonkrug", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_BEBIDA, "lore": "A clay jug that keeps water cool."},
    {"slug": "verband", "emoji": "V", "name": "Sauberer Verband", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_REMEDIO, "lore": "Clean linen from Marta's shelf."},
    {"slug": "seil", "emoji": "R", "name": "Altes Seil", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Frayed, but strong enough."},
    {"slug": "zinnbecher", "emoji": "C", "name": "Zinnbecher", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Dented tin, polished where fingers hold it."},
    {"slug": "getrockneter_apfel", "emoji": "A", "name": "Getrockneter Apfel", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMIDA, "lore": "Sweet slices wrapped in paper."},
    {"slug": "hartkaese", "emoji": "Q", "name": "Hartkaese", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMIDA, "lore": "Salty cheese that keeps through travel."},
    {"slug": "nussbeutel", "emoji": "N", "name": "Nussbeutel", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMIDA, "lore": "A small cloth bag of walnuts."},
    {"slug": "wasserflasche", "emoji": "W", "name": "Wasserflasche", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_BEBIDA, "lore": "Enough water for one tense afternoon."},
    {"slug": "bitterer_tee", "emoji": "T", "name": "Bitterer Tee", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_BEBIDA, "lore": "Marta says it clears the head. Otto says it tastes like bark."},
    {"slug": "wachstuch", "emoji": "P", "name": "Wachstuch", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Keeps bread, paper, and bandages dry."},
    {"slug": "kurze_schnur", "emoji": "S", "name": "Kurze Schnur", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Too short for escape, useful for repair."},
    {"slug": "duenne_kerze", "emoji": "L", "name": "Duenne Kerze", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Burns fast, but reveals ink in dark corners."},
    {"slug": "nadel_und_faden", "emoji": "F", "name": "Nadel und Faden", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Greta says torn cloth tells too much if left open."},
    {"slug": "kreidestueck", "emoji": "C", "name": "Kreidestueck", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Marks stones, doors, and paths when memory fails."},
    {"slug": "kleine_muenze", "emoji": "M", "name": "Kleine Muenze", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_MONEDA, "lore": "Not much value, but sometimes enough to be polite."},
    {"slug": "befleckter_schein", "emoji": "D", "name": "Befleckter Schein", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "A stained paper with an official-looking mark."},
    {"slug": "holzloeffel", "emoji": "H", "name": "Holzloeffel", "rarity": AdventureItem.RARITY_COMUM, "tag": AdventureItem.TAG_COMUM, "lore": "Klara insists no traveler leaves hungry or empty-handed."},

    {"slug": "halbe_karte", "emoji": "P", "name": "Halbe Karte", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "Half a map of the northern road. The missing half matters."},
    {"slug": "silbermuenze", "emoji": "S", "name": "Silbermuenze", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_MONEDA, "lore": "Too heavy for a simple village trade."},
    {"slug": "messingkompass", "emoji": "N", "name": "Messingkompass", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "The needle insists on north."},
    {"slug": "versiegelter_brief", "emoji": "L", "name": "Versiegelter Brief", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "Red wax, old paper, no sender."},
    {"slug": "glaslinse", "emoji": "G", "name": "Glaslinse", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "Small letters become large; small lies sometimes do too."},
    {"slug": "schluessel_ohne_tuer", "emoji": "Y", "name": "Schluessel ohne Tuer", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "It opens something. Somewhere."},
    {"slug": "lederflasche", "emoji": "O", "name": "Lederflasche", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_BEBIDA, "lore": "Keeps water cooler than a clay cup."},
    {"slug": "knochenwuerfel", "emoji": "D", "name": "Knochenwuerfel", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "Otto refuses to gamble with it. That says enough."},
    {"slug": "silbersporn", "emoji": "R", "name": "Silbersporn", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "Only one spur. The other may have been lost in flight."},
    {"slug": "falkenfeder", "emoji": "E", "name": "Falkenfeder", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "Cut for writing. A bird from roads, not kitchens."},
    {"slug": "lampenoel", "emoji": "O", "name": "Lampenoel", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "Light for places the Vogt would prefer dark."},
    {"slug": "ledergurt", "emoji": "B", "name": "Ledergurt", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "Double stitching. Someone once hid a paper inside."},
    {"slug": "schmiedsrasiermesser", "emoji": "Z", "name": "Schmiedsrasiermesser", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_ARMA, "lore": "Friedrich dislikes it, but admits the edge is clean."},
    {"slug": "kaputter_rosenkranz", "emoji": "R", "name": "Kaputter Rosenkranz", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_COMUM, "lore": "One bead is missing."},
    {"slug": "nordzettel", "emoji": "Z", "name": "Nordzettel", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "A road name written in fading ink."},
    {"slug": "kraeuterbeutel", "emoji": "H", "name": "Kraeuterbeutel", "rarity": AdventureItem.RARITY_RARO, "tag": AdventureItem.TAG_REMEDIO, "lore": "Three pockets of dried herbs. Marta recognizes all of them."},

    {"slug": "kraeuterbuch", "emoji": "H", "name": "Kraeuterbuch", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "Marta's notes in a tight hand. One page is missing."},
    {"slug": "alter_ring", "emoji": "O", "name": "Alter Ring", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_COMUM, "lore": "Gold, thin, and engraved inside with a mark you nearly recognize."},
    {"slug": "zerbrochenes_medaillon", "emoji": "D", "name": "Zerbrochenes Medaillon", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_COMUM, "lore": "Half of a token. It was divided on purpose."},
    {"slug": "martas_kraut", "emoji": "H", "name": "Martas Kraut", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_REMEDIO, "lore": "Bitter leaves wrapped in dark cloth. They calm more than fever."},
    {"slug": "zeremoniendolch", "emoji": "K", "name": "Zeremoniendolch", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_ARMA, "lore": "Curved blade, old sign. More oath than weapon."},
    {"slug": "stehende_uhr", "emoji": "U", "name": "Stehende Uhr", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_COMUM, "lore": "Stopped at one exact hour."},
    {"slug": "volle_karte", "emoji": "V", "name": "Volle Karte", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "The northern road in full, with one place left unnamed."},
    {"slug": "dunkle_phiole", "emoji": "P", "name": "Dunkle Phiole", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_REMEDIO, "lore": "No label. Marta knows what it is and says nothing."},
    {"slug": "handspiegel", "emoji": "M", "name": "Handspiegel", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_COMUM, "lore": "For a second the face inside seems to remember more than you do."},
    {"slug": "knochenamulett", "emoji": "A", "name": "Knochenamulett", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_COMUM, "lore": "The Seekers gave these to people who went too far."},
    {"slug": "verbranntes_register", "emoji": "B", "name": "Verbranntes Register", "rarity": AdventureItem.RARITY_EPICO, "tag": AdventureItem.TAG_DOCUMENTO, "lore": "A book of names, burned exactly where the answer should be."},

    {"slug": "alter_goldgulden", "emoji": "G", "name": "Alter Goldgulden", "rarity": AdventureItem.RARITY_LENDARIO, "tag": AdventureItem.TAG_MONEDA, "lore": "Gold from a village that is no longer on any map."},
    {"slug": "schwarzer_schluessel", "emoji": "X", "name": "Schwarzer Schluessel", "rarity": AdventureItem.RARITY_LENDARIO, "tag": AdventureItem.TAG_COMUM, "lore": "Black iron. No rust. It waits for a final door."},
]

DEGRADED = [
    {"slug": "trockenes_brot", "emoji": "b", "name": "Trockenes Brot", "of": "frisches_brot", "lore": "Temporary fallback bread. It leaves when you master Brot."},
    {"slug": "schales_wasser", "emoji": "w", "name": "Schales Wasser", "of": "wasser_aus_dem_brunnen", "lore": "Water that helps, but does not satisfy."},
    {"slug": "weicher_apfel", "emoji": "a", "name": "Weicher Apfel", "of": "apfel_vom_feld", "lore": "Bruised fruit for a word still not stable."},
]

CHEST_PHASES = {
    2: AdventureItem.RARITY_COMUM,
    3: AdventureItem.RARITY_COMUM,
    6: AdventureItem.RARITY_COMUM,
    9: AdventureItem.RARITY_COMUM,
    11: AdventureItem.RARITY_COMUM,
    13: AdventureItem.RARITY_COMUM,
    17: AdventureItem.RARITY_COMUM,
    22: AdventureItem.RARITY_COMUM,
    7: AdventureItem.RARITY_RARO,
    12: AdventureItem.RARITY_RARO,
    16: AdventureItem.RARITY_RARO,
    20: AdventureItem.RARITY_RARO,
    8: AdventureItem.RARITY_EPICO,
    14: AdventureItem.RARITY_EPICO,
    19: AdventureItem.RARITY_EPICO,
}

BOSS_REWARDS = [
    {"slug": "siegel_des_dorfes", "emoji": "S", "name": "Siegel des Dorfes", "rarity": AdventureItem.RARITY_LENDARIO, "action": AdventureItem.ACTION_EXAMINAR, "item_tag": AdventureItem.TAG_DOCUMENTO, "word_id": "de_siegel", "order": 25, "lore": "The Vogt's seal in red wax. Proof that the village has no legal hold over you now."},
    {"slug": "brief_fragment_2", "emoji": "F", "name": "Brief Fragment 2", "rarity": AdventureItem.RARITY_LENDARIO, "action": AdventureItem.ACTION_EXAMINAR, "item_tag": AdventureItem.TAG_DOCUMENTO, "word_id": "de_bruder", "order": 26, "lore": "The second word on the old letter clears: BRUDER. You have a brother somewhere north."},
]
