# Generated by Django 5.0.6 on 2026-05-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_phase_type_characters_items_section_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField()),
                ('section_type', models.CharField(choices=[('narrativa', 'Narrativa'), ('revisao_srs', 'Revisão SRS'), ('pratica_aplicada', 'Prática Aplicada'), ('gramatica_narrativa', 'Gramática Narrativa'), ('reforco', 'Reforço'), ('obstaculo', 'Obstáculo')], max_length=25)),
                ('content', models.JSONField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='adventure.adventurephase')),
            ],
            options={
                'ordering': ['section_number'],
                'unique_together': {('phase', 'section_number')},
            },
        ),
    ]
