# Generated by Django 5.0.6 on 2026-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_add_phase_section_and_word_mastery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureitem',
            name='word_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
