# Generated by Django 5.0.6 on 2026-05-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_inventory_dynamics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventureitem',
            name='degrades_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degraded_versions', to='adventure.adventureitem'),
        ),
        migrations.AlterField(
            model_name='adventureitem',
            name='is_degraded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adventureitem',
            name='item_tag',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adventurephase',
            name='chest_tier',
            field=models.CharField(blank=True, choices=[('comum', 'Comum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário'), ('mitico', 'Mítico')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='adventurephase',
            name='has_chest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useritemqueue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useritemqueue',
            name='next_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useritemqueue',
            name='ordered_item_ids',
            field=models.JSONField(default=list),
        ),
    ]
