# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0007_alter_adventureitem_degrades_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdventureSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(choices=[("combate", "Combate"), ("sobrevivencia", "Sobrevivencia"), ("social", "Social"), ("investigacao", "Investigacao"), ("suporte", "Suporte")], default="suporte", max_length=20)),
                ("emoji", models.CharField(blank=True, default="", max_length=10)),
                ("base_power", models.PositiveSmallIntegerField(default=10)),
                ("order", models.PositiveIntegerField(default=1)),
                ("chapter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="adventure.adventurechapter")),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("chapter", "slug")},
            },
        ),
        migrations.AddField(
            model_name="adventureitem",
            name="skill",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="items", to="adventure.adventureskill"),
        ),
        migrations.CreateModel(
            name="UserSkillMastery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mastery_entries", to="adventure.adventureskill")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_mastery", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["skill__order"],
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.CreateModel(
            name="UserChest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chest_tier", models.CharField(choices=[("comum", "Comum"), ("raro", "Raro"), ("epico", "Ãƒâ€°pico"), ("lendario", "LendÃƒÂ¡rio"), ("mitico", "MÃƒÂ­tico")], max_length=10)),
                ("phase_score", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("stored", "Stored"), ("opening", "Opening"), ("ready", "Ready"), ("claimed", "Claimed"), ("discarded", "Discarded")], default="stored", max_length=12)),
                ("rolled_rarity", models.CharField(blank=True, choices=[("comum", "Comum"), ("raro", "Raro"), ("epico", "Ãƒâ€°pico"), ("lendario", "LendÃƒÂ¡rio")], default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("chapter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_chests", to="adventure.adventurechapter")),
                ("earned_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chest_drops", to="adventure.adventureitem")),
                ("phase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_chests", to="adventure.adventurephase")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="adventure_chests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["status", "unlock_at", "created_at"],
                "unique_together": {("user", "phase")},
            },
        ),
    ]
