# Generated by Django 5.0.6 on 2026-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_skills_and_user_chests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchest',
            name='chest_tier',
            field=models.CharField(choices=[('comum', 'Comum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário'), ('mitico', 'Mítico')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userchest',
            name='rolled_rarity',
            field=models.CharField(blank=True, choices=[('comum', 'Comum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário')], default='', max_length=10),
        ),
    ]
