import type { Strings } from "./types";

export const DE_DE: Strings = {
  app: {
    name: "Talkly",
    subtitle: "Sprachen lernen, indem du die Geschichte erlebst",
    loading: "Talkly wird geladen...",
  },
  actions: {
    back: "Zurueck",
    continue: "Weiter",
    start: "Starten",
    createArea: "Bereich erstellen",
    finish: "Abschliessen",
    retry: "Erneut versuchen",
    close: "Schliessen",
    save: "Speichern",
    cancel: "Abbrechen",
  },
  nav: {
    home: "Start",
    adventure: "Abenteuer",
    study: "Lernen",
    vocabulary: "Vokabeln",
    profile: "Profil",
  },
  states: {
    loadingStudy: "Lerneinheit wird geladen...",
    studyLoadError: "Lerneinheit konnte nicht geladen werden.",
    emptyReview: "Keine Wiederholung offen.",
  },
  home: {
    title: "Heute",
    headline: "Mach dort weiter, wo du aufgehoert hast.",
    adventureCta: "Abenteuer fortsetzen",
    studyCta: "Jetzt lernen",
    languagePath: (source, target, level) => `${source} zu ${target} - ${level}`,
    routine: (days, minutes) => `${days} - ${minutes} Min pro Sitzung`,
    studyToday: "Heute ist Lerntag",
    levelBadge: (lang, current, target) => `${lang} · ${current} → ${target}`,
    startDay: "Tag starten",
    continueAdventure: "Abenteuer fortsetzen",
    phrasesLabel: "Saetze",
    noRoutine: "Keine Routine festgelegt",
    nextSessionTitle: "Naechste Sitzung",
    nextSession: (date) => `Naechste Sitzung: ${date}`,
    adventurePosition: (series, seriesName, season, phase) =>
      `Serie ${series} · ${seriesName} · S${season} · Ph${phase}`,
    studyDaySubtitle: (lang, minutes) => `${lang} - ${minutes}`,
    noActiveArea: "Kein aktiver Bereich",
    noActiveAreaDetail: "Erstelle einen Lernbereich, um deinen Sprachplan zu starten.",
    statStreak: "Serie",
    statWords: "Woerter",
    statLevel: "Niveau",
    routineTitle: "Routine",
    noFixedSchedule: "Kein fester Plan: lerne wann du willst",
    allDays: "Jeden Tag",
    flexibleStudy: "Flexibles Lernen",
  },
  adventureSeries: {
    A1: "Mittelalterliches Dorf",
    A2: "Bundesliga",
    B1: "Berlin",
    B2: "Spione",
    C1: "Antike Ruinen",
  },
  weekdays: {
    short: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  },
  languages: {
    DE: "Deutsch",
    ES: "Spanisch",
    EN: "Englisch",
    IT: "Italienisch",
    FR: "Franzoesisch",
    JA: "Japanisch",
    PT: "Portugiesisch",
  },
  auth: {
    loginTab: "Anmelden",
    registerTab: "Konto erstellen",
    usernameLabel: "Benutzername",
    emailLabel: "Email",
    passwordLabel: "Passwort",
    confirmPasswordLabel: "Passwort bestaetigen",
    forgotPassword: "Passwort vergessen",
    orContinueWith: "oder weiter mit",
    continueWithGoogle: "Mit Google fortfahren",
    noAccountPrompt: "Kein Konto? ",
    hasAccountPrompt: "Schon ein Konto? ",
    usernameRequiredRegister: "Gib einen Benutzernamen ein.",
    emailRequired: "Gib eine Email ein.",
    passwordRulesIncomplete: "Erfuelle die Passwortregeln.",
    passwordsDoNotMatch: "Passwoerter stimmen nicht ueberein.",
    usernameRequiredLogin: "Gib deinen Benutzernamen ein.",
    passwordRequired: "Gib dein Passwort ein.",
    errorUsernameExists: "Dieser Benutzername existiert bereits.",
    errorInvalidCredentials: "Benutzername oder Passwort ist falsch.",
    errorPasswordUppercase: "Das Passwort braucht einen Grossbuchstaben.",
    errorPasswordLowercase: "Das Passwort braucht einen Kleinbuchstaben.",
    errorPasswordNumber: "Das Passwort braucht eine Zahl.",
    errorPasswordLength: "Das Passwort braucht mindestens 6 Zeichen.",
    errorEmailInvalid: "Gib eine gueltige Email ein.",
    errorBackendUnavailable: "Backend nicht erreichbar.",
    errorLoginFallback: "Anmeldung nicht moeglich.",
    errorRegisterFallback: "Konto konnte nicht erstellt werden.",
    passwordRuleLength: "Mindestens 6 Zeichen",
    passwordRuleUppercase: "Ein Grossbuchstabe",
    passwordRuleLowercase: "Ein Kleinbuchstabe",
    passwordRuleNumber: "Eine Zahl",
  },
  onboarding: {
    stepProgress: (step, total) => `Schritt ${step} von ${total}`,
    next: "Weiter",
    start: "Plan starten",
    configureCourseTitle: "Kurs einrichten",
    configureCourseSubtitle: "Waehle Sprachen und Startpunkt",
    sourceLanguageDetailPt: "Erklaerungen auf Portugiesisch",
    loadingLanguages: "Sprachen werden geladen...",
    routineTitle: "Routine erstellen",
    routineSubtitle: "Du kannst jeden Tag lernen - wir erinnern dich an diesen Tagen",
    youSpeak: "Du sprichst...",
    youLearn: "Du willst lernen...",
    levelLabel: "Startniveau",
    levelIniciante: "Anfaenger",
    levelA1Detail: "Ich starte bei null",
    daysLabel: "Lerntage",
    durationLabel: "Sitzungsdauer",
    chooseDayError: "Waehle mindestens einen Tag",
    estimateSentence: (months) => `In deinem Tempo erreichst du A1 in etwa ${months} ${months === 1 ? "Monat" : "Monaten"}`,
    estimatePace: (days, duration) => `${days}x pro Woche - ${duration} pro Sitzung`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 Stunde",
    minutesShort: (minutes) => `${minutes} Min`,
    flagAlt: (code) => `${code} Flagge`,
  },
  adventure: {
    title: "Abenteuer",
    mapTitle: "Karte",
    loading: "Abenteuer wird geladen...",
    empty: "Kein Abenteuer verfuegbar.",
    phaseLabel: (n) => `Phase ${n}`,
    sectionProgress: (done, total) => `${done}/${total} Abschnitte`,
    backToMap: "Zur Karte",
    languageBridge: "Sprachbruecke",
    narrativeOrder: "Erzaehlreihenfolge",
    yes: "Ja",
    no: "Nein",
    met: "getroffen",
    undiscovered: "unentdeckt",
  },
  today: {
    tabSession: "Gefuehrte Einheit",
    tabModules: "Module",
  },
  study: {
    title: "Gefuehrtes Lernen",
    headline: "Uebe, was das Abenteuer gerade braucht.",
    pendingReviews: (count) => `${count} Wiederholungen offen`,
    nextPhase: "Naechste Phase",
    startAdventureTitle: "Starte dein Abenteuer",
    adventureMap: "Abenteuerkarte",
    continueAdventureHint: "Die aktuelle Phase bestimmt den Wortschatz im Lernen.",
    continueAdventureBtn: "Abenteuer fortsetzen",
    studyNowBtn: "Jetzt lernen",
    currentLesson: "Aktuelle Lektion",
    lessonFallback: "Gefuehrte Lektion",
    moduleLessons: (count) => `${count} Lektionen`,
    phrasesCount: (count) => `${count} Saetze`,
    studyPhrasesBtn: (count) => `${count} Saetze lernen`,
    noWordsDetail: "Oeffne das Abenteuer oder aktualisiere den Seed, um Saetze fuer diese Lektion freizuschalten.",
    reviewNowTitle: "Verteilte Wiederholung",
    reviewNowSubtitle: "Festige die Woerter, die im SRS faellig sind.",
    reviewNowWords: (count) => `${count} Woerter zum Wiederholen`,
    reviewBtn: "Jetzt wiederholen",
    pathEyebrow: "Lernpfad",
    pathTitle: "Seed-Module",
    pathDetail: "Lektionen folgen der Abenteuerphase und nutzen registrierte Inhalte.",
    moduleLabel: (order) => `Modul ${order}`,
    phaseLabel: (phase) => `Phase ${phase}`,
    unlocked: "Offen",
    locked: "Gesperrt",
    completed: "Abgeschlossen",
    current: "Aktuell",
    sessionComplete: "Wiederholung abgeschlossen",
    sessionScore: (correct, mistakes) => `${correct} richtig - ${mistakes} Fehler`,
    answer: "Antworten",
    exit: "Beenden",
  },
  admin: {
    app: {
      title: "Admin",
      subtitle: "Backoffice",
      panel: "Adminbereich",
      loading: "Daten werden geladen...",
      empty: "Keine Daten geladen.",
      search: "Suchen",
      refresh: "Daten aktualisieren",
      logout: "Abmelden",
      apiStatus: "Django API",
      apiStatusDetail: "Geschuetzte Admin-Endpunkte werden verwendet.",
    },
    auth: {
      description: "Melde dich mit einem Staff- oder Superuser-Konto an, um Inhalte, Benutzer und Bereiche zu verwalten.",
      username: "Benutzername",
      password: "Passwort",
      submit: "Anmelden",
      submitting: "Anmeldung...",
      error: "Anmeldung nicht moeglich.",
      forbidden: "Benutzer hat keine Admin-Berechtigung.",
      loadError: "Daten konnten nicht geladen werden.",
    },
    groups: {
      operation: "Betrieb",
      content: "Inhalt",
      strategy: "Strategie",
      system: "System",
    },
    shared: {
      fields: {
        id: "ID",
        name: "Name",
        title: "Titel",
        status: "Status",
        created: "Erstellt",
        user: "Benutzer",
        email: "Email",
        language: "Sprache",
        level: "Niveau",
        type: "Typ",
        total: "Gesamt",
        description: "Beschreibung",
      },
      status: {
        active: "Aktiv",
        inactive: "Inaktiv",
        yes: "Ja",
        no: "Nein",
        staff: "Staff",
        student: "Lerner",
        connected: "Verbunden",
        planned: "Geplant",
      },
    },
    apps: {
      dashboard: { title: "Dashboard", description: "Produktuebersicht" },
      users: { title: "Benutzer", description: "Konten, Zugriff und Aktivitaet" },
      goals: { title: "Bereiche", description: "Kurse und Routinen der Benutzer" },
      content: { title: "Katalog", description: "Sprachen, Szenarien und Saetze" },
      learning: { title: "Lernen", description: "Module, Lektionen und Study Days" },
      adventure: { title: "Abenteuer", description: "Kapitel, Phasen, Figuren und Gegenstaende" },
      progress: { title: "Fortschritt", description: "Abschluesse, SRS, Favoriten und Meisterung" },
      businessPlan: { title: "Geschaeftsmodell", description: "Szenarien, Annahmen, Runway und Validierung" },
      system: { title: "Django Apps", description: "Domain- und Endpunktkarte" },
    },
    businessPlan: {
      scenario: "Szenario",
      assumptions: "Annahmen",
      validation: "Validierung",
      pessimistic: "Pessimistisch",
      realistic: "Realistisch",
      optimistic: "Optimistisch",
      monthlyPrice: "Monatspreis",
      activeUsers: "Aktive Benutzer",
      payingUsers: "Zahlende Benutzer",
      mrr: "MRR",
      costs: "Kosten",
      runway: "Runway",
      risk: "Risiko",
    },
  },
  errors: {
    generic: "Die Aktion konnte nicht abgeschlossen werden.",
  },
};
