import type { Strings } from "./types";

export const DE_DE: Strings = {
  app: {
    name: "Talkly",
    subtitle: "Sprachen lernen, indem du die Geschichte erlebst",
    loading: "Talkly wird geladen...",
  },
  actions: {
    back: "Zurueck",
    continue: "Weiter",
    start: "Starten",
    finish: "Abschliessen",
    retry: "Erneut versuchen",
    close: "Schliessen",
    save: "Speichern",
    cancel: "Abbrechen",
  },
  nav: {
    home: "Start",
    adventure: "Abenteuer",
    study: "Lernen",
    vocabulary: "Vokabeln",
    profile: "Profil",
  },
  home: {
    title: "Heute",
    headline: "Mach dort weiter, wo du aufgehoert hast.",
    adventureCta: "Abenteuer fortsetzen",
    studyCta: "Jetzt lernen",
  },
  weekdays: {
    short: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  },
  languages: {
    DE: "Deutsch",
    ES: "Spanisch",
    EN: "Englisch",
    IT: "Italienisch",
    FR: "Franzoesisch",
    JA: "Japanisch",
    PT: "Portugiesisch",
  },
  auth: {
    loginTab: "Anmelden",
    registerTab: "Konto erstellen",
    usernameLabel: "Benutzername",
    emailLabel: "Email",
    passwordLabel: "Passwort",
    confirmPasswordLabel: "Passwort bestaetigen",
    forgotPassword: "Passwort vergessen",
    orContinueWith: "oder weiter mit",
    continueWithGoogle: "Mit Google fortfahren",
    noAccountPrompt: "Kein Konto? ",
    hasAccountPrompt: "Schon ein Konto? ",
    usernameRequiredRegister: "Gib einen Benutzernamen ein.",
    emailRequired: "Gib eine Email ein.",
    passwordRulesIncomplete: "Erfuelle die Passwortregeln.",
    passwordsDoNotMatch: "Passwoerter stimmen nicht ueberein.",
    usernameRequiredLogin: "Gib deinen Benutzernamen ein.",
    passwordRequired: "Gib dein Passwort ein.",
    errorUsernameExists: "Dieser Benutzername existiert bereits.",
    errorInvalidCredentials: "Benutzername oder Passwort ist falsch.",
    errorPasswordUppercase: "Das Passwort braucht einen Grossbuchstaben.",
    errorPasswordLowercase: "Das Passwort braucht einen Kleinbuchstaben.",
    errorPasswordNumber: "Das Passwort braucht eine Zahl.",
    errorPasswordLength: "Das Passwort braucht mindestens 6 Zeichen.",
    errorEmailInvalid: "Gib eine gueltige Email ein.",
    errorBackendUnavailable: "Backend nicht erreichbar.",
    errorLoginFallback: "Anmeldung nicht moeglich.",
    errorRegisterFallback: "Konto konnte nicht erstellt werden.",
    passwordRuleLength: "Mindestens 6 Zeichen",
    passwordRuleUppercase: "Ein Grossbuchstabe",
    passwordRuleLowercase: "Ein Kleinbuchstabe",
    passwordRuleNumber: "Eine Zahl",
  },
  onboarding: {
    stepProgress: (step, total) => `Schritt ${step} von ${total}`,
    next: "Weiter",
    start: "Plan starten",
    configureCourseTitle: "Kurs einrichten",
    configureCourseSubtitle: "Waehle Sprachen und Startpunkt",
    sourceLanguageDetailPt: "Erklaerungen auf Portugiesisch",
    loadingLanguages: "Sprachen werden geladen...",
    routineTitle: "Routine erstellen",
    routineSubtitle: "Du kannst jeden Tag lernen - wir erinnern dich an diesen Tagen",
    youSpeak: "Du sprichst...",
    youLearn: "Du willst lernen...",
    levelLabel: "Startniveau",
    levelIniciante: "Anfaenger",
    levelA1Detail: "Ich starte bei null",
    daysLabel: "Lerntage",
    durationLabel: "Sitzungsdauer",
    chooseDayError: "Waehle mindestens einen Tag",
    estimateSentence: (months) => `In deinem Tempo erreichst du A1 in etwa ${months} ${months === 1 ? "Monat" : "Monaten"}`,
    estimatePace: (days, duration) => `${days}x pro Woche - ${duration} pro Sitzung`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 Stunde",
    minutesShort: (minutes) => `${minutes} Min`,
    flagAlt: (code) => `${code} Flagge`,
  },
  adventure: {
    title: "Abenteuer",
    mapTitle: "Karte",
    loading: "Abenteuer wird geladen...",
    empty: "Kein Abenteuer verfuegbar.",
    phaseLabel: (n) => `Phase ${n}`,
    sectionProgress: (done, total) => `${done}/${total} Abschnitte`,
    backToMap: "Zur Karte",
    languageBridge: "Sprachbruecke",
    narrativeOrder: "Erzaehlreihenfolge",
    yes: "Ja",
    no: "Nein",
    met: "getroffen",
    undiscovered: "unentdeckt",
  },
  errors: {
    generic: "Die Aktion konnte nicht abgeschlossen werden.",
  },
};
