import type { Strings } from "./types";

export const EN: Strings = {
  app: {
    name: "Talkly",
    subtitle: "Learn languages by living the story",
    loading: "Loading Talkly...",
  },
  actions: {
    back: "Back",
    continue: "Continue",
    start: "Start",
    finish: "Finish",
    retry: "Try again",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
  },
  nav: {
    home: "Home",
    adventure: "Adventure",
    study: "Study",
    vocabulary: "Vocabulary",
    profile: "Profile",
  },
  home: {
    title: "Today",
    headline: "Continue where you left off.",
    adventureCta: "Continue adventure",
    studyCta: "Study now",
  },
  weekdays: {
    short: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  },
  languages: {
    DE: "German",
    ES: "Spanish",
    EN: "English",
    IT: "Italian",
    FR: "French",
    JA: "Japanese",
    PT: "Portuguese",
  },
  auth: {
    loginTab: "Sign in",
    registerTab: "Create account",
    usernameLabel: "Username",
    emailLabel: "Email",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    forgotPassword: "Forgot password",
    orContinueWith: "or continue with",
    continueWithGoogle: "Continue with Google",
    noAccountPrompt: "No account? ",
    hasAccountPrompt: "Already have an account? ",
    usernameRequiredRegister: "Enter a username.",
    emailRequired: "Enter an email.",
    passwordRulesIncomplete: "Complete the password requirements.",
    passwordsDoNotMatch: "Passwords do not match.",
    usernameRequiredLogin: "Enter your username.",
    passwordRequired: "Enter your password.",
    errorUsernameExists: "That username already exists.",
    errorInvalidCredentials: "Invalid username or password.",
    errorPasswordUppercase: "Password needs an uppercase letter.",
    errorPasswordLowercase: "Password needs a lowercase letter.",
    errorPasswordNumber: "Password needs a number.",
    errorPasswordLength: "Password needs at least 6 characters.",
    errorEmailInvalid: "Enter a valid email.",
    errorBackendUnavailable: "Could not reach the backend.",
    errorLoginFallback: "Could not sign in.",
    errorRegisterFallback: "Could not create the account.",
    passwordRuleLength: "At least 6 characters",
    passwordRuleUppercase: "One uppercase letter",
    passwordRuleLowercase: "One lowercase letter",
    passwordRuleNumber: "One number",
  },
  onboarding: {
    stepProgress: (step, total) => `Step ${step} of ${total}`,
    next: "Next",
    start: "Start my plan",
    configureCourseTitle: "Configure your course",
    configureCourseSubtitle: "Choose languages and your starting point",
    sourceLanguageDetailPt: "Explanations in Portuguese",
    loadingLanguages: "Loading languages...",
    routineTitle: "Create your routine",
    routineSubtitle: "You can study any day - these are your reminders",
    youSpeak: "You speak...",
    youLearn: "You want to learn...",
    levelLabel: "Starting level",
    levelIniciante: "Beginner",
    levelA1Detail: "I am starting from zero",
    daysLabel: "Study days",
    durationLabel: "Session length",
    chooseDayError: "Choose at least one day",
    estimateSentence: (months) => `At your pace, you reach A1 in about ${months} ${months === 1 ? "month" : "months"}`,
    estimatePace: (days, duration) => `${days}x per week - ${duration} per session`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 hour",
    minutesShort: (minutes) => `${minutes} min`,
    flagAlt: (code) => `${code} flag`,
  },
  adventure: {
    title: "Adventure",
    mapTitle: "Map",
    loading: "Loading adventure...",
    empty: "No adventure available.",
    phaseLabel: (n) => `Phase ${n}`,
    sectionProgress: (done, total) => `${done}/${total} sections`,
    backToMap: "Back to map",
    languageBridge: "Language bridge",
    narrativeOrder: "Narrative order",
    yes: "Yes",
    no: "No",
    met: "met",
    undiscovered: "undiscovered",
  },
  errors: {
    generic: "Could not complete the action.",
  },
};
