import type { Strings } from "./types";

export const EN: Strings = {
  app: {
    name: "Talkly",
    subtitle: "Learn languages by living the story",
    loading: "Loading Talkly...",
  },
  actions: {
    back: "Back",
    continue: "Continue",
    start: "Start",
    createArea: "Create area",
    finish: "Finish",
    retry: "Try again",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
  },
  nav: {
    home: "Home",
    adventure: "Adventure",
    study: "Study",
    vocabulary: "Vocabulary",
    profile: "Profile",
  },
  states: {
    loadingStudy: "Loading study...",
    studyLoadError: "Could not load study.",
    emptyReview: "No review pending.",
  },
  vocabulary: {
    eyebrow: "Vocabulary",
    title: "Saved phrases",
    subtitle: "Review what you marked as important.",
    filterAll: "All",
    savedCount: (count) => `${count} saved`,
    scenarioCount: (count) => `${count} scenarios`,
    categoryCount: (count) => `${count} categories`,
    loading: "Loading vocabulary...",
    loadError: "Could not load vocabulary.",
    emptyTitle: "No saved phrases yet.",
    emptyDetail: "Save phrases during lessons and adventures to review them here later.",
    filterEmpty: "No phrases found for this filter.",
    remove: "Remove",
    scenarioFallback: "No scenario",
    categoryFallback: "General",
    difficultyLabel: "Difficulty",
  },
  history: {
    title: "History",
    subtitle: "Track your study days and completed sessions.",
    unavailableTitle: "History unavailable",
    unavailableDetail: "Could not load your history right now.",
    loading: "Loading history...",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    bestStreak: "Streak",
    days: "Days",
    sessions: "Sessions",
    areas: "Areas",
    all: "All",
    byArea: "By area",
    completed: "Completed",
    planned: "Planned",
    open: "Open",
    active: "Active",
    noHistoryTitle: "No history this month.",
    noHistoryDetail: "Complete study sessions to fill this calendar.",
  },
  home: {
    title: "Today",
    headline: "Continue where you left off.",
    adventureCta: "Continue adventure",
    studyCta: "Study now",
    languagePath: (source, target, level) => `${source} to ${target} - ${level}`,
    routine: (days, minutes) => `${days} - ${minutes} min per session`,
    studyToday: "Today is a study day",
    levelBadge: (lang, current, target) => `${lang} · ${current} → ${target}`,
    startDay: "Start the day",
    continueAdventure: "Continue Adventure",
    phrasesLabel: "phrases",
    noRoutine: "No routine set",
    nextSessionTitle: "Next session",
    nextSession: (date) => `Next session: ${date}`,
    adventurePosition: (series, seriesName, season, phase) =>
      `Series ${series} · ${seriesName} · S${season} · Ph${phase}`,
    studyDaySubtitle: (lang, minutes) => `${lang} - ${minutes}`,
    noActiveArea: "No active area",
    noActiveAreaDetail: "Create a study area to start your language plan.",
    statStreak: "Streak",
    statWords: "Words",
    statLevel: "Level",
    routineTitle: "Routine",
    noFixedSchedule: "No fixed schedule: study whenever you want",
    allDays: "Every day",
    flexibleStudy: "Flexible study",
  },
  adventureSeries: {
    A1: "Medieval Village",
    A2: "Bundesliga",
    B1: "Berlin",
    B2: "Spies",
    C1: "Ancient Ruins",
  },
  weekdays: {
    short: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  },
  languages: {
    DE: "German",
    ES: "Spanish",
    EN: "English",
    IT: "Italian",
    FR: "French",
    JA: "Japanese",
    PT: "Portuguese",
  },
  auth: {
    loginTab: "Sign in",
    registerTab: "Create account",
    usernameLabel: "Username",
    emailLabel: "Email",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    forgotPassword: "Forgot password",
    orContinueWith: "or continue with",
    continueWithGoogle: "Continue with Google",
    noAccountPrompt: "No account? ",
    hasAccountPrompt: "Already have an account? ",
    usernameRequiredRegister: "Enter a username.",
    emailRequired: "Enter an email.",
    passwordRulesIncomplete: "Complete the password requirements.",
    passwordsDoNotMatch: "Passwords do not match.",
    usernameRequiredLogin: "Enter your username.",
    passwordRequired: "Enter your password.",
    errorUsernameExists: "That username already exists.",
    errorInvalidCredentials: "Invalid username or password.",
    errorPasswordUppercase: "Password needs an uppercase letter.",
    errorPasswordLowercase: "Password needs a lowercase letter.",
    errorPasswordNumber: "Password needs a number.",
    errorPasswordLength: "Password needs at least 6 characters.",
    errorEmailInvalid: "Enter a valid email.",
    errorBackendUnavailable: "Could not reach the backend.",
    errorLoginFallback: "Could not sign in.",
    errorRegisterFallback: "Could not create the account.",
    passwordRuleLength: "At least 6 characters",
    passwordRuleUppercase: "One uppercase letter",
    passwordRuleLowercase: "One lowercase letter",
    passwordRuleNumber: "One number",
  },
  onboarding: {
    stepProgress: (step, total) => `Step ${step} of ${total}`,
    next: "Next",
    start: "Start my plan",
    configureCourseTitle: "Configure your course",
    configureCourseSubtitle: "Choose languages and your starting point",
    sourceLanguageDetailPt: "Explanations in Portuguese",
    loadingLanguages: "Loading languages...",
    routineTitle: "Create your routine",
    routineSubtitle: "You can study any day - these are your reminders",
    youSpeak: "You speak...",
    youLearn: "You want to learn...",
    levelLabel: "Starting level",
    levelIniciante: "Beginner",
    levelA1Detail: "I am starting from zero",
    daysLabel: "Study days",
    durationLabel: "Session length",
    chooseDayError: "Choose at least one day",
    estimateSentence: (months) => `At your pace, you reach A1 in about ${months} ${months === 1 ? "month" : "months"}`,
    estimatePace: (days, duration) => `${days}x per week - ${duration} per session`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 hour",
    minutesShort: (minutes) => `${minutes} min`,
    flagAlt: (code) => `${code} flag`,
  },
  profile: {
    noEmail: "No email registered",
    memberLabel: "Fluenci Account",
    activeCourse: "Active course",
    otherAreas: "Other areas",
    addArea: "Add study area",
    addAreaDetail: "Spanish, French and more",
    accountSection: "Account",
    changePassword: "Change password",
    signOut: "Sign out",
    deleteAreaTitle: "Delete area?",
    deleteAreaBody: (name) => `${name} will be removed from your profile. This action cannot be undone.`,
    cancelAction: "Cancel",
    planLabel: "Plan",
    planName: "Free",
    planDetail: "Basic access",
    weekActivity: "This week",
    viewHistory: "View full history",
    editRoutine: "Edit",
    editRoutineTitle: "Edit routine",
    saveRoutine: "Save routine",
    chooseDayError: "Choose at least one day",
    casualStudy: "Flexible study",
    allDays: "Every day",
    loading: "Loading profile...",
    unavailable: "Profile unavailable.",
    addAreaTitle: "Add area",
    learnTarget: "You want to learn",
    studyDays: "Study days",
    duration: "Duration",
    saving: "Saving...",
    close: "Close",
    upgrade: "Upgrade",
    useArea: "Use",
    progressComplete: (pct) => `${pct}% complete`,
  },
  adventure: {
    title: "Adventure",
    hubTitle: "Enter the adventure",
    hubSubtitle: "Choose whether to open the map, check your backpack or see what you have unlocked.",
    openMap: "Open map",
    collectionTitle: "Adventure collection",
    inventory: "Backpack",
    chests: "Chests",
    words: "Words",
    hero: "Hero",
    characters: "Characters",
    inventoryEyebrow: "Inventory",
    inventorySubtitle: "Items you earned in the story appear here.",
    chestsEyebrow: "Rewards",
    chestsSubtitle: "Stored, opening or ready-to-claim chests.",
    wordsEyebrow: "Vocabulary",
    wordsSubtitle: "Words unlocked by the adventure.",
    heroEyebrow: "Progress",
    heroSubtitle: "Level, XP, streak and journey attributes.",
    charactersEyebrow: "Cast",
    charactersSubtitle: "Allies, NPCs and important figures you have met.",
    collectionLoadError: "Could not load this adventure area.",
    inventoryEmpty: "Your backpack is empty. Complete phases to collect items.",
    chestsEmpty: "Complete phases with chests to store rewards here.",
    wordsEmpty: "Complete the first section to see words here.",
    heroEmpty: "Hero data is unavailable.",
    charactersEmpty: "Characters will appear as you advance.",
    used: "used",
    available: "available",
    ready: "ready",
    chestTitle: (tier) => `Chest ${tier}`,
    phaseScore: (phase, score) => `Phase ${phase} - score ${score}`,
    heroLevel: "Level",
    heroXp: "XP",
    heroPhases: "Phases",
    heroStreak: "Streak",
    heroVocabulary: "Vocabulary",
    heroGrammar: "Grammar",
    heroFluency: "Fluency",
    mapTitle: "Map",
    bossLabel: "Boss",
    reviewLabel: "Review",
    currentLabel: "Current",
    lockedLabel: "Locked",
    completedLabel: "Completed",
    dayShort: "Day",
    phaseStart: "Start phase",
    phaseStartReview: "Review phase",
    phaseStartBoss: "Face boss",
    sectionLabel: (done, total) => `Section ${done}/${total}`,
    phasesCompleted: (done, total) => `${done}/${total} phases completed`,
    keyWords: "Key words",
    phaseType: "Type",
    npc: "NPC",
    loading: "Loading adventure...",
    empty: "No adventure available.",
    phaseLabel: (n) => `Phase ${n}`,
    sectionProgress: (done, total) => `${done}/${total} sections`,
    backToMap: "Back to map",
    languageBridge: "Language bridge",
    narrativeOrder: "Narrative order",
    yes: "Yes",
    no: "No",
    met: "met",
    undiscovered: "undiscovered",
    details: "Details",
    itemAction: "Action",
    itemSource: "Source",
    itemEarnedAt: "Earned on",
    useItem: "Use item",
    itemAlreadyUsed: "Item already used",
    chestStatus: "Status",
    chestReward: "Reward",
    chestEmptyReward: "Reward not revealed yet",
    startChest: "Open chest",
    claimChest: "Claim chest",
    chestAlreadyClaimed: "Chest already claimed",
    chestsStoredMetric: "Stored",
    chestsOpeningMetric: "Opening",
    chestsReadyMetric: "Ready",
    chestsSlotsTitle: "Opening slots",
    chestsStoredTitle: "Stored chests",
    chestSlotEmpty: "Empty slot",
    chestsSlotsFull: "Slots full",
    chestReadyToClaim: "Ready to claim",
    chestStoredForLater: "Stored to open later",
    actionError: "Could not complete the action.",
    wordTier: "Tier",
    wordNative: "Translation",
    answer: "Answer",
    phaseLoading: "Loading phase...",
    phaseEmptySections: "Phase has no sections.",
    recapTitle: "Where we left off",
    answerCorrect: (correct) => `Correct: ${correct}`,
    completeSection: "Section complete",
    correctCount: (count) => `${count} correct`,
    mistakesCount: (count) => `${count} mistakes`,
    finish: "Finish",
    phaseCompleted: "Phase complete",
    practicedWords: "Practiced words",
    earnedItem: "Earned item",
  },
  today: {
    tabSession: "Guided session",
    tabModules: "Modules",
  },
  study: {
    title: "Guided study",
    headline: "Train what the adventure needs right now.",
    pendingReviews: (count) => `${count} reviews pending`,
    nextPhase: "Next phase",
    startAdventureTitle: "Start your adventure",
    adventureMap: "Adventure map",
    continueAdventureHint: "The current phase defines the vocabulary shown in study.",
    continueAdventureBtn: "Continue adventure",
    studyNowBtn: "Study now",
    currentLesson: "Current lesson",
    lessonFallback: "Guided lesson",
    moduleLessons: (count) => `${count} lessons`,
    phrasesCount: (count) => `${count} phrases`,
    studyPhrasesBtn: (count) => `Study ${count} phrases`,
    noWordsDetail: "Open the adventure or refresh the seed to unlock phrases for this lesson.",
    reviewNowTitle: "Spaced review",
    reviewNowSubtitle: "Reinforce the words that are due in SRS.",
    reviewNowWords: (count) => `${count} words to review`,
    reviewBtn: "Review now",
    pathEyebrow: "Study path",
    pathTitle: "Seed modules",
    pathDetail: "Lessons follow the adventure phase and reuse registered content.",
    moduleLabel: (order) => `Module ${order}`,
    phaseLabel: (phase) => `Phase ${phase}`,
    unlocked: "Unlocked",
    locked: "Locked",
    completed: "Completed",
    current: "Current",
    sessionComplete: "Review complete",
    sessionScore: (correct, mistakes) => `${correct} correct - ${mistakes} mistakes`,
    answer: "Answer",
    exit: "Exit",
    lessonSessionTitle: "Guided session",
    phraseProgress: (current, total) => `Phrase ${current} of ${total}`,
    showTranslation: "Show translation",
    nextPhrase: "Next phrase",
    finishLesson: "Finish lesson",
    sourcePhrase: "Base",
    targetPhrase: "Answer",
  },
  admin: {
    app: {
      title: "Admin",
      subtitle: "Backoffice",
      panel: "Admin panel",
      loading: "Loading data...",
      empty: "No data loaded.",
      search: "Search",
      refresh: "Refresh data",
      logout: "Sign out",
      apiStatus: "Django API",
      apiStatusDetail: "Using protected admin endpoints.",
    },
    auth: {
      description: "Sign in with a staff or superuser account to manage content, users and areas.",
      username: "Username",
      password: "Password",
      submit: "Sign in",
      submitting: "Signing in...",
      error: "Could not sign in.",
      forbidden: "User has no admin permission.",
      loadError: "Could not load data.",
    },
    groups: {
      operation: "Operation",
      content: "Content",
      strategy: "Strategy",
      system: "System",
    },
    shared: {
      fields: {
        id: "ID",
        name: "Name",
        title: "Title",
        status: "Status",
        created: "Created",
        user: "User",
        email: "Email",
        language: "Language",
        level: "Level",
        type: "Type",
        total: "Total",
        description: "Description",
      },
      status: {
        active: "Active",
        inactive: "Inactive",
        yes: "Yes",
        no: "No",
        staff: "Staff",
        student: "Student",
        connected: "Connected",
        planned: "Planned",
      },
    },
    apps: {
      dashboard: { title: "Dashboard", description: "Product overview" },
      users: { title: "Users", description: "Accounts, access and activity" },
      goals: { title: "Areas", description: "User courses and routines" },
      content: { title: "Catalog", description: "Languages, scenarios and phrases" },
      learning: { title: "Study", description: "Modules, lessons and study days" },
      adventure: { title: "Adventure", description: "Chapters, phases, characters and items" },
      progress: { title: "Progress", description: "Completions, SRS, favorites and mastery" },
      businessPlan: { title: "Business model", description: "Scenarios, assumptions, runway and validation" },
      system: { title: "Django apps", description: "Domain and endpoint map" },
    },
    businessPlan: {
      scenario: "Scenario",
      assumptions: "Assumptions",
      validation: "Validation",
      pessimistic: "Pessimistic",
      realistic: "Realistic",
      optimistic: "Optimistic",
      monthlyPrice: "Monthly price",
      activeUsers: "Active users",
      payingUsers: "Paying users",
      mrr: "MRR",
      costs: "Costs",
      runway: "Runway",
      risk: "Risk",
    },
  },
  errors: {
    generic: "Could not complete the action.",
  },
};
