export const PT_BR = {
  app: {
    name: "Talkly",
    subtitle: "Aprenda idiomas vivendo a historia",
    loading: "Carregando Talkly...",
  },
  actions: {
    back: "Voltar",
    continue: "Continuar",
    start: "Comecar",
    createArea: "Criar area",
    finish: "Concluir",
    retry: "Tentar novamente",
    close: "Fechar",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
  },
  nav: {
    home: "Home",
    adventure: "Aventura",
    study: "Estudo",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  states: {
    loadingStudy: "Carregando estudo...",
    studyLoadError: "Nao foi possivel carregar o estudo.",
    emptyReview: "Nenhuma revisao pendente.",
  },
  vocabulary: {
    eyebrow: "Vocabulario",
    title: "Frases salvas",
    subtitle: "Revise o que voce marcou como importante.",
    filterAll: "Tudo",
    savedCount: (count: number) => `${count} salvas`,
    scenarioCount: (count: number) => `${count} cenarios`,
    categoryCount: (count: number) => `${count} categorias`,
    loading: "Carregando vocabulario...",
    loadError: "Nao foi possivel carregar o vocabulario.",
    emptyTitle: "Nenhuma frase salva ainda.",
    emptyDetail: "Marque frases durante as licoes e aventuras para revisar aqui depois.",
    filterEmpty: "Nenhuma frase encontrada nesse filtro.",
    remove: "Remover",
    scenarioFallback: "Sem cenario",
    categoryFallback: "Geral",
    difficultyLabel: "Dificuldade",
  },
  history: {
    title: "Historico",
    subtitle: "Acompanhe seus dias de estudo e sessoes concluidas.",
    unavailableTitle: "Historico indisponivel",
    unavailableDetail: "Nao foi possivel carregar seu historico agora.",
    loading: "Carregando historico...",
    previousMonth: "Mes anterior",
    nextMonth: "Proximo mes",
    bestStreak: "Sequencia",
    days: "Dias",
    sessions: "Sessoes",
    areas: "Areas",
    all: "Todos",
    byArea: "Por area",
    completed: "Concluido",
    planned: "Planejado",
    open: "Livre",
    active: "Ativa",
    noHistoryTitle: "Sem historico neste mes.",
    noHistoryDetail: "Conclua sessoes de estudo para preencher este calendario.",
  },
  home: {
    title: "Hoje",
    headline: "Continue de onde parou.",
    adventureCta: "Continuar aventura",
    studyCta: "Estudar agora",
    languagePath: (source: string, target: string, level: string) => `${source} para ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min por sessao`,
    studyToday: "Hoje e dia de estudo",
    levelBadge: (lang: string, current: string, target: string) => `${lang} · ${current} → ${target}`,
    startDay: "Comecar o dia",
    continueAdventure: "Continuar Aventura",
    phrasesLabel: "frases",
    noRoutine: "Sem rotina definida",
    nextSessionTitle: "Proxima sessao",
    nextSession: (date: string) => `Proxima sessao: ${date}`,
    adventurePosition: (series: string, seriesName: string, season: number, phase: number) =>
      `Serie ${series} · ${seriesName} · T${season} · F${phase}`,
    studyDaySubtitle: (lang: string, minutes: string) => `${lang} - ${minutes}`,
    noActiveArea: "Nenhuma area ativa",
    noActiveAreaDetail: "Crie uma area de estudo para comecar seu plano de idiomas.",
    statStreak: "Sequencia",
    statWords: "Palavras",
    statLevel: "Nivel",
    routineTitle: "Rotina",
    noFixedSchedule: "Sem agenda fixa: estude quando quiser",
    allDays: "Todo dia",
    flexibleStudy: "Estudo avulso",
  },
  adventureSeries: {
    A1: "Vila Medieval",
    A2: "Bundesliga",
    B1: "Berlim",
    B2: "Espioes",
    C1: "Ruinas Antigas",
  },
  weekdays: {
    short: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"] as readonly string[],
  },
  languages: {
    DE: "Alemao",
    ES: "Espanhol",
    EN: "Ingles",
    IT: "Italiano",
    FR: "Frances",
    JA: "Japones",
    PT: "Portugues",
  },
  auth: {
    loginTab: "Entrar",
    registerTab: "Criar conta",
    usernameLabel: "Nome de usuario",
    emailLabel: "Email",
    passwordLabel: "Senha",
    confirmPasswordLabel: "Confirmar senha",
    forgotPassword: "Esqueci a senha",
    orContinueWith: "ou continue com",
    continueWithGoogle: "Continuar com Google",
    noAccountPrompt: "Nao tem conta? ",
    hasAccountPrompt: "Ja tem conta? ",
    usernameRequiredRegister: "Informe um nome de usuario.",
    emailRequired: "Informe um email.",
    passwordRulesIncomplete: "Complete os requisitos da senha.",
    passwordsDoNotMatch: "As senhas nao coincidem.",
    usernameRequiredLogin: "Informe seu usuario.",
    passwordRequired: "Informe sua senha.",
    errorUsernameExists: "Esse usuario ja existe. Tente entrar ou escolha outro nome.",
    errorInvalidCredentials: "Usuario ou senha incorretos.",
    errorPasswordUppercase: "A senha precisa ter uma letra maiuscula.",
    errorPasswordLowercase: "A senha precisa ter uma letra minuscula.",
    errorPasswordNumber: "A senha precisa ter um numero.",
    errorPasswordLength: "A senha precisa ter pelo menos 6 caracteres.",
    errorEmailInvalid: "Informe um email valido.",
    errorBackendUnavailable: "Nao consegui conectar no backend. Confirme se o Django esta rodando na porta configurada.",
    errorLoginFallback: "Nao foi possivel entrar. Confira usuario e senha.",
    errorRegisterFallback: "Nao foi possivel criar a conta. Confira os dados e tente novamente.",
    passwordRuleLength: "Pelo menos 6 caracteres",
    passwordRuleUppercase: "Uma letra maiuscula",
    passwordRuleLowercase: "Uma letra minuscula",
    passwordRuleNumber: "Um numero",
  },
  onboarding: {
    stepProgress: (step: number, total: number) => `Passo ${step} de ${total}`,
    next: "Proximo",
    start: "Comecar meu plano",
    configureCourseTitle: "Configure seu curso",
    configureCourseSubtitle: "Escolha os idiomas e seu ponto de partida",
    sourceLanguageDetailPt: "Explicacoes em portugues",
    loadingLanguages: "Carregando idiomas...",
    routineTitle: "Crie sua rotina",
    routineSubtitle: "Voce pode estudar qualquer dia - vamos te lembrar nesses",
    youSpeak: "Voce fala...",
    youLearn: "Voce quer aprender...",
    levelLabel: "Nivel inicial",
    levelIniciante: "Iniciante",
    levelA1Detail: "Estou comecando do zero",
    daysLabel: "Dias de estudo",
    durationLabel: "Duracao da sessao",
    chooseDayError: "Escolha pelo menos um dia",
    estimateSentence: (months: number) => `No seu ritmo, voce chega no A1 em cerca de ${months} ${months === 1 ? "mes" : "meses"}`,
    estimatePace: (days: number, duration: string) => `${days}x por semana - ${duration} por sessao`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 hora",
    minutesShort: (minutes: number) => `${minutes} min`,
    flagAlt: (code: string) => `${code} flag`,
  },
  profile: {
    noEmail: "Sem email cadastrado",
    memberLabel: "Conta Fluenci",
    activeCourse: "Curso ativo",
    otherAreas: "Outras areas",
    addArea: "Adicionar area de estudo",
    addAreaDetail: "Espanhol, frances e mais",
    accountSection: "Conta",
    changePassword: "Alterar senha",
    signOut: "Sair da conta",
    deleteAreaTitle: "Excluir area?",
    deleteAreaBody: (name: string) => `${name} sera removido do seu perfil. Essa acao nao pode ser desfeita.`,
    cancelAction: "Cancelar",
    planLabel: "Plano",
    planName: "Gratuito",
    planDetail: "Acesso basico",
    weekActivity: "Atividade da semana",
    viewHistory: "Ver historico completo",
    editRoutine: "Editar",
    editRoutineTitle: "Editar rotina",
    saveRoutine: "Salvar rotina",
    chooseDayError: "Escolha pelo menos um dia",
    casualStudy: "Estudo avulso",
    allDays: "Todo dia",
    loading: "Carregando perfil...",
    unavailable: "Perfil indisponivel.",
    addAreaTitle: "Adicionar area",
    learnTarget: "Voce quer aprender",
    studyDays: "Dias de estudo",
    duration: "Duracao",
    saving: "Salvando...",
    close: "Fechar",
    upgrade: "Upgrade",
    useArea: "Usar",
    progressComplete: (pct: number) => `${pct}% concluido`,
  },
  adventure: {
    title: "Aventura",
    hubTitle: "Entre na aventura",
    hubSubtitle: "Escolha se quer abrir o mapa, conferir sua mochila ou ver o que ja desbloqueou.",
    openMap: "Abrir mapa",
    collectionTitle: "Colecao da aventura",
    inventory: "Mochila",
    chests: "Baus",
    words: "Palavras",
    hero: "Heroi",
    characters: "Personagens",
    inventoryEyebrow: "Inventario",
    inventorySubtitle: "Itens que voce ganhou na historia aparecem aqui.",
    chestsEyebrow: "Recompensas",
    chestsSubtitle: "Baus guardados, abrindo ou prontos para coletar.",
    wordsEyebrow: "Vocabulario",
    wordsSubtitle: "Palavras desbloqueadas pela aventura.",
    heroEyebrow: "Progresso",
    heroSubtitle: "Nivel, XP, sequencia e atributos da jornada.",
    charactersEyebrow: "Elenco",
    charactersSubtitle: "Aliados, NPCs e figuras importantes que voce encontrou.",
    collectionLoadError: "Nao foi possivel carregar esta area da aventura.",
    inventoryEmpty: "Sua mochila esta vazia. Complete fases para coletar itens.",
    chestsEmpty: "Complete fases com bau para guardar recompensas aqui.",
    wordsEmpty: "Complete a primeira secao para ver as palavras aqui.",
    heroEmpty: "Dados do heroi indisponiveis.",
    charactersEmpty: "Os personagens aparecerao conforme voce avanca.",
    used: "usado",
    available: "disponivel",
    ready: "pronto",
    chestTitle: (tier: string) => `Bau ${tier}`,
    phaseScore: (phase: number, score: number) => `Fase ${phase} - score ${score}`,
    heroLevel: "Nivel",
    heroXp: "XP",
    heroPhases: "Fases",
    heroStreak: "Sequencia",
    heroVocabulary: "Vocabulario",
    heroGrammar: "Gramatica",
    heroFluency: "Fluencia",
    mapTitle: "Mapa",
    bossLabel: "Chefe",
    reviewLabel: "Revisao",
    currentLabel: "Atual",
    lockedLabel: "Travada",
    completedLabel: "Concluida",
    dayShort: "Dia",
    phaseStart: "Iniciar fase",
    phaseStartReview: "Revisar fase",
    phaseStartBoss: "Enfrentar chefe",
    sectionLabel: (done: number, total: number) => `Secao ${done}/${total}`,
    phasesCompleted: (done: number, total: number) => `${done}/${total} fases concluidas`,
    keyWords: "Palavras-chave",
    phaseType: "Tipo",
    npc: "NPC",
    loading: "Carregando aventura...",
    empty: "Nenhuma aventura disponivel.",
    phaseLabel: (n: number) => `Fase ${n}`,
    sectionProgress: (done: number, total: number) => `${done}/${total} secoes`,
    backToMap: "Voltar ao mapa",
    languageBridge: "Ponte de idioma",
    narrativeOrder: "Ordem narrativa",
    yes: "Sim",
    no: "Nao",
    met: "encontrado",
    undiscovered: "por descobrir",
    details: "Detalhes",
    itemAction: "Acao",
    itemSource: "Origem",
    itemEarnedAt: "Ganho em",
    useItem: "Usar item",
    itemAlreadyUsed: "Item ja usado",
    chestStatus: "Status",
    chestReward: "Recompensa",
    chestEmptyReward: "Recompensa ainda nao revelada",
    startChest: "Abrir bau",
    claimChest: "Coletar bau",
    chestAlreadyClaimed: "Bau ja coletado",
    chestsStoredMetric: "Guardados",
    chestsOpeningMetric: "Abrindo",
    chestsReadyMetric: "Prontos",
    chestsSlotsTitle: "Slots de abertura",
    chestsStoredTitle: "Baus guardados",
    chestSlotEmpty: "Slot vazio",
    chestsSlotsFull: "Slots cheios",
    chestReadyToClaim: "Pronto para coletar",
    chestStoredForLater: "Guardado para abrir depois",
    actionError: "Nao foi possivel concluir a acao.",
    wordTier: "Nivel",
    wordNative: "Traducao",
    answer: "Responder",
    phaseLoading: "Carregando fase...",
    phaseEmptySections: "Fase sem secoes.",
    recapTitle: "Onde paramos",
    answerCorrect: (correct: string) => `Correto: ${correct}`,
    completeSection: "Secao concluida",
    correctCount: (count: number) => `${count} acertos`,
    mistakesCount: (count: number) => `${count} erros`,
    finish: "Concluir",
    phaseCompleted: "Fase concluida",
    practicedWords: "Palavras praticadas",
    earnedItem: "Item ganho",
  },
  today: {
    tabSession: "Sessao guiada",
    tabModules: "Modulos",
  },
  study: {
    title: "Estudo guiado",
    headline: "Treine o que a aventura esta pedindo agora.",
    pendingReviews: (count: number) => `${count} revisoes pendentes`,
    nextPhase: "Proxima fase",
    startAdventureTitle: "Comece sua aventura",
    adventureMap: "Mapa da aventura",
    continueAdventureHint: "A fase atual define o vocabulario que aparece no estudo.",
    continueAdventureBtn: "Continuar aventura",
    studyNowBtn: "Estudar agora",
    currentLesson: "Licao atual",
    lessonFallback: "Aula guiada",
    moduleLessons: (count: number) => `${count} licoes`,
    phrasesCount: (count: number) => `${count} frases`,
    studyPhrasesBtn: (count: number) => `Estudar ${count} frases`,
    noWordsDetail: "Abra a aventura ou atualize o seed para liberar frases desta aula.",
    reviewNowTitle: "Revisao espaçada",
    reviewNowSubtitle: "Reforce as palavras que estao vencendo no SRS.",
    reviewNowWords: (count: number) => `${count} palavras para revisar`,
    reviewBtn: "Revisar agora",
    pathEyebrow: "Trilha de estudo",
    pathTitle: "Modulos do seed",
    pathDetail: "As aulas seguem a fase da aventura e reaproveitam o conteudo cadastrado.",
    moduleLabel: (order: number) => `Modulo ${order}`,
    phaseLabel: (phase: number) => `Fase ${phase}`,
    unlocked: "Liberada",
    locked: "Travada",
    completed: "Concluida",
    current: "Atual",
    sessionComplete: "Revisao concluida",
    sessionScore: (correct: number, mistakes: number) => `${correct} acertos - ${mistakes} erros`,
    answer: "Responder",
    exit: "Sair",
    lessonSessionTitle: "Sessao guiada",
    phraseProgress: (current: number, total: number) => `Frase ${current} de ${total}`,
    showTranslation: "Mostrar traducao",
    nextPhrase: "Proxima frase",
    finishLesson: "Concluir aula",
    sourcePhrase: "Base",
    targetPhrase: "Resposta",
  },
  admin: {
    app: {
      title: "Admin",
      subtitle: "Backoffice",
      panel: "Painel administrativo",
      loading: "Carregando dados...",
      empty: "Sem dados carregados.",
      search: "Buscar",
      refresh: "Atualizar dados",
      logout: "Sair",
      apiStatus: "Django API",
      apiStatusDetail: "Usando endpoints administrativos protegidos.",
    },
    auth: {
      description: "Entre com um usuario staff ou superuser para gerenciar conteudo, usuarios e areas.",
      username: "Usuario",
      password: "Senha",
      submit: "Entrar",
      submitting: "Entrando...",
      error: "Nao foi possivel entrar.",
      forbidden: "Usuario sem permissao de admin.",
      loadError: "Nao foi possivel carregar os dados.",
    },
    groups: {
      operation: "Operacao",
      content: "Conteudo",
      strategy: "Estrategia",
      system: "Sistema",
    },
    shared: {
      fields: {
        id: "ID",
        name: "Nome",
        title: "Titulo",
        status: "Status",
        created: "Criado em",
        user: "Usuario",
        email: "Email",
        language: "Idioma",
        level: "Nivel",
        type: "Tipo",
        total: "Total",
        description: "Descricao",
      },
      status: {
        active: "Ativo",
        inactive: "Inativo",
        yes: "Sim",
        no: "Nao",
        staff: "Staff",
        student: "Aluno",
        connected: "Conectado",
        planned: "Planejado",
      },
    },
    apps: {
      dashboard: { title: "Dashboard", description: "Visao geral do produto" },
      users: { title: "Usuarios", description: "Contas, acesso e atividade" },
      goals: { title: "Areas", description: "Cursos e rotinas dos usuarios" },
      content: { title: "Catalogo", description: "Idiomas, cenarios e frases" },
      learning: { title: "Estudo", description: "Modulos, aulas e study days" },
      adventure: { title: "Aventura", description: "Capitulos, fases, personagens e itens" },
      progress: { title: "Progresso", description: "Conclusoes, SRS, favoritos e maestria" },
      businessPlan: { title: "Modelo de negocio", description: "Cenarios, premissas, runway e validacao" },
      system: { title: "Apps Django", description: "Mapa dos dominios e endpoints" },
    },
    businessPlan: {
      scenario: "Cenario",
      assumptions: "Premissas",
      validation: "Validacao",
      pessimistic: "Pessimista",
      realistic: "Realista",
      optimistic: "Otimista",
      monthlyPrice: "Preco mensal",
      activeUsers: "Usuarios ativos",
      payingUsers: "Pagantes",
      mrr: "MRR",
      costs: "Custos",
      runway: "Runway",
      risk: "Risco",
    },
  },
  errors: {
    generic: "Nao foi possivel concluir a acao.",
  },
} as const;
