export const PT_BR = {
  app: {
    name: "Talkly",
    subtitle: "Aprenda idiomas vivendo a historia",
    loading: "Carregando Talkly...",
  },
  actions: {
    back: "Voltar",
    continue: "Continuar",
    start: "Comecar",
    createArea: "Criar area",
    finish: "Concluir",
    retry: "Tentar novamente",
    close: "Fechar",
    save: "Salvar",
    cancel: "Cancelar",
  },
  nav: {
    home: "Home",
    adventure: "Aventura",
    study: "Estudo",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  states: {
    loadingStudy: "Carregando estudo...",
    studyLoadError: "Nao foi possivel carregar o estudo.",
    emptyReview: "Nenhuma revisao pendente.",
  },
  home: {
    title: "Hoje",
    headline: "Continue de onde parou.",
    adventureCta: "Continuar aventura",
    studyCta: "Estudar agora",
    languagePath: (source: string, target: string, level: string) => `${source} para ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min por sessao`,
    studyToday: "Hoje e dia de estudo",
    levelBadge: (lang: string, current: string, target: string) => `${lang} · ${current} → ${target}`,
    startDay: "Comecar o dia",
    continueAdventure: "Continuar Aventura",
    phrasesLabel: "frases",
    noRoutine: "Sem rotina definida",
    nextSessionTitle: "Proxima sessao",
    nextSession: (date: string) => `Proxima sessao: ${date}`,
    adventurePosition: (series: string, seriesName: string, season: number, phase: number) =>
      `Serie ${series} · ${seriesName} · T${season} · F${phase}`,
    studyDaySubtitle: (lang: string, minutes: string) => `${lang} - ${minutes}`,
    noActiveArea: "Nenhuma area ativa",
    noActiveAreaDetail: "Crie uma area de estudo para comecar seu plano de idiomas.",
    statStreak: "Sequencia",
    statWords: "Palavras",
    statLevel: "Nivel",
    routineTitle: "Rotina",
    noFixedSchedule: "Sem agenda fixa: estude quando quiser",
    allDays: "Todo dia",
    flexibleStudy: "Estudo avulso",
  },
  adventureSeries: {
    A1: "Vila Medieval",
    A2: "Bundesliga",
    B1: "Berlim",
    B2: "Espioes",
    C1: "Ruinas Antigas",
  },
  weekdays: {
    short: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"] as readonly string[],
  },
  languages: {
    DE: "Alemao",
    ES: "Espanhol",
    EN: "Ingles",
    IT: "Italiano",
    FR: "Frances",
    JA: "Japones",
    PT: "Portugues",
  },
  auth: {
    loginTab: "Entrar",
    registerTab: "Criar conta",
    usernameLabel: "Nome de usuario",
    emailLabel: "Email",
    passwordLabel: "Senha",
    confirmPasswordLabel: "Confirmar senha",
    forgotPassword: "Esqueci a senha",
    orContinueWith: "ou continue com",
    continueWithGoogle: "Continuar com Google",
    noAccountPrompt: "Nao tem conta? ",
    hasAccountPrompt: "Ja tem conta? ",
    usernameRequiredRegister: "Informe um nome de usuario.",
    emailRequired: "Informe um email.",
    passwordRulesIncomplete: "Complete os requisitos da senha.",
    passwordsDoNotMatch: "As senhas nao coincidem.",
    usernameRequiredLogin: "Informe seu usuario.",
    passwordRequired: "Informe sua senha.",
    errorUsernameExists: "Esse usuario ja existe. Tente entrar ou escolha outro nome.",
    errorInvalidCredentials: "Usuario ou senha incorretos.",
    errorPasswordUppercase: "A senha precisa ter uma letra maiuscula.",
    errorPasswordLowercase: "A senha precisa ter uma letra minuscula.",
    errorPasswordNumber: "A senha precisa ter um numero.",
    errorPasswordLength: "A senha precisa ter pelo menos 6 caracteres.",
    errorEmailInvalid: "Informe um email valido.",
    errorBackendUnavailable: "Nao consegui conectar no backend. Confirme se o Django esta rodando na porta configurada.",
    errorLoginFallback: "Nao foi possivel entrar. Confira usuario e senha.",
    errorRegisterFallback: "Nao foi possivel criar a conta. Confira os dados e tente novamente.",
    passwordRuleLength: "Pelo menos 6 caracteres",
    passwordRuleUppercase: "Uma letra maiuscula",
    passwordRuleLowercase: "Uma letra minuscula",
    passwordRuleNumber: "Um numero",
  },
  onboarding: {
    stepProgress: (step: number, total: number) => `Passo ${step} de ${total}`,
    next: "Proximo",
    start: "Comecar meu plano",
    configureCourseTitle: "Configure seu curso",
    configureCourseSubtitle: "Escolha os idiomas e seu ponto de partida",
    sourceLanguageDetailPt: "Explicacoes em portugues",
    loadingLanguages: "Carregando idiomas...",
    routineTitle: "Crie sua rotina",
    routineSubtitle: "Voce pode estudar qualquer dia - vamos te lembrar nesses",
    youSpeak: "Voce fala...",
    youLearn: "Voce quer aprender...",
    levelLabel: "Nivel inicial",
    levelIniciante: "Iniciante",
    levelA1Detail: "Estou comecando do zero",
    daysLabel: "Dias de estudo",
    durationLabel: "Duracao da sessao",
    chooseDayError: "Escolha pelo menos um dia",
    estimateSentence: (months: number) => `No seu ritmo, voce chega no A1 em cerca de ${months} ${months === 1 ? "mes" : "meses"}`,
    estimatePace: (days: number, duration: string) => `${days}x por semana - ${duration} por sessao`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 hora",
    minutesShort: (minutes: number) => `${minutes} min`,
    flagAlt: (code: string) => `${code} flag`,
  },
  adventure: {
    title: "Aventura",
    mapTitle: "Mapa",
    loading: "Carregando aventura...",
    empty: "Nenhuma aventura disponivel.",
    phaseLabel: (n: number) => `Fase ${n}`,
    sectionProgress: (done: number, total: number) => `${done}/${total} secoes`,
    backToMap: "Voltar ao mapa",
    languageBridge: "Ponte de idioma",
    narrativeOrder: "Ordem narrativa",
    yes: "Sim",
    no: "Nao",
    met: "encontrado",
    undiscovered: "por descobrir",
  },
  today: {
    tabSession: "Sessao guiada",
    tabModules: "Modulos",
  },
  study: {
    title: "Estudo guiado",
    headline: "Treine o que a aventura esta pedindo agora.",
    pendingReviews: (count: number) => `${count} revisoes pendentes`,
    nextPhase: "Proxima fase",
    startAdventureTitle: "Comece sua aventura",
    adventureMap: "Mapa da aventura",
    continueAdventureHint: "A fase atual define o vocabulario que aparece no estudo.",
    continueAdventureBtn: "Continuar aventura",
    studyNowBtn: "Estudar agora",
    currentLesson: "Licao atual",
    lessonFallback: "Aula guiada",
    moduleLessons: (count: number) => `${count} licoes`,
    phrasesCount: (count: number) => `${count} frases`,
    studyPhrasesBtn: (count: number) => `Estudar ${count} frases`,
    noWordsDetail: "Abra a aventura ou atualize o seed para liberar frases desta aula.",
    reviewNowTitle: "Revisao espaçada",
    reviewNowSubtitle: "Reforce as palavras que estao vencendo no SRS.",
    reviewNowWords: (count: number) => `${count} palavras para revisar`,
    reviewBtn: "Revisar agora",
    pathEyebrow: "Trilha de estudo",
    pathTitle: "Modulos do seed",
    pathDetail: "As aulas seguem a fase da aventura e reaproveitam o conteudo cadastrado.",
    moduleLabel: (order: number) => `Modulo ${order}`,
    phaseLabel: (phase: number) => `Fase ${phase}`,
    unlocked: "Liberada",
    locked: "Travada",
    completed: "Concluida",
    current: "Atual",
    sessionComplete: "Revisao concluida",
    sessionScore: (correct: number, mistakes: number) => `${correct} acertos - ${mistakes} erros`,
    answer: "Responder",
    exit: "Sair",
  },
  admin: {
    app: {
      title: "Admin",
      subtitle: "Backoffice",
      panel: "Painel administrativo",
      loading: "Carregando dados...",
      empty: "Sem dados carregados.",
      search: "Buscar",
      refresh: "Atualizar dados",
      logout: "Sair",
      apiStatus: "Django API",
      apiStatusDetail: "Usando endpoints administrativos protegidos.",
    },
    auth: {
      description: "Entre com um usuario staff ou superuser para gerenciar conteudo, usuarios e areas.",
      username: "Usuario",
      password: "Senha",
      submit: "Entrar",
      submitting: "Entrando...",
      error: "Nao foi possivel entrar.",
      forbidden: "Usuario sem permissao de admin.",
      loadError: "Nao foi possivel carregar os dados.",
    },
    groups: {
      operation: "Operacao",
      content: "Conteudo",
      strategy: "Estrategia",
      system: "Sistema",
    },
    shared: {
      fields: {
        id: "ID",
        name: "Nome",
        title: "Titulo",
        status: "Status",
        created: "Criado em",
        user: "Usuario",
        email: "Email",
        language: "Idioma",
        level: "Nivel",
        type: "Tipo",
        total: "Total",
        description: "Descricao",
      },
      status: {
        active: "Ativo",
        inactive: "Inativo",
        yes: "Sim",
        no: "Nao",
        staff: "Staff",
        student: "Aluno",
        connected: "Conectado",
        planned: "Planejado",
      },
    },
    apps: {
      dashboard: { title: "Dashboard", description: "Visao geral do produto" },
      users: { title: "Usuarios", description: "Contas, acesso e atividade" },
      goals: { title: "Areas", description: "Cursos e rotinas dos usuarios" },
      content: { title: "Catalogo", description: "Idiomas, cenarios e frases" },
      learning: { title: "Estudo", description: "Modulos, aulas e study days" },
      adventure: { title: "Aventura", description: "Capitulos, fases, personagens e itens" },
      progress: { title: "Progresso", description: "Conclusoes, SRS, favoritos e maestria" },
      businessPlan: { title: "Modelo de negocio", description: "Cenarios, premissas, runway e validacao" },
      system: { title: "Apps Django", description: "Mapa dos dominios e endpoints" },
    },
    businessPlan: {
      scenario: "Cenario",
      assumptions: "Premissas",
      validation: "Validacao",
      pessimistic: "Pessimista",
      realistic: "Realista",
      optimistic: "Otimista",
      monthlyPrice: "Preco mensal",
      activeUsers: "Usuarios ativos",
      payingUsers: "Pagantes",
      mrr: "MRR",
      costs: "Custos",
      runway: "Runway",
      risk: "Risco",
    },
  },
  errors: {
    generic: "Nao foi possivel concluir a acao.",
  },
} as const;
