export const PT_BR = {
  app: {
    name: "Talkly",
    subtitle: "Aprenda idiomas vivendo a historia",
    loading: "Carregando Talkly...",
  },
  actions: {
    back: "Voltar",
    continue: "Continuar",
    start: "Comecar",
    finish: "Concluir",
    retry: "Tentar novamente",
    close: "Fechar",
    save: "Salvar",
    cancel: "Cancelar",
  },
  nav: {
    home: "Home",
    adventure: "Aventura",
    study: "Estudo",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  home: {
    title: "Hoje",
    headline: "Continue de onde parou.",
    adventureCta: "Continuar aventura",
    studyCta: "Estudar agora",
  },
  weekdays: {
    short: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"] as readonly string[],
  },
  languages: {
    DE: "Alemao",
    ES: "Espanhol",
    EN: "Ingles",
    IT: "Italiano",
    FR: "Frances",
    JA: "Japones",
    PT: "Portugues",
  },
  auth: {
    loginTab: "Entrar",
    registerTab: "Criar conta",
    usernameLabel: "Nome de usuario",
    emailLabel: "Email",
    passwordLabel: "Senha",
    confirmPasswordLabel: "Confirmar senha",
    forgotPassword: "Esqueci a senha",
    orContinueWith: "ou continue com",
    continueWithGoogle: "Continuar com Google",
    noAccountPrompt: "Nao tem conta? ",
    hasAccountPrompt: "Ja tem conta? ",
    usernameRequiredRegister: "Informe um nome de usuario.",
    emailRequired: "Informe um email.",
    passwordRulesIncomplete: "Complete os requisitos da senha.",
    passwordsDoNotMatch: "As senhas nao coincidem.",
    usernameRequiredLogin: "Informe seu usuario.",
    passwordRequired: "Informe sua senha.",
    errorUsernameExists: "Esse usuario ja existe. Tente entrar ou escolha outro nome.",
    errorInvalidCredentials: "Usuario ou senha incorretos.",
    errorPasswordUppercase: "A senha precisa ter uma letra maiuscula.",
    errorPasswordLowercase: "A senha precisa ter uma letra minuscula.",
    errorPasswordNumber: "A senha precisa ter um numero.",
    errorPasswordLength: "A senha precisa ter pelo menos 6 caracteres.",
    errorEmailInvalid: "Informe um email valido.",
    errorBackendUnavailable: "Nao consegui conectar no backend. Confirme se o Django esta rodando na porta configurada.",
    errorLoginFallback: "Nao foi possivel entrar. Confira usuario e senha.",
    errorRegisterFallback: "Nao foi possivel criar a conta. Confira os dados e tente novamente.",
    passwordRuleLength: "Pelo menos 6 caracteres",
    passwordRuleUppercase: "Uma letra maiuscula",
    passwordRuleLowercase: "Uma letra minuscula",
    passwordRuleNumber: "Um numero",
  },
  onboarding: {
    stepProgress: (step: number, total: number) => `Passo ${step} de ${total}`,
    next: "Proximo",
    start: "Comecar meu plano",
    configureCourseTitle: "Configure seu curso",
    configureCourseSubtitle: "Escolha os idiomas e seu ponto de partida",
    sourceLanguageDetailPt: "Explicacoes em portugues",
    loadingLanguages: "Carregando idiomas...",
    routineTitle: "Crie sua rotina",
    routineSubtitle: "Voce pode estudar qualquer dia - vamos te lembrar nesses",
    youSpeak: "Voce fala...",
    youLearn: "Voce quer aprender...",
    levelLabel: "Nivel inicial",
    levelIniciante: "Iniciante",
    levelA1Detail: "Estou comecando do zero",
    daysLabel: "Dias de estudo",
    durationLabel: "Duracao da sessao",
    chooseDayError: "Escolha pelo menos um dia",
    estimateSentence: (months: number) => `No seu ritmo, voce chega no A1 em cerca de ${months} ${months === 1 ? "mes" : "meses"}`,
    estimatePace: (days: number, duration: string) => `${days}x por semana - ${duration} por sessao`,
    hourShort: "1h",
    hourAndHalfShort: "1h30",
    hourLong: "1 hora",
    minutesShort: (minutes: number) => `${minutes} min`,
    flagAlt: (code: string) => `${code} flag`,
  },
  adventure: {
    title: "Aventura",
    mapTitle: "Mapa",
    loading: "Carregando aventura...",
    empty: "Nenhuma aventura disponivel.",
    phaseLabel: (n: number) => `Fase ${n}`,
    sectionProgress: (done: number, total: number) => `${done}/${total} secoes`,
    backToMap: "Voltar ao mapa",
    languageBridge: "Ponte de idioma",
    narrativeOrder: "Ordem narrativa",
    yes: "Sim",
    no: "Nao",
    met: "encontrado",
    undiscovered: "por descobrir",
  },
  errors: {
    generic: "Nao foi possivel concluir a acao.",
  },
} as const;
