import { APP_NAME, APP_TAGLINE_EN, APP_TAGLINE_PT } from "./app";

export type AppLocale = "pt" | "en";

const PT_STRINGS = {
  app: {
    name: APP_NAME,
    subtitle: APP_TAGLINE_PT,
    loading: `Carregando ${APP_NAME}...`,
  },
  nav: {
    home: "Home",
    adventure: "Aventura",
    today: "Estudo",
    history: "Historico",
    scenarios: "Cenarios",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  actions: {
    startToday: "Comecar estudo do dia",
    showTranslation: "Mostrar traducao",
    hideTranslation: "Ocultar traducao",
    next: "Proxima",
    favorite: "Favoritar",
    remove: "Remover",
    openVideo: "Abrir video",
    skip: "Pular",
    check: "Verificar",
    continue: "Continuar",
    logout: "Sair",
    manageInProfile: "Gerenciar no perfil",
    use: "Usar",
    delete: "Excluir",
    createArea: "Criar area",
    creating: "Criando...",
  },
  states: {
    loading: "Carregando...",
    empty: "Nenhum conteudo encontrado.",
    apiHint: "Inicie o backend e rode o seed para carregar os dados reais.",
  },
  layout: {
    interfaceLanguage: "Idioma da tela",
    portuguese: "Portugues",
    english: "Ingles",
    activeArea: "Area ativa",
    completed: "concluido",
    loggedAs: "Logado como",
    switchArea: "Trocar area",
    chooseActiveStudy: "Escolha seu estudo ativo",
    enteringArea: "Entrando na area",
  },
  home: {
    title: "Hoje",
    eyebrow: "Seu proximo passo",
    headline: "Continue de onde parou.",
    subtitle: "Uma sessao curta com video, frases do contexto e pratica de memoria para fixar melhor.",
    lessons: "licoes concluidas",
    streak: "dias de sequencia",
    progress: "progresso",
    remaining: "dias restantes",
    recommendedPace: "Como estudar hoje",
    recommendedDetail: "Assista ao video rapido, tente entender as frases sem traducao e finalize verificando sua resposta.",
    activeGoal: "Meta ativa",
    learned: (learned: number, total: number) => `${learned} de ${total} frases aprendidas.`,
    duration: (days: number) => `Meta de ${days} dias`,
    languagePath: (source: string, target: string, level: string) => `${source} para ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min por sessao`,
    studyToday: "Hoje e dia de estudo",
    nextSession: (date: string) => `Proxima sessao: ${date}`,
    flexibleStudy: "Estudo avulso",
    noFixedSchedule: "Sem agenda fixa: estude quando quiser",
    dailyPlan: "Plano da sessao",
    dailyPlanDetail: "Video curto, pratica guiada e revisao das frases que voce favoritar.",
    nextLesson: "Proxima licao",
    keepGoing: "Faltam poucos minutos para manter sua sequencia.",
  },
  today: {
    titlePrefix: "Day",
    session: "Sessao guiada de ~15 min",
    lesson: "Licao",
    video: "Video",
    practice: "Reforco",
    inputPrompt: "Leia a frase no idioma alvo e tente lembrar o significado antes de revelar.",
    recallPrompt: "Escreva em alemao:",
    correct: "Boa resposta",
    tryAgain: "Tente novamente ou avance",
    completed: "Dia concluido",
    completedDetail: "Seu progresso foi atualizado para esta area.",
    noLessonsTitle: "Este estudo ainda nao tem licoes.",
    noLessonsDetail: "Troque para uma area com seed ou adicione conteudo para este par de idiomas.",
  },
  scenarios: {
    title: "Cenarios",
    subtitle: "Explore frases por contexto de uso real.",
    eyebrow: "Contextos reais",
  },
  vocabulary: {
    title: "Vocabulario",
    subtitle: "Revise frases favoritadas durante o estudo.",
    eyebrow: "Revisao pessoal",
  },
  profile: {
    eyebrow: "Perfil",
    title: "Conta e areas",
    subtitle: "Gerencie sua conta e escolha qual linha de estudo fica ativa.",
    noEmail: "Sem email cadastrado",
    newArea: "Nova area",
    yourAreas: "Suas areas",
    active: "Ativa",
    completeLessons: (count: number) => `${count} licoes completas`,
    streak: (count: number) => `${count} streak`,
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Monte sua meta inicial",
    source: "Origem",
    target: "Destino",
    session: "Sessao",
    duration: "Duracao da meta",
    start: "Comecar meu plano",
  },
} as const;

const EN_STRINGS = {
  app: {
    name: APP_NAME,
    subtitle: APP_TAGLINE_EN,
    loading: `Loading ${APP_NAME}...`,
  },
  nav: {
    home: "Home",
    adventure: "Adventure",
    today: "Study",
    history: "History",
    scenarios: "Scenarios",
    vocabulary: "Vocabulary",
    profile: "Profile",
  },
  actions: {
    startToday: "Start today's study",
    showTranslation: "Show translation",
    hideTranslation: "Hide translation",
    next: "Next",
    favorite: "Favorite",
    remove: "Remove",
    openVideo: "Open video",
    skip: "Skip",
    check: "Check",
    continue: "Continue",
    logout: "Log out",
    manageInProfile: "Manage in profile",
    use: "Use",
    delete: "Delete",
    createArea: "Create area",
    creating: "Creating...",
  },
  states: {
    loading: "Loading...",
    empty: "No content found.",
    apiHint: "Start the backend and run the seed to load real data.",
  },
  layout: {
    interfaceLanguage: "Screen language",
    portuguese: "Portuguese",
    english: "English",
    activeArea: "Active area",
    completed: "completed",
    loggedAs: "Signed in as",
    switchArea: "Switch area",
    chooseActiveStudy: "Choose your active study",
    enteringArea: "Entering area",
  },
  home: {
    title: "Today",
    eyebrow: "Your next step",
    headline: "Continue where you left off.",
    subtitle: "A short session with video, contextual phrases, and memory practice to make it stick.",
    lessons: "completed lessons",
    streak: "day streak",
    progress: "progress",
    remaining: "days remaining",
    recommendedPace: "How to study today",
    recommendedDetail: "Watch the short video, try to understand each phrase without translation, then check your recall.",
    activeGoal: "Active goal",
    learned: (learned: number, total: number) => `${learned} of ${total} phrases learned.`,
    duration: (days: number) => `${days}-day goal`,
    languagePath: (source: string, target: string, level: string) => `${source} to ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min per session`,
    studyToday: "Today is a study day",
    nextSession: (date: string) => `Next session: ${date}`,
    flexibleStudy: "Flexible study",
    noFixedSchedule: "No fixed schedule: study whenever you want",
    dailyPlan: "Session plan",
    dailyPlanDetail: "Short video, guided practice, and review of the phrases you save.",
    nextLesson: "Next lesson",
    keepGoing: "A few minutes are enough to keep your streak moving.",
  },
  today: {
    titlePrefix: "Day",
    session: "~15 min guided session",
    lesson: "Lesson",
    video: "Video",
    practice: "Practice",
    inputPrompt: "Read the target-language phrase and try to remember the meaning before revealing it.",
    recallPrompt: "Write it in German:",
    correct: "Good answer",
    tryAgain: "Try again or continue",
    completed: "Day completed",
    completedDetail: "Your progress was updated for this area.",
    noLessonsTitle: "This study does not have lessons yet.",
    noLessonsDetail: "Switch to an area with seed content or add content for this language pair.",
  },
  scenarios: {
    title: "Scenarios",
    subtitle: "Explore phrases by real-life context.",
    eyebrow: "Real contexts",
  },
  vocabulary: {
    title: "Vocabulary",
    subtitle: "Review phrases you saved during study.",
    eyebrow: "Personal review",
  },
  profile: {
    eyebrow: "Profile",
    title: "Account and areas",
    subtitle: "Manage your account and choose which study track is active.",
    noEmail: "No email registered",
    newArea: "New area",
    yourAreas: "Your areas",
    active: "Active",
    completeLessons: (count: number) => `${count} completed lessons`,
    streak: (count: number) => `${count} streak`,
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Set up your first goal",
    source: "Source",
    target: "Target",
    session: "Session",
    duration: "Goal duration",
    start: "Start my plan",
  },
} as const;

type WidenStrings<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => infer Return
    ? (...args: Args) => Return
    : T[K] extends string
      ? string
      : WidenStrings<T[K]>;
};

export type AppStrings = WidenStrings<typeof PT_STRINGS>;

export const STRINGS_BY_LOCALE: Record<AppLocale, AppStrings> = {
  pt: PT_STRINGS,
  en: EN_STRINGS,
};

export const STRINGS: AppStrings = PT_STRINGS;

export function getLocaleFromSourceLanguage(code?: string): AppLocale {
  return code === "EN" ? "en" : "pt";
}
