export type AppLocale = "pt" | "en";

const PT_STRINGS = {
  app: {
    name: "LinguaFlow",
    subtitle: "Estudo diario para situacoes reais",
    loading: "Carregando LinguaFlow...",
  },
  nav: {
    home: "Home",
    today: "Estudo Guiado",
    scenarios: "Cenarios",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  actions: {
    startToday: "Comecar estudo do dia",
    showTranslation: "Mostrar traducao",
    hideTranslation: "Ocultar traducao",
    next: "Proxima",
    favorite: "Favoritar",
    remove: "Remover",
    openVideo: "Abrir video",
    skip: "Pular",
    check: "Verificar",
    continue: "Continuar",
    logout: "Sair",
    manageInProfile: "Gerenciar no perfil",
    use: "Usar",
    delete: "Excluir",
    createArea: "Criar area",
    creating: "Criando...",
  },
  states: {
    loading: "Carregando...",
    empty: "Nenhum conteudo encontrado.",
    apiHint: "Inicie o backend e rode o seed para carregar os dados reais.",
  },
  layout: {
    activeArea: "Area ativa",
    completed: "concluido",
    loggedAs: "Logado como",
    switchArea: "Trocar area",
    chooseActiveStudy: "Escolha seu estudo ativo",
    enteringArea: "Entrando na area",
  },
  home: {
    title: "Hoje",
    eyebrow: "Plano de hoje",
    headline: "Pequeno sprint, progresso real.",
    subtitle: "Complete a licao diaria, marque frases importantes e avance sua meta.",
    lessons: "licoes concluidas",
    streak: "dias de sequencia",
    progress: "progresso",
    remaining: "dias restantes",
    recommendedPace: "Ritmo recomendado",
    recommendedDetail: "Uma licao por dia. O app escolhe o proximo Study Day com base nas suas conclusoes.",
    activeGoal: "Meta ativa",
    learned: (learned: number, total: number) => `${learned} de ${total} frases aprendidas.`,
  },
  today: {
    titlePrefix: "Day",
    session: "~15 min session",
    lesson: "Licao",
    video: "Video",
    practice: "Reforco",
    inputPrompt: "Tente entender a frase antes de revelar.",
    recallPrompt: "Escreva em alemao:",
    correct: "Boa resposta",
    tryAgain: "Tente novamente ou avance",
    completed: "Dia concluido",
    completedDetail: "Seu progresso foi atualizado para esta area.",
    noLessonsTitle: "Este estudo ainda nao tem licoes.",
    noLessonsDetail: "Troque para uma area com seed ou adicione conteudo para este par de idiomas.",
  },
  scenarios: {
    title: "Cenarios",
    subtitle: "Explore frases por contexto de uso real.",
    eyebrow: "Contextos reais",
  },
  vocabulary: {
    title: "Vocabulario",
    subtitle: "Revise frases favoritadas durante o estudo.",
    eyebrow: "Revisao pessoal",
  },
  profile: {
    eyebrow: "Perfil",
    title: "Conta e areas",
    subtitle: "Gerencie sua conta e escolha qual linha de estudo fica ativa.",
    noEmail: "Sem email cadastrado",
    newArea: "Nova area",
    yourAreas: "Suas areas",
    active: "Ativa",
    completeLessons: (count: number) => `${count} licoes completas`,
    streak: (count: number) => `${count} streak`,
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Monte sua meta inicial",
    source: "Origem",
    target: "Destino",
    session: "Sessao",
    duration: "Duracao da meta",
    start: "Comecar meu plano",
  },
} as const;

const EN_STRINGS = {
  app: {
    name: "LinguaFlow",
    subtitle: "Daily study for real situations",
    loading: "Loading LinguaFlow...",
  },
  nav: {
    home: "Home",
    today: "Guided Study",
    scenarios: "Scenarios",
    vocabulary: "Vocabulary",
    profile: "Profile",
  },
  actions: {
    startToday: "Start today's study",
    showTranslation: "Show translation",
    hideTranslation: "Hide translation",
    next: "Next",
    favorite: "Favorite",
    remove: "Remove",
    openVideo: "Open video",
    skip: "Skip",
    check: "Check",
    continue: "Continue",
    logout: "Log out",
    manageInProfile: "Manage in profile",
    use: "Use",
    delete: "Delete",
    createArea: "Create area",
    creating: "Creating...",
  },
  states: {
    loading: "Loading...",
    empty: "No content found.",
    apiHint: "Start the backend and run the seed to load real data.",
  },
  layout: {
    activeArea: "Active area",
    completed: "completed",
    loggedAs: "Signed in as",
    switchArea: "Switch area",
    chooseActiveStudy: "Choose your active study",
    enteringArea: "Entering area",
  },
  home: {
    title: "Today",
    eyebrow: "Today's plan",
    headline: "Small sprint, real progress.",
    subtitle: "Complete your daily lesson, save important phrases, and move your goal forward.",
    lessons: "completed lessons",
    streak: "day streak",
    progress: "progress",
    remaining: "days remaining",
    recommendedPace: "Recommended pace",
    recommendedDetail: "One lesson per day. The app chooses the next Study Day based on your completions.",
    activeGoal: "Active goal",
    learned: (learned: number, total: number) => `${learned} of ${total} phrases learned.`,
  },
  today: {
    titlePrefix: "Day",
    session: "~15 min session",
    lesson: "Lesson",
    video: "Video",
    practice: "Practice",
    inputPrompt: "Try to understand the phrase before revealing it.",
    recallPrompt: "Write it in German:",
    correct: "Good answer",
    tryAgain: "Try again or continue",
    completed: "Day completed",
    completedDetail: "Your progress was updated for this area.",
    noLessonsTitle: "This study does not have lessons yet.",
    noLessonsDetail: "Switch to an area with seed content or add content for this language pair.",
  },
  scenarios: {
    title: "Scenarios",
    subtitle: "Explore phrases by real-life context.",
    eyebrow: "Real contexts",
  },
  vocabulary: {
    title: "Vocabulary",
    subtitle: "Review phrases you saved during study.",
    eyebrow: "Personal review",
  },
  profile: {
    eyebrow: "Profile",
    title: "Account and areas",
    subtitle: "Manage your account and choose which study track is active.",
    noEmail: "No email registered",
    newArea: "New area",
    yourAreas: "Your areas",
    active: "Active",
    completeLessons: (count: number) => `${count} completed lessons`,
    streak: (count: number) => `${count} streak`,
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Set up your first goal",
    source: "Source",
    target: "Target",
    session: "Session",
    duration: "Goal duration",
    start: "Start my plan",
  },
} as const;

export const STRINGS_BY_LOCALE = {
  pt: PT_STRINGS,
  en: EN_STRINGS,
} as const;

export type AppStrings = typeof PT_STRINGS;

export const STRINGS = PT_STRINGS;

export function getLocaleFromSourceLanguage(code?: string): AppLocale {
  return code === "EN" ? "en" : "pt";
}
