import { APP_NAME, APP_TAGLINE_EN, APP_TAGLINE_PT } from "./app";

export type AppLocale = "pt" | "en";

const PT_STRINGS = {
  app: {
    name: APP_NAME,
    subtitle: APP_TAGLINE_PT,
    loading: `Carregando ${APP_NAME}...`,
  },
  nav: {
    home: "Home",
    adventure: "Aventura",
    today: "Estudo",
    history: "Historico",
    scenarios: "Cenarios",
    vocabulary: "Vocabulario",
    profile: "Perfil",
  },
  actions: {
    startToday: "Comecar estudo do dia",
    showTranslation: "Mostrar traducao",
    hideTranslation: "Ocultar traducao",
    next: "Proxima",
    favorite: "Favoritar",
    remove: "Remover",
    openVideo: "Abrir video",
    skip: "Pular",
    check: "Verificar",
    continue: "Continuar",
    back: "Voltar",
    logout: "Sair",
    manageInProfile: "Gerenciar no perfil",
    use: "Usar",
    delete: "Excluir",
    createArea: "Criar area",
    creating: "Criando...",
  },
  states: {
    loading: "Carregando...",
    empty: "Nenhum conteudo encontrado.",
    apiHint: "Inicie o backend e rode o seed para carregar os dados reais.",
  },
  layout: {
    interfaceLanguage: "Idioma da tela",
    portuguese: "Portugues",
    english: "Ingles",
    activeArea: "Area ativa",
    completed: "concluido",
    loggedAs: "Logado como",
    switchArea: "Trocar area",
    chooseActiveStudy: "Escolha seu estudo ativo",
    enteringArea: "Entrando na area",
  },
  home: {
    title: "Hoje",
    eyebrow: "Seu proximo passo",
    headline: "Continue de onde parou.",
    subtitle: "Uma sessao curta com video, frases do contexto e pratica de memoria para fixar melhor.",
    lessons: "licoes concluidas",
    streak: "dias de sequencia",
    progress: "progresso",
    remaining: "dias restantes",
    recommendedPace: "Como estudar hoje",
    recommendedDetail: "Assista ao video rapido, tente entender as frases sem traducao e finalize verificando sua resposta.",
    activeGoal: "Meta ativa",
    learned: (learned: number, total: number) => `${learned} de ${total} frases aprendidas.`,
    duration: (days: number) => `Meta de ${days} dias`,
    languagePath: (source: string, target: string, level: string) => `${source} para ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min por sessao`,
    studyToday: "Hoje e dia de estudo",
    nextSession: (date: string) => `Proxima sessao: ${date}`,
    flexibleStudy: "Estudo avulso",
    noFixedSchedule: "Sem agenda fixa: estude quando quiser",
    dailyPlan: "Plano da sessao",
    dailyPlanDetail: "Video curto, pratica guiada e revisao das frases que voce favoritar.",
    nextLesson: "Proxima licao",
    keepGoing: "Faltam poucos minutos para manter sua sequencia.",
    noActiveArea: "Nenhuma area ativa",
    noActiveAreaDetail: "Crie uma area de estudo para comecar seu plano de idiomas.",
    phrasesLabel: "frases",
    goalLabel: "Meta",
    daysLabel: "dias",
    noRoutine: "Sem rotina definida",
    startDay: "Comecar o dia",
    continueAdventure: "Continuar Aventura",
    adventurePosition: (series: string, seriesName: string, season: number, phase: number) =>
      `Serie ${series} · ${seriesName} · T${season} · F${phase}`,
    statStreak: "Sequencia",
    statWords: "Palavras",
    statLevel: "Nivel",
    nextSessionTitle: "Proxima sessao",
    studyDaySubtitle: (lang: string, minutes: string) => `${lang} · ${minutes}`,
  },
  adventureSeries: {
    A1: "Vila Medieval",
    A2: "Bundesliga",
    B1: "Berlim",
    B2: "Espioes",
    C1: "Ruinas Antigas",
  },
  study: {
    reviewNowTitle: "Revisar agora",
    reviewNowSubtitle: "Palavras para revisar",
    reviewNowWords: (n: number) => `${n} palavras`,
    reviewBtn: "Revisar",
    continueTitle: "Continuar aprendendo",
    continueBtn: "Comecar",
    continueAdventureBtn: "Ir para aventura",
    continueAdventureHint: "Continue de onde parou",
    studyNowBtn: "Estudar agora",
    seasonsTitle: "Temporadas",
    unitsTitle: "Unidades",
    sessionTitle: "Sessao de Revisao",
    sessionProgress: (current: number, total: number) => `${current} de ${total}`,
    sessionEmpty: "Tudo em dia!",
    sessionEmptyDetail: "Volte depois de estudar na aventura.",
    sessionComplete: "Sessao concluida!",
    sessionScore: (correct: number, total: number) => `${correct} de ${total} corretas`,
    sessionScoreDetail: (pct: number) => `${pct === 100 ? "Perfeito!" : pct >= 80 ? "Muito bom!" : pct >= 60 ? "Bom trabalho." : "Continue praticando."}`,
    noWordsTitle: "Nenhuma palavra ainda",
    noWordsDetail: "Complete secoes na aventura para desbloquear palavras.",
    writePlaceholder: "Digite a palavra...",
    hintLabel: "Dica",
    correctLabel: "Correto!",
    wrongLabel: "Errado",
    modulesTitle: "Modulos",
    moduleLabel: (n: number) => `Modulo ${n}`,
    lessonPhaseRef: (n: number) => `Fase ${n}`,
    modulesEmpty: "Nenhum modulo disponivel para este idioma ainda.",
    startAdventureTitle: "Comece sua jornada",
    phrasesCount: (n: number) => `${n} frases`,
    lessonTitle: "Lição atual",
    vocabListEyebrow: "Vocabulário da lição",
    studyPhrasesBtn: (n: number) => `Estudar ${n} frases`,
    guidedIntroDetail: "Veja cada palavra com tradução, depois pratique.",
    guidedNewWord: "Palavra nova",
    guidedWordOf: (i: number, n: number) => `${i} de ${n}`,
    guidedUnderstood: "Entendi",
    guidedCheckQuestion: (src: string) => `Como se diz "${src}"?`,
    guidedPracticeTitle: "Hora de praticar!",
    guidedPracticeDetail: (n: number) => `Você viu ${n} palavras. Agora vamos testar!`,
    guidedPracticeStart: "Praticar",
  },
  today: {
    titlePrefix: "Day",
    session: "Sessao guiada de ~15 min",
    lesson: "Licao",
    video: "Video",
    practice: "Reforco",
    inputPrompt: "Leia a frase no idioma alvo e tente lembrar o significado antes de revelar.",
    recallPrompt: "Escreva em alemao:",
    correct: "Boa resposta",
    tryAgain: "Tente novamente ou avance",
    completed: "Dia concluido",
    completedDetail: "Seu progresso foi atualizado para esta area.",
    noLessonsTitle: "Este estudo ainda nao tem licoes.",
    noLessonsDetail: "Troque para uma area com seed ou adicione conteudo para este par de idiomas.",
    tabSession: "Estudo Guiado",
    tabScenarios: "Cenarios",
    tabModules: "Cenários",
  },
  scenarios: {
    title: "Cenarios",
    subtitle: "Explore frases por contexto de uso real.",
    eyebrow: "Contextos reais",
    phrasesCount: (n: number) => `${n} frases`,
    selectPrompt: "Selecione um cenario para ver as frases.",
  },
  vocabulary: {
    title: "Vocabulario",
    subtitle: "Frases que voce salvou durante o estudo.",
    eyebrow: "Revisao pessoal",
    filterAll: "Todos",
    emptyTitle: "Nenhuma frase salva",
    emptyDetail: "Favorite frases durante o estudo e elas apareceram aqui.",
    filterEmpty: "Nenhuma frase nesta categoria.",
  },
  profile: {
    eyebrow: "Perfil",
    title: "Conta e areas",
    subtitle: "Gerencie sua conta e escolha qual linha de estudo fica ativa.",
    noEmail: "Sem email cadastrado",
    newArea: "Nova area",
    yourAreas: "Suas areas",
    active: "Ativa",
    completeLessons: (count: number) => `${count} licoes completas`,
    streak: (count: number) => `${count} streak`,
    tabProfile: "Perfil",
    tabHistory: "Historico",
    memberLabel: "Conta Fluenci",
    statStreak: "dias streak",
    statPhrases: "frases",
    statLevel: "nivel",
    otherAreas: "Outras areas",
    addArea: "Adicionar area de estudo",
    addAreaDetail: "Espanhol, frances e mais",
    accountSection: "Conta",
    changePassword: "Alterar senha",
    signOut: "Sair da conta",
    deleteAreaTitle: "Excluir area?",
    deleteAreaBody: (name: string) => `${name} sera removido do seu perfil. Essa acao nao pode ser desfeita.`,
    cancelAction: "Cancelar",
    planLabel: "Plano",
    planName: "Gratuito",
    planDetail: "Acesso basico",
    progressLabel: (level: string, pct: number) => `nivel ${level} · ${pct}% concluido`,
    weekActivity: "Atividade da semana",
    viewHistory: "Ver historico completo",
    editRoutine: "Editar",
    editRoutineTitle: "Editar rotina",
    saveRoutine: "Salvar rotina",
    chooseDayError: "Escolha pelo menos um dia",
    casualStudy: "Estudo avulso",
    allDays: "Todo dia",
  },
  weekdays: {
    short: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sab", "Dom"] as readonly string[],
  },
  languages: {
    DE: "Alemao",
    ES: "Espanhol",
    EN: "Ingles",
    IT: "Italiano",
    FR: "Frances",
    JA: "Japones",
    PT: "Portugues",
  },
  adventure: {
    exit: "Sair",
    progress: "Progresso",
    storyOf: "A historia de",
    beginAdventure: "Iniciar Aventura",
    continueAdventure: "Continuar Aventura",
    nextPhase: "Proxima fase",
    phasesCompleted: (done: number, total: number) => `${done}/${total} fases concluidas`,
    phaseLabel: (n: number) => `Fase ${n}`,
    sectionLabel: (n: number, total: number) => `Secao ${n}/${total}`,
    bossLabel: "Boss",
    reviewLabel: "Revisao",
    phaseStart: "Comecar",
    phaseStartBoss: "Enfrentar o Boss",
    phaseStartReview: "Iniciar Revisao",
    tabMap: "Mapa",
    tabBag: "Mochila",
    tabWords: "Palavras",
    tabHero: "Herói",
    tabPersonagens: "Personagens",
    phaseComplete: "Fase Concluida!",
    backToMap: "Voltar ao Mapa",
    sectionTypeIntro: "Prologo",
    sectionTypeCotidiano: "Cotidiano",
    sectionTypeAquecimento: "Aquecimento",
    sectionTypeEventoP: "Evento Principal",
    sectionTypeDecodificacao: "Decodificacao",
    sectionTypePratica: "Pratica",
    sectionTypeObstaculo: "Obstaculo",
    practiceReveal: "Revelar traducao",
    patternFormula: "Formula",
    translatePrompt: "Traduza para o italiano",
    obstaclePrompt: "Escolha a resposta correta para continuar",
    obstacleCorrect: "Correto! A porta se abre.",
    obstacleWrong: "Resposta errada. Tente novamente.",
    phaseMistakesSummary: (n: number) => n === 0 ? "Perfeito — nenhum erro!" : `${n} ${n === 1 ? "erro" : "erros"} — ${n === 1 ? "ele volta" : "eles voltam"} na próxima revisão.`,
    openingEnterVillage: "Entrar no vilarejo",
    openingGateOpens: "O portao se abre.",
    castLabel: "Elenco",
    metCount: (n: number) => `${n} ${n === 1 ? "encontrado" : "encontrados"}`,
    comingUp: "Por vir",
    speaksYourLang: "Fala sua lingua",
    inventoryLabel: "Inventario",
    itemsCollected: (n: number) => `${n} ${n === 1 ? "item coletado" : "itens coletados"}`,
    bagEmpty: "Sua mochila esta vazia. Complete fases para coletar itens.",
    toDiscover: "Por descobrir",
    itemMomentUse: (name: string) => `Usar ${name}`,
    itemMomentUseDegraded: (name: string) => `Usar ${name} (versao simples)`,
    itemMomentSkip: "Continuar sem item",
    itemMomentNoItem: "Voce nao tem esse tipo de item",
    itemMomentUsed: (name: string) => `Voce usou: ${name}`,
    chestOpen: "Abrir o bau",
    chestRewardLabel: "Recompensa do bau",
    itemLockedHint: (word: string) => `Domine "${word}" para desbloquear`,
    actionExaminar: "Examinar",
    actionEntregar: "Entregar",
    actionUsar: "Usar",
    actionEquipar: "Equipar",
    itemUsed: "Usado",
    streakToday: (n: number) => n === 1 ? "1 dia seguido!" : `${n} dias seguidos!`,
    plusOne: "+1",
    comboLabel: (n: number) => `${n}x combo!`,
    sectionWordsLabel: "Palavras desta seção",
    recapEyebrow: "Onde paramos",
    recapNowLabel: "O que vem agora",
    recapButton: "Me relembre",
    recapClose: "Fechar",
    continueBtn: "Continuar",
    devResetLabel: "DEV · pular para fase",
    devJumpTitle: "Pular para qual fase?",
    devJumpHint: "Apaga seu progresso e libera tudo até o ponto escolhido.",
    devJumpPhaseLabel: "Fase",
    devJumpSectionLabel: "Seção",
    devJumpConfirm: (phase: number, section: number) => `Pular para fase ${phase}, seção ${section}`,
    devJumpPickPhase: "Escolha uma fase",
    devJumping: "Aplicando...",
    loading: "Carregando...",
    errorLoading: "Não foi possível carregar.",
    seasonsLabel: "Temporadas",
    adventureLabel: "A aventura",
    withNpc: (name: string) => `com ${name}`,
    noCharactersYet: "Os personagens aparecerão conforme você avança.",
    wordsLearned: "Palavras aprendidas",
    vocabularyLabel: "Vocabulário",
    noWordsYet: "Complete a primeira seção para ver as palavras aqui.",
    noWordsSearch: (q: string) => `Nenhuma palavra encontrada para "${q}".`,
    wordCount: (n: number) => `${n} ${n === 1 ? "palavra" : "palavras"} até agora`,
    searchPlaceholder: "Buscar palavra...",
    itemRarity: {
      comum:    "Comum",
      raro:     "Raro",
      epico:    "Épico",
      lendario: "Lendário",
    },
    phaseSeeSummary:           "Ver resumo",
    phaseWordsSummaryEyebrow:  "Esta fase",
    phaseWordsSummaryTitle:    "Palavras praticadas",
    phaseWordsSummaryCount:    (n: number) => `${n} ${n === 1 ? "palavra" : "palavras"} desta fase`,
    phaseSeeItem:              "Ver item ganho",
    phaseItemGainedEyebrow:    "Item ganho",
    phaseToBag:                "Para a mochila",
    inventoryLoading:          "Carregando inventário...",
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Monte sua meta inicial",
    source: "Origem",
    target: "Destino",
    session: "Sessao",
    duration: "Duracao da meta",
    start: "Comecar meu plano",
    levelLabel: "Nivel inicial",
    daysLabel: "Dias de estudo",
    durationLabel: "Duracao da sessao",
    comingSoon: "Em breve",
    addAreaTitle: "Adicionar area",
    addAreaCta: "Adicionar area",
    estimateMonths: (n: number) => `~${n} ${n === 1 ? "mes" : "meses"} para o A1`,
    estimateDetail: (days: number, duration: string) => `${days}x por semana · ${duration} por sessao`,
    youSpeak: "Voce fala...",
    youLearn: "Voce quer aprender...",
    levelIniciante: "Iniciante",
    levelA1Detail: "Estou comecando do zero",
    levelBasico: "Basico",
    levelA2Detail: "Conheco algumas palavras",
    levelBase: "Tenho base",
    levelB1Detail: "Consigo me comunicar",
  },
} as const;

const EN_STRINGS = {
  app: {
    name: APP_NAME,
    subtitle: APP_TAGLINE_EN,
    loading: `Loading ${APP_NAME}...`,
  },
  nav: {
    home: "Home",
    adventure: "Adventure",
    today: "Study",
    history: "History",
    scenarios: "Scenarios",
    vocabulary: "Vocabulary",
    profile: "Profile",
  },
  actions: {
    startToday: "Start today's study",
    showTranslation: "Show translation",
    hideTranslation: "Hide translation",
    next: "Next",
    favorite: "Favorite",
    remove: "Remove",
    openVideo: "Open video",
    skip: "Skip",
    check: "Check",
    continue: "Continue",
    back: "Back",
    logout: "Log out",
    manageInProfile: "Manage in profile",
    use: "Use",
    delete: "Delete",
    createArea: "Create area",
    creating: "Creating...",
  },
  states: {
    loading: "Loading...",
    empty: "No content found.",
    apiHint: "Start the backend and run the seed to load real data.",
  },
  layout: {
    interfaceLanguage: "Screen language",
    portuguese: "Portuguese",
    english: "English",
    activeArea: "Active area",
    completed: "completed",
    loggedAs: "Signed in as",
    switchArea: "Switch area",
    chooseActiveStudy: "Choose your active study",
    enteringArea: "Entering area",
  },
  home: {
    title: "Today",
    eyebrow: "Your next step",
    headline: "Continue where you left off.",
    subtitle: "A short session with video, contextual phrases, and memory practice to make it stick.",
    lessons: "completed lessons",
    streak: "day streak",
    progress: "progress",
    remaining: "days remaining",
    recommendedPace: "How to study today",
    recommendedDetail: "Watch the short video, try to understand each phrase without translation, then check your recall.",
    activeGoal: "Active goal",
    learned: (learned: number, total: number) => `${learned} of ${total} phrases learned.`,
    duration: (days: number) => `${days}-day goal`,
    languagePath: (source: string, target: string, level: string) => `${source} to ${target} - ${level}`,
    routine: (days: string, minutes: number) => `${days} - ${minutes} min per session`,
    studyToday: "Today is a study day",
    nextSession: (date: string) => `Next session: ${date}`,
    flexibleStudy: "Flexible study",
    noFixedSchedule: "No fixed schedule: study whenever you want",
    dailyPlan: "Session plan",
    dailyPlanDetail: "Short video, guided practice, and review of the phrases you save.",
    nextLesson: "Next lesson",
    keepGoing: "A few minutes are enough to keep your streak moving.",
    noActiveArea: "No active area",
    noActiveAreaDetail: "Create a study area to start your language plan.",
    phrasesLabel: "phrases",
    goalLabel: "Goal",
    daysLabel: "days",
    noRoutine: "No routine set",
    startDay: "Start the day",
    continueAdventure: "Continue Adventure",
    adventurePosition: (series: string, seriesName: string, season: number, phase: number) =>
      `Series ${series} · ${seriesName} · S${season} · Ph${phase}`,
    statStreak: "Streak",
    statWords: "Words",
    statLevel: "Level",
    nextSessionTitle: "Next session",
    studyDaySubtitle: (lang: string, minutes: string) => `${lang} · ${minutes}`,
  },
  adventureSeries: {
    A1: "Medieval Village",
    A2: "Bundesliga",
    B1: "Berlin",
    B2: "Spies",
    C1: "Ancient Ruins",
  },
  study: {
    reviewNowTitle: "Review now",
    reviewNowSubtitle: "Words to review",
    reviewNowWords: (n: number) => `${n} words`,
    reviewBtn: "Review",
    continueTitle: "Continue learning",
    continueBtn: "Start",
    continueAdventureBtn: "Go to adventure",
    continueAdventureHint: "Pick up where you left off",
    studyNowBtn: "Study now",
    seasonsTitle: "Seasons",
    unitsTitle: "Units",
    sessionTitle: "Review Session",
    sessionProgress: (current: number, total: number) => `${current} of ${total}`,
    sessionEmpty: "All caught up!",
    sessionEmptyDetail: "Come back after studying in the adventure.",
    sessionComplete: "Session complete!",
    sessionScore: (correct: number, total: number) => `${correct} of ${total} correct`,
    sessionScoreDetail: (pct: number) => `${pct === 100 ? "Perfect!" : pct >= 80 ? "Great job!" : pct >= 60 ? "Good work." : "Keep practicing."}`,
    noWordsTitle: "No words yet",
    noWordsDetail: "Complete adventure sections to unlock words.",
    writePlaceholder: "Type the word...",
    hintLabel: "Hint",
    correctLabel: "Correct!",
    wrongLabel: "Wrong",
    modulesTitle: "Modules",
    moduleLabel: (n: number) => `Module ${n}`,
    lessonPhaseRef: (n: number) => `Phase ${n}`,
    modulesEmpty: "No modules available for this language yet.",
    startAdventureTitle: "Begin your journey",
    phrasesCount: (n: number) => `${n} phrases`,
    lessonTitle: "Current lesson",
    vocabListEyebrow: "Lesson vocabulary",
    studyPhrasesBtn: (n: number) => `Study ${n} phrases`,
    guidedIntroDetail: "See each word with translation, then practice.",
    guidedNewWord: "New word",
    guidedWordOf: (i: number, n: number) => `${i} of ${n}`,
    guidedUnderstood: "Got it",
    guidedCheckQuestion: (src: string) => `How do you say "${src}"?`,
    guidedPracticeTitle: "Practice time!",
    guidedPracticeDetail: (n: number) => `You've seen ${n} words. Now let's test!`,
    guidedPracticeStart: "Practice",
  },
  today: {
    titlePrefix: "Day",
    session: "~15 min guided session",
    lesson: "Lesson",
    video: "Video",
    practice: "Practice",
    inputPrompt: "Read the target-language phrase and try to remember the meaning before revealing it.",
    recallPrompt: "Write it in German:",
    correct: "Good answer",
    tryAgain: "Try again or continue",
    completed: "Day completed",
    completedDetail: "Your progress was updated for this area.",
    noLessonsTitle: "This study does not have lessons yet.",
    noLessonsDetail: "Switch to an area with seed content or add content for this language pair.",
    tabSession: "Guided Study",
    tabScenarios: "Scenarios",
    tabModules: "Scenarios",
  },
  scenarios: {
    title: "Scenarios",
    subtitle: "Explore phrases by real-life context.",
    eyebrow: "Real contexts",
    phrasesCount: (n: number) => `${n} phrases`,
    selectPrompt: "Select a scenario to see its phrases.",
  },
  vocabulary: {
    title: "Vocabulary",
    subtitle: "Phrases you saved during study.",
    eyebrow: "Personal review",
    filterAll: "All",
    emptyTitle: "No saved phrases",
    emptyDetail: "Save phrases during study and they'll appear here.",
    filterEmpty: "No phrases in this category.",
  },
  profile: {
    eyebrow: "Profile",
    title: "Account and areas",
    subtitle: "Manage your account and choose which study track is active.",
    noEmail: "No email registered",
    newArea: "New area",
    yourAreas: "Your areas",
    active: "Active",
    completeLessons: (count: number) => `${count} completed lessons`,
    streak: (count: number) => `${count} streak`,
    tabProfile: "Profile",
    tabHistory: "History",
    memberLabel: "Fluenci Account",
    statStreak: "day streak",
    statPhrases: "phrases",
    statLevel: "level",
    otherAreas: "Other areas",
    addArea: "Add study area",
    addAreaDetail: "Spanish, French and more",
    accountSection: "Account",
    changePassword: "Change password",
    signOut: "Sign out",
    deleteAreaTitle: "Delete area?",
    deleteAreaBody: (name: string) => `${name} will be removed from your profile. This action cannot be undone.`,
    cancelAction: "Cancel",
    planLabel: "Plan",
    planName: "Free",
    planDetail: "Basic access",
    progressLabel: (level: string, pct: number) => `Level ${level} · ${pct}% complete`,
    weekActivity: "This week",
    viewHistory: "View full history",
    editRoutine: "Edit",
    editRoutineTitle: "Edit routine",
    saveRoutine: "Save routine",
    chooseDayError: "Choose at least one day",
    casualStudy: "Flexible study",
    allDays: "Every day",
  },
  weekdays: {
    short: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as readonly string[],
  },
  languages: {
    DE: "German",
    ES: "Spanish",
    EN: "English",
    IT: "Italian",
    FR: "French",
    JA: "Japanese",
    PT: "Portuguese",
  },
  adventure: {
    exit: "Exit",
    progress: "Progress",
    storyOf: "The story of",
    beginAdventure: "Begin Adventure",
    continueAdventure: "Continue Adventure",
    nextPhase: "Next phase",
    phasesCompleted: (done: number, total: number) => `${done}/${total} phases completed`,
    phaseLabel: (n: number) => `Phase ${n}`,
    sectionLabel: (n: number, total: number) => `Section ${n}/${total}`,
    bossLabel: "Boss",
    reviewLabel: "Review",
    phaseStart: "Start",
    phaseStartBoss: "Face the Boss",
    phaseStartReview: "Start Review",
    tabMap: "Map",
    tabBag: "Bag",
    tabWords: "Words",
    tabHero: "Hero",
    tabPersonagens: "Characters",
    phaseComplete: "Phase Complete!",
    backToMap: "Back to Map",
    sectionTypeIntro: "Prologue",
    sectionTypeCotidiano: "Daily Life",
    sectionTypeAquecimento: "Warm-up",
    sectionTypeEventoP: "Main Event",
    sectionTypeDecodificacao: "Decoding",
    sectionTypePratica: "Practice",
    sectionTypeObstaculo: "Gate",
    practiceReveal: "Reveal translation",
    patternFormula: "Formula",
    translatePrompt: "Translate to Italian",
    obstaclePrompt: "Choose the correct answer to proceed",
    obstacleCorrect: "Correct! The gate opens.",
    obstacleWrong: "Wrong answer. Try again.",
    phaseMistakesSummary: (n: number) => n === 0 ? "Perfect — no mistakes!" : `${n} ${n === 1 ? "mistake" : "mistakes"} — ${n === 1 ? "it comes" : "they come"} back in the next review.`,
    openingEnterVillage: "Enter the Village",
    openingGateOpens: "The gate opens.",
    castLabel: "Cast",
    metCount: (n: number) => `${n} ${n === 1 ? "character found" : "characters found"}`,
    comingUp: "Coming up",
    speaksYourLang: "Speaks your language",
    inventoryLabel: "Inventory",
    itemsCollected: (n: number) => `${n} ${n === 1 ? "item collected" : "items collected"}`,
    bagEmpty: "Your bag is empty. Complete phases to collect items.",
    toDiscover: "Yet to discover",
    itemMomentUse: (name: string) => `Use ${name}`,
    itemMomentUseDegraded: (name: string) => `Use ${name} (worn version)`,
    itemMomentSkip: "Continue without item",
    itemMomentNoItem: "You don't have that kind of item",
    itemMomentUsed: (name: string) => `You used: ${name}`,
    chestOpen: "Open the chest",
    chestRewardLabel: "Chest reward",
    itemLockedHint: (word: string) => `Master "${word}" to unlock`,
    actionExaminar: "Examine",
    actionEntregar: "Deliver",
    actionUsar: "Use",
    actionEquipar: "Equip",
    itemUsed: "Used",
    streakToday: (n: number) => n === 1 ? "1 day streak!" : `${n} day streak!`,
    plusOne: "+1",
    comboLabel: (n: number) => `${n}x combo!`,
    sectionWordsLabel: "Words from this section",
    recapEyebrow: "Where we left off",
    recapNowLabel: "What's next",
    recapButton: "Remind me",
    recapClose: "Close",
    continueBtn: "Continue",
    devResetLabel: "DEV · jump to phase",
    devJumpTitle: "Jump to which phase?",
    devJumpHint: "Wipes your progress and unlocks everything up to the chosen point.",
    devJumpPhaseLabel: "Phase",
    devJumpSectionLabel: "Section",
    devJumpConfirm: (phase: number, section: number) => `Jump to phase ${phase}, section ${section}`,
    devJumpPickPhase: "Pick a phase",
    devJumping: "Applying...",
    loading: "Loading...",
    errorLoading: "Unable to load.",
    seasonsLabel: "Seasons",
    adventureLabel: "The adventure",
    withNpc: (name: string) => `with ${name}`,
    noCharactersYet: "Characters will appear as you progress.",
    wordsLearned: "Words learned",
    vocabularyLabel: "Vocabulary",
    noWordsYet: "Complete the first section to see words here.",
    noWordsSearch: (q: string) => `No words found for "${q}".`,
    wordCount: (n: number) => `${n} ${n === 1 ? "word" : "words"} so far`,
    searchPlaceholder: "Search word...",
    itemRarity: {
      comum:    "Common",
      raro:     "Rare",
      epico:    "Epic",
      lendario: "Legendary",
    },
    phaseSeeSummary:           "See summary",
    phaseWordsSummaryEyebrow:  "This phase",
    phaseWordsSummaryTitle:    "Words practiced",
    phaseWordsSummaryCount:    (n: number) => `${n} ${n === 1 ? "word" : "words"} from this phase`,
    phaseSeeItem:              "See earned item",
    phaseItemGainedEyebrow:    "Item earned",
    phaseToBag:                "To the bag",
    inventoryLoading:          "Loading inventory...",
  },
  onboarding: {
    eyebrow: "Onboarding",
    title: "Set up your first goal",
    source: "Source",
    target: "Target",
    session: "Session",
    duration: "Goal duration",
    start: "Start my plan",
    levelLabel: "Starting level",
    daysLabel: "Study days",
    durationLabel: "Session duration",
    comingSoon: "Coming soon",
    addAreaTitle: "Add study area",
    addAreaCta: "Add area",
    estimateMonths: (n: number) => `~${n} ${n === 1 ? "month" : "months"} to A1`,
    estimateDetail: (days: number, duration: string) => `${days}x per week · ${duration} per session`,
    youSpeak: "You speak...",
    youLearn: "You want to learn...",
    levelIniciante: "Beginner",
    levelA1Detail: "Starting from zero",
    levelBasico: "Basic",
    levelA2Detail: "I know some words",
    levelBase: "I have a base",
    levelB1Detail: "I can get by",
  },
} as const;

type WidenStrings<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => infer Return
    ? (...args: Args) => Return
    : T[K] extends string
      ? string
      : WidenStrings<T[K]>;
};

export type AppStrings = WidenStrings<typeof PT_STRINGS>;

export const STRINGS_BY_LOCALE: Record<AppLocale, AppStrings> = {
  pt: PT_STRINGS,
  en: EN_STRINGS,
};

export const STRINGS: AppStrings = PT_STRINGS;

export function getLocaleFromSourceLanguage(code?: string): AppLocale {
  return code === "EN" ? "en" : "pt";
}
