"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'The Market - market - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'ueberzeugung',
                         'min_level': 1,
                         'uses_item_tag': 'moneda',
                         'success': 'Your timing and tone make the villager listen before suspicion hardens.',
                         'fallback': 'The villager does not trust you yet, but Otto keeps the exchange from closing.'},
                        {'kind': 'narrative',
                         'text': 'The market teaches price, number, and public pressure. Greta '
                                 'notices more than she says. This is the same ES canon beat, '
                                 'adapted for EN -> DE. English tells you what is happening; '
                                 'German is what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is numbers and prices. The language focus is '
                                 'Wie viel kostet das?. Nothing is presented as a lecture; every '
                                 'phrase is tied to a person, an object, or a risk in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'eins. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'eins. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: eins.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Greta watches from the edge of the scene. The look is not '
                                 'random; it plants the next problem before you can name it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'zwei. Noch einmal.',
                         'translation': 'zwei. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: eins, zwei, drei.'},
                        {'kind': 'scene',
                         'text': 'The Market - second angle - the group shifts position'},
                        {'kind': 'narrative',
                         'text': 'This second beat keeps the village alive: Otto reacts, Der '
                                 'Markthaendler applies pressure, and the background NPCs continue '
                                 'their own business.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'drei? Ja. Aber langsam.',
                         'translation': 'drei? Yes. But slowly.',
                         'pace': 'slow'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'eins', 'native': 'one'},
                                       {'target': 'zwei', 'native': 'two'},
                                       {'target': 'drei', 'native': 'three'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'The scene needs German for "one".',
                             'options': [{'id': 'a', 'text': 'eins'},
                                         {'id': 'b', 'text': 'Wie heisst du?'},
                                         {'id': 'c', 'text': 'Wasser'},
                                         {'id': 'd', 'text': 'Der Wald'}],
                             'correct': 'a',
                             'word_id': 'de_eins',
                             'target': 'eins',
                             'native': 'one',
                             'npc_reaction': 'Der Markthaendler accepts the word: eins.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'The scene needs German for "two".',
                             'options': [{'id': 'a', 'text': 'zwei'},
                                         {'id': 'b', 'text': 'Wie heisst du?'},
                                         {'id': 'c', 'text': 'Wasser'},
                                         {'id': 'd', 'text': 'Der Wald'}],
                             'correct': 'a',
                             'word_id': 'de_zwei',
                             'target': 'zwei',
                             'native': 'two',
                             'npc_reaction': 'Der Markthaendler accepts the word: zwei.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'The scene needs German for "three".',
                             'options': [{'id': 'a', 'text': 'drei'},
                                         {'id': 'b', 'text': 'Wie heisst du?'},
                                         {'id': 'c', 'text': 'Wasser'},
                                         {'id': 'd', 'text': 'Der Wald'}],
                             'correct': 'a',
                             'word_id': 'de_drei',
                             'target': 'drei',
                             'native': 'three',
                             'npc_reaction': 'Der Markthaendler accepts the word: drei.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'A previous word returns inside the new scene: "my name '
                                         'is".',
                             'options': [{'id': 'a', 'text': 'Ich heisse'},
                                         {'id': 'b', 'text': 'eins'},
                                         {'id': 'c', 'text': 'drei'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_ich_heisse',
                             'target': 'Ich heisse',
                             'native': 'my name is',
                             'npc_reaction': 'Ich heisse. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Otto',
                             'question': 'A previous word returns inside the new scene: "what is '
                                         'your name?".',
                             'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                         {'id': 'b', 'text': 'eins'},
                                         {'id': 'c', 'text': 'drei'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_wie_heisst_du',
                             'target': 'Wie heisst du?',
                             'native': 'what is your name?',
                             'npc_reaction': 'Wie heisst du?. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Greta',
                             'question': 'A previous word returns inside the new scene: '
                                         '"stranger".',
                             'options': [{'id': 'a', 'text': 'Fremder'},
                                         {'id': 'b', 'text': 'eins'},
                                         {'id': 'c', 'text': 'drei'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_fremder',
                             'target': 'Fremder',
                             'native': 'stranger',
                             'npc_reaction': 'Fremder. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'A previous word returns inside the new scene: "bread".',
                             'options': [{'id': 'a', 'text': 'Brot'},
                                         {'id': 'b', 'text': 'eins'},
                                         {'id': 'c', 'text': 'drei'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_brot',
                             'target': 'Brot',
                             'native': 'bread',
                             'npc_reaction': 'Brot. The answer fits the scene.'}]}},
 {'section_number': 2,
  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Der Markthaendler', 'Otto', 'Greta'],
                        'story': 'The market teaches price, number, and public pressure. Greta '
                                 'notices more than she says.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for The Market. Earlier vocabulary returns because '
                                 'the situation asks for it, not because the interface changed '
                                 'modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "my name is".',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Der Weg'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_heisse',
                         'target': 'Ich heisse',
                         'native': 'my name is',
                         'npc_reaction': 'Otto nods. Ich heisse still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "what is your '
                                     'name?".',
                         'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Der Wald'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_heisst_du',
                         'target': 'Wie heisst du?',
                         'native': 'what is your name?',
                         'npc_reaction': 'Otto nods. Wie heisst du? still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "stranger".',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Hier'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_fremder',
                         'target': 'Fremder',
                         'native': 'stranger',
                         'npc_reaction': 'Otto nods. Fremder still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Dort'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_brot',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'Otto nods. Brot still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "water".',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Links'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wasser',
                         'target': 'Wasser',
                         'native': 'water',
                         'npc_reaction': 'Otto nods. Wasser still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Rechts'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hunger',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'Otto nods. Ich habe Hunger still belongs to you.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Wie viel kostet das?'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_durst',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'Otto nods. Ich habe Durst still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the road".',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Ich moechte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_weg',
                         'target': 'Der Weg',
                         'native': 'the road',
                         'npc_reaction': 'Otto nods. Der Weg still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Ich will'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wald',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'Otto nods. Der Wald still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Ich muss gehen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Otto nods. Hier still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Ich kann helfen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Otto nods. Dort still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Otto nods. Links still belongs to you.',
                         'gated': True}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Der Markthaendler', 'Otto', 'Greta'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'The Market - applied practice'},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Der Markthaendler asks '
                                 'for language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'eins. Sag es klar.',
                         'translation': 'eins. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Applied answer: choose "one".',
                         'options': [{'id': 'a', 'text': 'eins'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_eins',
                         'target': 'eins',
                         'native': 'one',
                         'npc_reaction': 'eins. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'zwei. Sag es klar.',
                         'translation': 'zwei. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "two".',
                         'options': [{'id': 'a', 'text': 'zwei'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_zwei',
                         'target': 'zwei',
                         'native': 'two',
                         'npc_reaction': 'zwei. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'drei. Sag es klar.',
                         'translation': 'drei. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "three".',
                         'options': [{'id': 'a', 'text': 'drei'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_drei',
                         'target': 'drei',
                         'native': 'three',
                         'npc_reaction': 'drei. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'Der Wald. Sag es klar.',
                         'translation': 'Der Wald. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Applied answer: choose "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wald',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'Der Wald. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Hier. Sag es klar.',
                         'translation': 'Hier. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Hier. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Dort. Sag es klar.',
                         'translation': 'Dort. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Dort. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'Links. Sag es klar.',
                         'translation': 'Links. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Applied answer: choose "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Links. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Rechts. Sag es klar.',
                         'translation': 'Rechts. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Rechts. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Wie viel kostet das?. Sag es klar.',
                         'translation': 'Wie viel kostet das?. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "how much does it cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Wie viel kostet das?. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'Wie viel kostet das?',
                          'explanation': 'Use only what the scene requires: Wie viel kostet das?.',
                          'examples': ['eins',
                                       'zwei',
                                       'drei',
                                       'Ich heisse',
                                       'Wie heisst du?',
                                       'Fremder']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: Wie viel kostet das?. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'eins. zwei. drei.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'eins'},
                                     {'id': 'b', 'text': 'zwei'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_0',
                         'target': 'eins',
                         'native': 'usable German phrase',
                         'npc_reaction': 'eins. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'zwei'},
                                     {'id': 'b', 'text': 'drei'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_1',
                         'target': 'zwei',
                         'native': 'usable German phrase',
                         'npc_reaction': 'zwei. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'drei'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_2',
                         'target': 'drei',
                         'native': 'usable German phrase',
                         'npc_reaction': 'drei. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_3',
                         'target': 'Ich heisse',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich heisse. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_4',
                         'target': 'Wie heisst du?',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Wie heisst du?. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_5',
                         'target': 'Fremder',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Fremder. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_6',
                         'target': 'Brot',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Brot. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for Wie viel kostet das?: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'eins'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_4_7',
                         'target': 'Wasser',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Wasser. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Der Markthaendler', 'Otto', 'Greta'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'item_moment',
                         'npc': 'Otto',
                         'situation': 'Leaving the market, Otto slows down. The morning was long, '
                                      'and the village has not fed anyone for free.',
                         'npc_line': 'Fremder, hast du etwas zu essen in der Tasche? Brot, Apfel, '
                                     'irgendetwas.',
                         'item_tag': 'comida',
                         'on_use': {'narrative': 'You take food from the backpack and share it '
                                                 'before the next street watches you too closely.',
                                    'npc_reaction': 'Gut. Wer Essen teilt, wird hier schneller '
                                                    'gehoert.',
                                    'bonus': 'relationship_boost'},
                         'on_skip': {'npc_reaction': 'Schon gut. Wir halten bis zur Herberge '
                                                     'durch.'}},
                        {'kind': 'scene', 'text': 'The Market - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: The '
                                 'market teaches price, number, and public pressure. Greta notices '
                                 'more than she says. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "one".',
                         'options': [{'id': 'a', 'text': 'eins'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_eins',
                         'target': 'eins',
                         'native': 'one',
                         'npc_reaction': 'eins. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Rechts. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "how much '
                                     'does it cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Wie viel kostet das?. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "two".',
                         'options': [{'id': 'a', 'text': 'zwei'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_zwei',
                         'target': 'zwei',
                         'native': 'two',
                         'npc_reaction': 'zwei. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Ich will. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "I must '
                                     'go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Ich muss gehen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "three".',
                         'options': [{'id': 'a', 'text': 'drei'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_drei',
                         'target': 'drei',
                         'native': 'three',
                         'npc_reaction': 'drei. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "one".',
                         'options': [{'id': 'a', 'text': 'eins'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_eins',
                         'target': 'eins',
                         'native': 'one',
                         'npc_reaction': 'eins. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Wahrheit. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Der Markthaendler', 'Otto', 'Greta'],
                        'story': 'The market teaches price, number, and public pressure. Greta '
                                 'notices more than she says.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'The Market - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: The market '
                                 'teaches price, number, and public pressure. Greta notices more '
                                 'than she says.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 1: answer with "one".',
                         'options': [{'id': 'a', 'text': 'eins'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_0',
                         'target': 'eins',
                         'native': 'one',
                         'npc_reaction': 'The gate accepts eins.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 2: answer with "two".',
                         'options': [{'id': 'a', 'text': 'zwei'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_1',
                         'target': 'zwei',
                         'native': 'two',
                         'npc_reaction': 'The gate accepts zwei.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 3: answer with "three".',
                         'options': [{'id': 'a', 'text': 'drei'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_2',
                         'target': 'drei',
                         'native': 'three',
                         'npc_reaction': 'The gate accepts drei.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 4: answer with "my name is".',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_3',
                         'target': 'Ich heisse',
                         'native': 'my name is',
                         'npc_reaction': 'The gate accepts Ich heisse.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 5: answer with "what is your name?".',
                         'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_4',
                         'target': 'Wie heisst du?',
                         'native': 'what is your name?',
                         'npc_reaction': 'The gate accepts Wie heisst du?.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 6: answer with "stranger".',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_5',
                         'target': 'Fremder',
                         'native': 'stranger',
                         'npc_reaction': 'The gate accepts Fremder.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 7: answer with "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_6',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'The gate accepts Brot.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Gate 8: answer with "water".',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_4_7',
                         'target': 'Wasser',
                         'native': 'water',
                         'npc_reaction': 'The gate accepts Wasser.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves the market carrying the next '
                                 'problem toward phase 5.'}]}}]
