"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'A Normal Day - ordinary_day - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'ueberzeugung',
                         'min_level': 1,
                         'uses_item_tag': 'moneda',
                         'success': 'Your timing and tone make the villager listen before suspicion hardens.',
                         'fallback': 'The villager does not trust you yet, but Otto keeps the exchange from closing.'},
                        {'kind': 'narrative',
                         'text': 'A normal day proves the village is watching. Direction words '
                                 'become survival words. This is the same ES canon beat, adapted '
                                 'for EN -> DE. English tells you what is happening; German is '
                                 'what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is navigation and suspicion. The language '
                                 'focus is verb-second word order. Nothing is presented as a '
                                 'lecture; every phrase is tied to a person, an object, or a risk '
                                 'in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'links. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'links. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: links.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Greta watches from the edge of the scene. The look is not '
                                 'random; it plants the next problem before you can name it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'rechts. Noch einmal.',
                         'translation': 'rechts. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: links, rechts, Tor.'},
                        {'kind': 'scene',
                         'text': 'A Normal Day - second angle - the group shifts position'},
                        {'kind': 'narrative',
                         'text': 'This second beat keeps the village alive: Otto reacts, Lina '
                                 'applies pressure, and the background NPCs continue their own '
                                 'business.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Tor? Ja. Aber langsam.',
                         'translation': 'Tor? Yes. But slowly.',
                         'pace': 'slow'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'links', 'native': 'left'},
                                       {'target': 'rechts', 'native': 'right'},
                                       {'target': 'Tor', 'native': 'gate'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'The scene needs German for "left".',
                             'options': [{'id': 'a', 'text': 'links'},
                                         {'id': 'b', 'text': 'Wasser'},
                                         {'id': 'c', 'text': 'Der Weg'},
                                         {'id': 'd', 'text': 'Links'}],
                             'correct': 'a',
                             'word_id': 'de_links',
                             'target': 'links',
                             'native': 'left',
                             'npc_reaction': 'Lina accepts the word: links.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'The scene needs German for "right".',
                             'options': [{'id': 'a', 'text': 'rechts'},
                                         {'id': 'b', 'text': 'Wasser'},
                                         {'id': 'c', 'text': 'Der Weg'},
                                         {'id': 'd', 'text': 'Links'}],
                             'correct': 'a',
                             'word_id': 'de_rechts',
                             'target': 'rechts',
                             'native': 'right',
                             'npc_reaction': 'Lina accepts the word: rechts.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'The scene needs German for "gate".',
                             'options': [{'id': 'a', 'text': 'Tor'},
                                         {'id': 'b', 'text': 'Wasser'},
                                         {'id': 'c', 'text': 'Der Weg'},
                                         {'id': 'd', 'text': 'Links'}],
                             'correct': 'a',
                             'word_id': 'de_tor',
                             'target': 'Tor',
                             'native': 'gate',
                             'npc_reaction': 'Lina accepts the word: Tor.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'A previous word returns inside the new scene: "bread".',
                             'options': [{'id': 'a', 'text': 'Brot'},
                                         {'id': 'b', 'text': 'links'},
                                         {'id': 'c', 'text': 'Tor'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_brot',
                             'target': 'Brot',
                             'native': 'bread',
                             'npc_reaction': 'Brot. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Otto',
                             'question': 'A previous word returns inside the new scene: "water".',
                             'options': [{'id': 'a', 'text': 'Wasser'},
                                         {'id': 'b', 'text': 'links'},
                                         {'id': 'c', 'text': 'Tor'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_wasser',
                             'target': 'Wasser',
                             'native': 'water',
                             'npc_reaction': 'Wasser. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Greta',
                             'question': 'A previous word returns inside the new scene: "I am '
                                         'hungry".',
                             'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                         {'id': 'b', 'text': 'links'},
                                         {'id': 'c', 'text': 'Tor'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_hunger',
                             'target': 'Ich habe Hunger',
                             'native': 'I am hungry',
                             'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'A previous word returns inside the new scene: "I am '
                                         'thirsty".',
                             'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                         {'id': 'b', 'text': 'links'},
                                         {'id': 'c', 'text': 'Tor'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_durst',
                             'target': 'Ich habe Durst',
                             'native': 'I am thirsty',
                             'npc_reaction': 'Ich habe Durst. The answer fits the scene.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Lina', 'Otto', 'Greta'],
                        'story': 'A normal day proves the village is watching. Direction words '
                                 'become survival words.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for A Normal Day. Earlier vocabulary returns because '
                                 'the situation asks for it, not because the interface changed '
                                 'modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Dort'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_brot',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'Otto nods. Brot still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "water".',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Links'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wasser',
                         'target': 'Wasser',
                         'native': 'water',
                         'npc_reaction': 'Otto nods. Wasser still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Rechts'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hunger',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'Otto nods. Ich habe Hunger still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Wie viel kostet das?'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_durst',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'Otto nods. Ich habe Durst still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the road".',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Ich moechte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_weg',
                         'target': 'Der Weg',
                         'native': 'the road',
                         'npc_reaction': 'Otto nods. Der Weg still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Ich will'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wald',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'Otto nods. Der Wald still belongs to you.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Ich muss gehen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Otto nods. Hier still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Ich kann helfen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Otto nods. Dort still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Otto nods. Links still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Gestern'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Otto nods. Rechts still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "how much does it '
                                     'cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Heute'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Otto nods. Wie viel kostet das? still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Otto nods. Ich moechte still belongs to you.',
                         'gated': True}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Lina', 'Otto', 'Greta'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'A Normal Day - applied practice'},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Lina asks for language '
                                 'that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'links. Sag es klar.',
                         'translation': 'links. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "left".',
                         'options': [{'id': 'a', 'text': 'links'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'links',
                         'native': 'left',
                         'npc_reaction': 'links. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'rechts. Sag es klar.',
                         'translation': 'rechts. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "right".',
                         'options': [{'id': 'a', 'text': 'rechts'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'rechts',
                         'native': 'right',
                         'npc_reaction': 'rechts. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Tor. Sag es klar.',
                         'translation': 'Tor. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "gate".',
                         'options': [{'id': 'a', 'text': 'Tor'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_tor',
                         'target': 'Tor',
                         'native': 'gate',
                         'npc_reaction': 'Tor. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Links. Sag es klar.',
                         'translation': 'Links. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Links. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Rechts. Sag es klar.',
                         'translation': 'Rechts. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Rechts. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Wie viel kostet das?. Sag es klar.',
                         'translation': 'Wie viel kostet das?. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "how much does it cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Wie viel kostet das?. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Ich moechte. Sag es klar.',
                         'translation': 'Ich moechte. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Ich moechte. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Ich will. Sag es klar.',
                         'translation': 'Ich will. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Ich will. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Ich muss gehen. Sag es klar.',
                         'translation': 'Ich muss gehen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Ich muss gehen. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'verb-second word order',
                          'explanation': 'Use only what the scene requires: verb-second word '
                                         'order.',
                          'examples': ['links',
                                       'rechts',
                                       'Tor',
                                       'Brot',
                                       'Wasser',
                                       'Ich habe Hunger']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: verb-second word order. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'links. rechts. Tor.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'links'},
                                     {'id': 'b', 'text': 'rechts'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_0',
                         'target': 'links',
                         'native': 'usable German phrase',
                         'npc_reaction': 'links. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'rechts'},
                                     {'id': 'b', 'text': 'Tor'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_1',
                         'target': 'rechts',
                         'native': 'usable German phrase',
                         'npc_reaction': 'rechts. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Tor'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_2',
                         'target': 'Tor',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Tor. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_3',
                         'target': 'Brot',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Brot. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_4',
                         'target': 'Wasser',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Wasser. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_5',
                         'target': 'Ich habe Hunger',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_6',
                         'target': 'Ich habe Durst',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich habe Durst. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for verb-second word order: choose '
                                     'the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'links'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_7_7',
                         'target': 'Der Weg',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Der Weg. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Lina', 'Otto', 'Greta'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'scene',
                         'text': 'A Normal Day - reinforcement and emotional echo'},
                        {'kind': 'item_moment',
                         'npc': 'Lina',
                         'situation': 'The afternoon heat sits in the square. Lina has been '
                                      'explaining signs and routes until her voice turns rough.',
                         'npc_line': 'Hast du etwas zu trinken? Wasser waere genug.',
                         'item_tag': 'bebida',
                         'on_use': {'narrative': 'You pass her a drink from the backpack. She '
                                                 'drinks once, then points at the gate again with '
                                                 'a steadier hand.',
                                    'npc_reaction': 'Danke. Jetzt kann ich weiterreden, ohne jedes '
                                                    'Wort zu verlieren.',
                                    'bonus': 'extra_dialogue'},
                         'on_skip': {'npc_reaction': 'Kein Problem. Der Brunnen ist nicht weit.'}},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: A '
                                 'normal day proves the village is watching. Direction words '
                                 'become survival words. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'links'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'links',
                         'native': 'left',
                         'npc_reaction': 'links. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Ich will. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "I must '
                                     'go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Ich muss gehen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'rechts'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'rechts',
                         'native': 'right',
                         'npc_reaction': 'rechts. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "gate".',
                         'options': [{'id': 'a', 'text': 'Tor'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_tor',
                         'target': 'Tor',
                         'native': 'gate',
                         'npc_reaction': 'Tor. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Wahrheit. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'links'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'links',
                         'native': 'left',
                         'npc_reaction': 'links. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Siegel. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "brother".',
                         'options': [{'id': 'a', 'text': 'Bruder'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bruder',
                         'target': 'Bruder',
                         'native': 'brother',
                         'npc_reaction': 'Bruder. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Lina', 'Otto', 'Greta'],
                        'story': 'A normal day proves the village is watching. Direction words '
                                 'become survival words.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'A Normal Day - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: A normal day '
                                 'proves the village is watching. Direction words become survival '
                                 'words.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 1: answer with "left".',
                         'options': [{'id': 'a', 'text': 'links'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_0',
                         'target': 'links',
                         'native': 'left',
                         'npc_reaction': 'The gate accepts links.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 2: answer with "right".',
                         'options': [{'id': 'a', 'text': 'rechts'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_1',
                         'target': 'rechts',
                         'native': 'right',
                         'npc_reaction': 'The gate accepts rechts.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 3: answer with "gate".',
                         'options': [{'id': 'a', 'text': 'Tor'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_2',
                         'target': 'Tor',
                         'native': 'gate',
                         'npc_reaction': 'The gate accepts Tor.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 4: answer with "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_3',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'The gate accepts Brot.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 5: answer with "water".',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_4',
                         'target': 'Wasser',
                         'native': 'water',
                         'npc_reaction': 'The gate accepts Wasser.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 6: answer with "I am hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_5',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'The gate accepts Ich habe Hunger.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 7: answer with "I am thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_6',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'The gate accepts Ich habe Durst.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Gate 8: answer with "the road".',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_7_7',
                         'target': 'Der Weg',
                         'native': 'the road',
                         'npc_reaction': 'The gate accepts Der Weg.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves a normal day carrying the next '
                                 'problem toward phase 8.'}]}}]
