"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'Four at the Table - table - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'versorgung',
                         'min_level': 1,
                         'uses_item_tag': 'comida',
                         'success': 'You read the hunger in the group early and protect the food before the walk grows harder.',
                         'fallback': 'You misjudge the supplies at first, but someone shares enough for the story to continue.'},
                        {'kind': 'narrative',
                         'text': 'The four eat together and begin to feel like a group. Otto '
                                 'privately distrusts Marta. This is the same ES canon beat, '
                                 'adapted for EN -> DE. English tells you what is happening; '
                                 'German is what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is the group becomes a unit. The language '
                                 'focus is moechte + infinitive. Nothing is presented as a '
                                 'lecture; every phrase is tied to a person, an object, or a risk '
                                 'in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Suppe. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'Suppe. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: Suppe.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Der Markthaendler watches from the edge of the scene. The look '
                                 'is not random; it plants the next problem before you can name '
                                 'it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Tisch. Noch einmal.',
                         'translation': 'Tisch. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: Suppe, Tisch, Ich moechte.'},
                        {'kind': 'scene',
                         'text': 'Four at the Table - second angle - the group shifts position'},
                        {'kind': 'narrative',
                         'text': 'This second beat keeps the village alive: Otto reacts, Marta die '
                                 'Heilerin applies pressure, and the background NPCs continue '
                                 'their own business.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Ich moechte? Ja. Aber langsam.',
                         'translation': 'Ich moechte? Yes. But slowly.',
                         'pace': 'slow'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'Suppe', 'native': 'soup'},
                                       {'target': 'Tisch', 'native': 'table'},
                                       {'target': 'Ich moechte', 'native': 'I would like'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "soup".',
                             'options': [{'id': 'a', 'text': 'Suppe'},
                                         {'id': 'b', 'text': 'Ich habe Durst'},
                                         {'id': 'c', 'text': 'Hier'},
                                         {'id': 'd', 'text': 'Wie viel kostet das?'}],
                             'correct': 'a',
                             'word_id': 'de_suppe',
                             'target': 'Suppe',
                             'native': 'soup',
                             'npc_reaction': 'Marta die Heilerin accepts the word: Suppe.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "table".',
                             'options': [{'id': 'a', 'text': 'Tisch'},
                                         {'id': 'b', 'text': 'Ich habe Durst'},
                                         {'id': 'c', 'text': 'Hier'},
                                         {'id': 'd', 'text': 'Wie viel kostet das?'}],
                             'correct': 'a',
                             'word_id': 'de_tisch',
                             'target': 'Tisch',
                             'native': 'table',
                             'npc_reaction': 'Marta die Heilerin accepts the word: Tisch.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "I would like".',
                             'options': [{'id': 'a', 'text': 'Ich moechte'},
                                         {'id': 'b', 'text': 'Ich habe Durst'},
                                         {'id': 'c', 'text': 'Hier'},
                                         {'id': 'd', 'text': 'Wie viel kostet das?'}],
                             'correct': 'a',
                             'word_id': 'de_ich_moechte',
                             'target': 'Ich moechte',
                             'native': 'I would like',
                             'npc_reaction': 'Marta die Heilerin accepts the word: Ich moechte.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'A previous word returns inside the new scene: "I am '
                                         'hungry".',
                             'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                         {'id': 'b', 'text': 'Suppe'},
                                         {'id': 'c', 'text': 'Ich moechte'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_hunger',
                             'target': 'Ich habe Hunger',
                             'native': 'I am hungry',
                             'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'A previous word returns inside the new scene: "I am '
                                         'thirsty".',
                             'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                         {'id': 'b', 'text': 'Suppe'},
                                         {'id': 'c', 'text': 'Ich moechte'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_durst',
                             'target': 'Ich habe Durst',
                             'native': 'I am thirsty',
                             'npc_reaction': 'Ich habe Durst. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Otto',
                             'question': 'A previous word returns inside the new scene: "the '
                                         'road".',
                             'options': [{'id': 'a', 'text': 'Der Weg'},
                                         {'id': 'b', 'text': 'Suppe'},
                                         {'id': 'c', 'text': 'Ich moechte'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_weg',
                             'target': 'Der Weg',
                             'native': 'the road',
                             'npc_reaction': 'Der Weg. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Markthaendler',
                             'question': 'A previous word returns inside the new scene: "the '
                                         'forest".',
                             'options': [{'id': 'a', 'text': 'Der Wald'},
                                         {'id': 'b', 'text': 'Suppe'},
                                         {'id': 'c', 'text': 'Ich moechte'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_wald',
                             'target': 'Der Wald',
                             'native': 'the forest',
                             'npc_reaction': 'Der Wald. The answer fits the scene.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Lina', 'Otto'],
                        'story': 'The four eat together and begin to feel like a group. Otto '
                                 'privately distrusts Marta.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for Four at the Table. Earlier vocabulary returns '
                                 'because the situation asks for it, not because the interface '
                                 'changed modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Rechts'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hunger',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'Otto nods. Ich habe Hunger still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I am thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Wie viel kostet das?'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_durst',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'Otto nods. Ich habe Durst still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the road".',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Ich moechte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_weg',
                         'target': 'Der Weg',
                         'native': 'the road',
                         'npc_reaction': 'Otto nods. Der Weg still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Ich will'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wald',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'Otto nods. Der Wald still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Ich muss gehen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Otto nods. Hier still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Ich kann helfen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Otto nods. Dort still belongs to you.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Otto nods. Links still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Gestern'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Otto nods. Rechts still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "how much does it '
                                     'cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Heute'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Otto nods. Wie viel kostet das? still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Otto nods. Ich moechte still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Wahrheit'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Otto nods. Ich will still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Luege'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Otto nods. Ich muss gehen still belongs to you.',
                         'gated': True}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Lina', 'Otto'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'Four at the Table - applied practice'},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Marta die Heilerin asks '
                                 'for language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Suppe. Sag es klar.',
                         'translation': 'Suppe. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "soup".',
                         'options': [{'id': 'a', 'text': 'Suppe'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_suppe',
                         'target': 'Suppe',
                         'native': 'soup',
                         'npc_reaction': 'Suppe. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Tisch. Sag es klar.',
                         'translation': 'Tisch. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "table".',
                         'options': [{'id': 'a', 'text': 'Tisch'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_tisch',
                         'target': 'Tisch',
                         'native': 'table',
                         'npc_reaction': 'Tisch. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Ich moechte. Sag es klar.',
                         'translation': 'Ich moechte. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Ich moechte. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'Wie viel kostet das?. Sag es klar.',
                         'translation': 'Wie viel kostet das?. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Applied answer: choose "how much does it cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Wie viel kostet das?. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Ich moechte. Sag es klar.',
                         'translation': 'Ich moechte. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Ich moechte. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Ich will. Sag es klar.',
                         'translation': 'Ich will. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Ich will. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Ich muss gehen. Sag es klar.',
                         'translation': 'Ich muss gehen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Ich muss gehen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Markthaendler',
                         'line': 'Ich kann helfen. Sag es klar.',
                         'translation': 'Ich kann helfen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Applied answer: choose "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Ich kann helfen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Ich erinnere mich nicht. Sag es klar.',
                         'translation': 'Ich erinnere mich nicht. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "I do not remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'moechte + infinitive',
                          'explanation': 'Use only what the scene requires: moechte + infinitive.',
                          'examples': ['Suppe',
                                       'Tisch',
                                       'Ich moechte',
                                       'Ich habe Hunger',
                                       'Ich habe Durst',
                                       'Der Weg']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: moechte + infinitive. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Suppe. Tisch. Ich moechte.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Suppe'},
                                     {'id': 'b', 'text': 'Tisch'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_0',
                         'target': 'Suppe',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Suppe. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Tisch'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_1',
                         'target': 'Tisch',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Tisch. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_2',
                         'target': 'Ich moechte',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich moechte. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_3',
                         'target': 'Ich habe Hunger',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_4',
                         'target': 'Ich habe Durst',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich habe Durst. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_5',
                         'target': 'Der Weg',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Der Weg. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_6',
                         'target': 'Der Wald',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Der Wald. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Grammar-in-scene check for moechte + infinitive: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Suppe'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_9_7',
                         'target': 'Hier',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Hier. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Lina', 'Otto'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'item_moment',
                         'npc': 'Hanna die Baeckerin',
                         'situation': 'The group sits at a rough table. Hanna notices your '
                                      'backpack before anyone asks for a plan.',
                         'npc_line': 'Hast du etwas zu essen fuer den Tisch? Geteiltes Essen macht '
                                     'aus Leuten eine Gruppe.',
                         'item_tag': 'comida',
                         'on_use': {'narrative': 'You place food in the center. Otto, Hanna, '
                                                 'Marta, and you divide it without ceremony.',
                                    'npc_reaction': 'So. Jetzt ist es ein Tisch, nicht nur ein Ort '
                                                    'zum Sitzen.',
                                    'bonus': 'relationship_boost'},
                         'on_skip': {'npc_reaction': 'Dann teilen wir, was hier ist. Naechstes Mal '
                                                     'vielleicht.'}},
                        {'kind': 'scene',
                         'text': 'Four at the Table - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: The '
                                 'four eat together and begin to feel like a group. Otto privately '
                                 'distrusts Marta. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "soup".',
                         'options': [{'id': 'a', 'text': 'Suppe'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_suppe',
                         'target': 'Suppe',
                         'native': 'soup',
                         'npc_reaction': 'Suppe. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "I can '
                                     'help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Ich kann helfen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "table".',
                         'options': [{'id': 'a', 'text': 'Tisch'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_tisch',
                         'target': 'Tisch',
                         'native': 'table',
                         'npc_reaction': 'Tisch. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I would '
                                     'like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Ich moechte. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "lie".',
                         'options': [{'id': 'a', 'text': 'Luege'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_luege',
                         'target': 'Luege',
                         'native': 'lie',
                         'npc_reaction': 'Luege. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Siegel. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "soup".',
                         'options': [{'id': 'a', 'text': 'Suppe'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_suppe',
                         'target': 'Suppe',
                         'native': 'soup',
                         'npc_reaction': 'Suppe. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "hello".',
                         'options': [{'id': 'a', 'text': 'Hallo'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hallo',
                         'target': 'Hallo',
                         'native': 'hello',
                         'npc_reaction': 'Hallo. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Markthaendler',
                         'question': 'Reinforcement with consequence: choose German for "good '
                                     'morning".',
                         'options': [{'id': 'a', 'text': 'Guten Morgen'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_guten_morgen',
                         'target': 'Guten Morgen',
                         'native': 'good morning',
                         'npc_reaction': 'Guten Morgen. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Lina', 'Otto'],
                        'story': 'The four eat together and begin to feel like a group. Otto '
                                 'privately distrusts Marta.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'Four at the Table - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: The four eat '
                                 'together and begin to feel like a group. Otto privately '
                                 'distrusts Marta.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 1: answer with "soup".',
                         'options': [{'id': 'a', 'text': 'Suppe'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_0',
                         'target': 'Suppe',
                         'native': 'soup',
                         'npc_reaction': 'The gate accepts Suppe.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 2: answer with "table".',
                         'options': [{'id': 'a', 'text': 'Tisch'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_1',
                         'target': 'Tisch',
                         'native': 'table',
                         'npc_reaction': 'The gate accepts Tisch.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 3: answer with "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_2',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'The gate accepts Ich moechte.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 4: answer with "I am hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_3',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'The gate accepts Ich habe Hunger.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 5: answer with "I am thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_4',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'The gate accepts Ich habe Durst.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 6: answer with "the road".',
                         'options': [{'id': 'a', 'text': 'Der Weg'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_5',
                         'target': 'Der Weg',
                         'native': 'the road',
                         'npc_reaction': 'The gate accepts Der Weg.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 7: answer with "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_6',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'The gate accepts Der Wald.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 8: answer with "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_9_7',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'The gate accepts Hier.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves four at the table carrying the next '
                                 'problem toward phase 10.'}]}}]
