"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'Three Days - deadline - first tableau'},
                        {'kind': 'narrative',
                         'text': 'Three days become a deadline. The group gathers testimony and '
                                 'reviews recent past forms. This is the same ES canon beat, '
                                 'adapted for EN -> DE. English tells you what is happening; '
                                 'German is what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is time and memory pressure. The language '
                                 'focus is perfect exposure: ich habe gehoert. Nothing is '
                                 'presented as a lecture; every phrase is tied to a person, an '
                                 'object, or a risk in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'gestern. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'gestern. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: gestern.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Marta die Heilerin watches from the edge of the scene. The look '
                                 'is not random; it plants the next problem before you can name '
                                 'it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'heute. Noch einmal.',
                         'translation': 'heute. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: gestern, heute, ich habe gehoert.'},
                        {'kind': 'scene',
                         'text': 'Three Days - second angle - the group shifts position'},
                        {'kind': 'narrative',
                         'text': 'This second beat keeps the village alive: Otto reacts, Friedrich '
                                 'applies pressure, and the background NPCs continue their own '
                                 'business.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'ich habe gehoert? Ja. Aber langsam.',
                         'translation': 'ich habe gehoert? Yes. But slowly.',
                         'pace': 'slow'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'gestern', 'native': 'yesterday'},
                                       {'target': 'heute', 'native': 'today'},
                                       {'target': 'ich habe gehoert', 'native': 'I heard'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Friedrich',
                             'question': 'The scene needs German for "yesterday".',
                             'options': [{'id': 'a', 'text': 'gestern'},
                                         {'id': 'b', 'text': 'Hier'},
                                         {'id': 'c', 'text': 'Rechts'},
                                         {'id': 'd', 'text': 'Ich muss gehen'}],
                             'correct': 'a',
                             'word_id': 'de_gestern',
                             'target': 'gestern',
                             'native': 'yesterday',
                             'npc_reaction': 'Friedrich accepts the word: gestern.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Friedrich',
                             'question': 'The scene needs German for "today".',
                             'options': [{'id': 'a', 'text': 'heute'},
                                         {'id': 'b', 'text': 'Hier'},
                                         {'id': 'c', 'text': 'Rechts'},
                                         {'id': 'd', 'text': 'Ich muss gehen'}],
                             'correct': 'a',
                             'word_id': 'de_heute',
                             'target': 'heute',
                             'native': 'today',
                             'npc_reaction': 'Friedrich accepts the word: heute.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Friedrich',
                             'question': 'The scene needs German for "I heard".',
                             'options': [{'id': 'a', 'text': 'ich habe gehoert'},
                                         {'id': 'b', 'text': 'Hier'},
                                         {'id': 'c', 'text': 'Rechts'},
                                         {'id': 'd', 'text': 'Ich muss gehen'}],
                             'correct': 'a',
                             'word_id': 'de_ich_habe_gehoert',
                             'target': 'ich habe gehoert',
                             'native': 'I heard',
                             'npc_reaction': 'Friedrich accepts the word: ich habe gehoert.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Friedrich',
                             'question': 'A previous word returns inside the new scene: "the '
                                         'forest".',
                             'options': [{'id': 'a', 'text': 'Der Wald'},
                                         {'id': 'b', 'text': 'gestern'},
                                         {'id': 'c', 'text': 'ich habe gehoert'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_wald',
                             'target': 'Der Wald',
                             'native': 'the forest',
                             'npc_reaction': 'Der Wald. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Greta',
                             'question': 'A previous word returns inside the new scene: "here".',
                             'options': [{'id': 'a', 'text': 'Hier'},
                                         {'id': 'b', 'text': 'gestern'},
                                         {'id': 'c', 'text': 'ich habe gehoert'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_hier',
                             'target': 'Hier',
                             'native': 'here',
                             'npc_reaction': 'Hier. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'A previous word returns inside the new scene: "there".',
                             'options': [{'id': 'a', 'text': 'Dort'},
                                         {'id': 'b', 'text': 'gestern'},
                                         {'id': 'c', 'text': 'ich habe gehoert'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_dort',
                             'target': 'Dort',
                             'native': 'there',
                             'npc_reaction': 'Dort. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Friedrich',
                             'question': 'A previous word returns inside the new scene: "left".',
                             'options': [{'id': 'a', 'text': 'Links'},
                                         {'id': 'b', 'text': 'gestern'},
                                         {'id': 'c', 'text': 'ich habe gehoert'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_links',
                             'target': 'Links',
                             'native': 'left',
                             'npc_reaction': 'Links. The answer fits the scene.'}]}},
 {'section_number': 2,
  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Friedrich', 'Greta', 'Marta die Heilerin'],
                        'story': 'Three days become a deadline. The group gathers testimony and '
                                 'reviews recent past forms.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for Three Days. Earlier vocabulary returns because '
                                 'the situation asks for it, not because the interface changed '
                                 'modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Ich will'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wald',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'Otto nods. Der Wald still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Ich muss gehen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Otto nods. Hier still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Ich kann helfen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Otto nods. Dort still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Otto nods. Links still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Gestern'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Otto nods. Rechts still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "how much does it '
                                     'cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Heute'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Otto nods. Wie viel kostet das? still belongs to you.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Otto nods. Ich moechte still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Wahrheit'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Otto nods. Ich will still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Luege'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Otto nods. Ich muss gehen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Siegel'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Otto nods. Ich kann helfen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Bruder'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Otto nods. Ich erinnere mich nicht still belongs to '
                                         'you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Hallo'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Otto nods. Gestern still belongs to you.',
                         'gated': True}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Friedrich', 'Greta', 'Marta die Heilerin'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'item_moment',
                         'npc': 'Elias der Bauer',
                         'situation': 'Elias has worked beside smoke and dust all morning. His '
                                      'throat catches before the hard memory begins.',
                         'npc_line': 'Vorher: hast du etwas zu trinken? Nur ein Schluck.',
                         'item_tag': 'bebida',
                         'on_use': {'narrative': 'You hand him a drink. Elias drinks slowly, then '
                                                 'answers with less distance in his voice.',
                                    'npc_reaction': 'Danke. Wer Wasser teilt, darf schwere Fragen '
                                                    'stellen.',
                                    'bonus': 'relationship_boost'},
                         'on_skip': {'npc_reaction': 'Schon gut. Ich rede trotzdem, aber '
                                                     'langsamer.'}},
                        {'kind': 'scene', 'text': 'Three Days - applied practice'},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Friedrich asks for '
                                 'language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'gestern. Sag es klar.',
                         'translation': 'gestern. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Applied answer: choose "yesterday".',
                         'options': [{'id': 'a', 'text': 'gestern'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'gestern. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'heute. Sag es klar.',
                         'translation': 'heute. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "today".',
                         'options': [{'id': 'a', 'text': 'heute'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'heute',
                         'native': 'today',
                         'npc_reaction': 'heute. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'ich habe gehoert. Sag es klar.',
                         'translation': 'ich habe gehoert. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "I heard".',
                         'options': [{'id': 'a', 'text': 'ich habe gehoert'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_habe_gehoert',
                         'target': 'ich habe gehoert',
                         'native': 'I heard',
                         'npc_reaction': 'ich habe gehoert. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'Ich muss gehen. Sag es klar.',
                         'translation': 'Ich muss gehen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Applied answer: choose "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Ich muss gehen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Ich kann helfen. Sag es klar.',
                         'translation': 'Ich kann helfen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Ich kann helfen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Ich erinnere mich nicht. Sag es klar.',
                         'translation': 'Ich erinnere mich nicht. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "I do not remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'Gestern. Sag es klar.',
                         'translation': 'Gestern. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Applied answer: choose "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Gestern. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Greta',
                         'line': 'Heute. Sag es klar.',
                         'translation': 'Heute. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Applied answer: choose "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Morgen. Sag es klar.',
                         'translation': 'Morgen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'perfect exposure: ich habe gehoert',
                          'explanation': 'Use only what the scene requires: perfect exposure: ich '
                                         'habe gehoert.',
                          'examples': ['gestern',
                                       'heute',
                                       'ich habe gehoert',
                                       'Der Wald',
                                       'Hier',
                                       'Dort']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: perfect exposure: ich habe gehoert. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Friedrich',
                         'line': 'gestern. heute. ich habe gehoert.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'gestern'},
                                     {'id': 'b', 'text': 'heute'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_0',
                         'target': 'gestern',
                         'native': 'usable German phrase',
                         'npc_reaction': 'gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'heute'},
                                     {'id': 'b', 'text': 'ich habe gehoert'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_1',
                         'target': 'heute',
                         'native': 'usable German phrase',
                         'npc_reaction': 'heute. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'ich habe gehoert'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_2',
                         'target': 'ich habe gehoert',
                         'native': 'usable German phrase',
                         'npc_reaction': 'ich habe gehoert. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_3',
                         'target': 'Der Wald',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Der Wald. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_4',
                         'target': 'Hier',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Hier. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_5',
                         'target': 'Dort',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Dort. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_6',
                         'target': 'Links',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Links. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Grammar-in-scene check for perfect exposure: ich habe '
                                     'gehoert: choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'gestern'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_12_7',
                         'target': 'Rechts',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Rechts. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Friedrich', 'Greta', 'Marta die Heilerin'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'scene', 'text': 'Three Days - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: Three '
                                 'days become a deadline. The group gathers testimony and reviews '
                                 'recent past forms. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"yesterday".',
                         'options': [{'id': 'a', 'text': 'gestern'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Reinforcement with consequence: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'heute'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'heute',
                         'native': 'today',
                         'npc_reaction': 'heute. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "lie".',
                         'options': [{'id': 'a', 'text': 'Luege'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_luege',
                         'target': 'Luege',
                         'native': 'lie',
                         'npc_reaction': 'Luege. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Siegel. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Reinforcement with consequence: choose German for "I heard".',
                         'options': [{'id': 'a', 'text': 'ich habe gehoert'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_habe_gehoert',
                         'target': 'ich habe gehoert',
                         'native': 'I heard',
                         'npc_reaction': 'ich habe gehoert. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "hello".',
                         'options': [{'id': 'a', 'text': 'Hallo'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hallo',
                         'target': 'Hallo',
                         'native': 'hello',
                         'npc_reaction': 'Hallo. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "good '
                                     'morning".',
                         'options': [{'id': 'a', 'text': 'Guten Morgen'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_guten_morgen',
                         'target': 'Guten Morgen',
                         'native': 'good morning',
                         'npc_reaction': 'Guten Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"yesterday".',
                         'options': [{'id': 'a', 'text': 'gestern'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Greta',
                         'question': 'Reinforcement with consequence: choose German for "please".',
                         'options': [{'id': 'a', 'text': 'Bitte'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bitte',
                         'target': 'Bitte',
                         'native': 'please',
                         'npc_reaction': 'Bitte. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "my name '
                                     'is".',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_heisse',
                         'target': 'Ich heisse',
                         'native': 'my name is',
                         'npc_reaction': 'Ich heisse. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Friedrich', 'Greta', 'Marta die Heilerin'],
                        'story': 'Three days become a deadline. The group gathers testimony and '
                                 'reviews recent past forms.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'Three Days - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: Three days '
                                 'become a deadline. The group gathers testimony and reviews '
                                 'recent past forms.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 1: answer with "yesterday".',
                         'options': [{'id': 'a', 'text': 'gestern'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_0',
                         'target': 'gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'The gate accepts gestern.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 2: answer with "today".',
                         'options': [{'id': 'a', 'text': 'heute'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_1',
                         'target': 'heute',
                         'native': 'today',
                         'npc_reaction': 'The gate accepts heute.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 3: answer with "I heard".',
                         'options': [{'id': 'a', 'text': 'ich habe gehoert'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_2',
                         'target': 'ich habe gehoert',
                         'native': 'I heard',
                         'npc_reaction': 'The gate accepts ich habe gehoert.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 4: answer with "the forest".',
                         'options': [{'id': 'a', 'text': 'Der Wald'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_3',
                         'target': 'Der Wald',
                         'native': 'the forest',
                         'npc_reaction': 'The gate accepts Der Wald.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 5: answer with "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_4',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'The gate accepts Hier.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 6: answer with "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_5',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'The gate accepts Dort.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 7: answer with "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_6',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'The gate accepts Links.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Friedrich',
                         'question': 'Gate 8: answer with "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_12_7',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'The gate accepts Rechts.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves three days carrying the next '
                                 'problem toward phase 13.'}]}}]
