"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': "Otto's Family - family - first tableau"},
                        {'kind': 'skill_check',
                         'skill': 'ueberzeugung',
                         'min_level': 2,
                         'uses_item_tag': 'moneda',
                         'success': 'Your timing and tone make the villager listen before suspicion hardens.',
                         'fallback': 'The villager does not trust you yet, but Otto keeps the exchange from closing.'},
                        {'kind': 'narrative',
                         'text': 'Klara receives the group as family and recognizes Marta from '
                                 'somewhere old. This is the same ES canon beat, adapted for EN -> '
                                 'DE. English tells you what is happening; German is what the '
                                 'world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is family vocabulary and belonging. The '
                                 'language focus is possessives: mein/dein/sein. Nothing is '
                                 'presented as a lecture; every phrase is tied to a person, an '
                                 'object, or a risk in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'Familie. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'Familie. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: Familie.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Marta die Heilerin watches from the edge of the scene. The look '
                                 'is not random; it plants the next problem before you can name '
                                 'it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'mein. Noch einmal.',
                         'translation': 'mein. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: Familie, mein, dein.'},
                        {'kind': 'scene',
                         'text': "Otto's Family - second angle - the group shifts position"},
                        {'kind': 'narrative',
                         'text': 'This second beat keeps the village alive: Otto reacts, Klara '
                                 'applies pressure, and the background NPCs continue their own '
                                 'business.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'dein? Ja. Aber langsam.',
                         'translation': 'dein? Yes. But slowly.',
                         'pace': 'slow'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'Familie', 'native': 'family'},
                                       {'target': 'mein', 'native': 'my'},
                                       {'target': 'dein', 'native': 'your'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Klara',
                             'question': 'The scene needs German for "family".',
                             'options': [{'id': 'a', 'text': 'Familie'},
                                         {'id': 'b', 'text': 'Dort'},
                                         {'id': 'c', 'text': 'Wie viel kostet das?'},
                                         {'id': 'd', 'text': 'Ich kann helfen'}],
                             'correct': 'a',
                             'word_id': 'de_familie',
                             'target': 'Familie',
                             'native': 'family',
                             'npc_reaction': 'Klara accepts the word: Familie.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Klara',
                             'question': 'The scene needs German for "my".',
                             'options': [{'id': 'a', 'text': 'mein'},
                                         {'id': 'b', 'text': 'Dort'},
                                         {'id': 'c', 'text': 'Wie viel kostet das?'},
                                         {'id': 'd', 'text': 'Ich kann helfen'}],
                             'correct': 'a',
                             'word_id': 'de_mein',
                             'target': 'mein',
                             'native': 'my',
                             'npc_reaction': 'Klara accepts the word: mein.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Klara',
                             'question': 'The scene needs German for "your".',
                             'options': [{'id': 'a', 'text': 'dein'},
                                         {'id': 'b', 'text': 'Dort'},
                                         {'id': 'c', 'text': 'Wie viel kostet das?'},
                                         {'id': 'd', 'text': 'Ich kann helfen'}],
                             'correct': 'a',
                             'word_id': 'de_dein',
                             'target': 'dein',
                             'native': 'your',
                             'npc_reaction': 'Klara accepts the word: dein.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Klara',
                             'question': 'A previous word returns inside the new scene: "here".',
                             'options': [{'id': 'a', 'text': 'Hier'},
                                         {'id': 'b', 'text': 'Familie'},
                                         {'id': 'c', 'text': 'dein'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_hier',
                             'target': 'Hier',
                             'native': 'here',
                             'npc_reaction': 'Hier. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Otto',
                             'question': 'A previous word returns inside the new scene: "there".',
                             'options': [{'id': 'a', 'text': 'Dort'},
                                         {'id': 'b', 'text': 'Familie'},
                                         {'id': 'c', 'text': 'dein'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_dort',
                             'target': 'Dort',
                             'native': 'there',
                             'npc_reaction': 'Dort. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Lina',
                             'question': 'A previous word returns inside the new scene: "left".',
                             'options': [{'id': 'a', 'text': 'Links'},
                                         {'id': 'b', 'text': 'Familie'},
                                         {'id': 'c', 'text': 'dein'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_links',
                             'target': 'Links',
                             'native': 'left',
                             'npc_reaction': 'Links. The answer fits the scene.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'A previous word returns inside the new scene: "right".',
                             'options': [{'id': 'a', 'text': 'Rechts'},
                                         {'id': 'b', 'text': 'Familie'},
                                         {'id': 'c', 'text': 'dein'},
                                         {'id': 'd', 'text': 'Vielleicht'}],
                             'correct': 'a',
                             'word_id': 'de_rechts',
                             'target': 'Rechts',
                             'native': 'right',
                             'npc_reaction': 'Rechts. The answer fits the scene.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Klara', 'Otto', 'Lina'],
                        'story': 'Klara receives the group as family and recognizes Marta from '
                                 'somewhere old.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': "Review loop for Otto's Family. Earlier vocabulary returns "
                                 'because the situation asks for it, not because the interface '
                                 'changed modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Ich muss gehen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hier',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'Otto nods. Hier still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Ich kann helfen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dort',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'Otto nods. Dort still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Ich moechte'},
                                     {'id': 'c', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_links',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'Otto nods. Links still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Ich will'},
                                     {'id': 'c', 'text': 'Gestern'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_rechts',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'Otto nods. Rechts still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "how much does it '
                                     'cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Ich muss gehen'},
                                     {'id': 'c', 'text': 'Heute'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_viel',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'Otto nods. Wie viel kostet das? still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I would like".',
                         'options': [{'id': 'a', 'text': 'Ich moechte'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_moechte',
                         'target': 'Ich moechte',
                         'native': 'I would like',
                         'npc_reaction': 'Otto nods. Ich moechte still belongs to you.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I want".',
                         'options': [{'id': 'a', 'text': 'Ich will'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Wahrheit'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_will',
                         'target': 'Ich will',
                         'native': 'I want',
                         'npc_reaction': 'Otto nods. Ich will still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I must go".',
                         'options': [{'id': 'a', 'text': 'Ich muss gehen'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Luege'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_muss_gehen',
                         'target': 'Ich muss gehen',
                         'native': 'I must go',
                         'npc_reaction': 'Otto nods. Ich muss gehen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Siegel'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Otto nods. Ich kann helfen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Bruder'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Otto nods. Ich erinnere mich nicht still belongs to '
                                         'you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Hallo'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Otto nods. Gestern still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Guten Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Otto nods. Heute still belongs to you.',
                         'gated': True}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Klara', 'Otto', 'Lina'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': "Otto's Family - applied practice"},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Klara asks for language '
                                 'that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'Familie. Sag es klar.',
                         'translation': 'Familie. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Applied answer: choose "family".',
                         'options': [{'id': 'a', 'text': 'Familie'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_familie',
                         'target': 'Familie',
                         'native': 'family',
                         'npc_reaction': 'Familie. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'mein. Sag es klar.',
                         'translation': 'mein. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "my".',
                         'options': [{'id': 'a', 'text': 'mein'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_mein',
                         'target': 'mein',
                         'native': 'my',
                         'npc_reaction': 'mein. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'dein. Sag es klar.',
                         'translation': 'dein. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "your".',
                         'options': [{'id': 'a', 'text': 'dein'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dein',
                         'target': 'dein',
                         'native': 'your',
                         'npc_reaction': 'dein. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Ich kann helfen. Sag es klar.',
                         'translation': 'Ich kann helfen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Ich kann helfen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'Ich erinnere mich nicht. Sag es klar.',
                         'translation': 'Ich erinnere mich nicht. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Applied answer: choose "I do not remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Gestern. Sag es klar.',
                         'translation': 'Gestern. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Gestern. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'Heute. Sag es klar.',
                         'translation': 'Heute. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Morgen. Sag es klar.',
                         'translation': 'Morgen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'Wahrheit. Sag es klar.',
                         'translation': 'Wahrheit. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Applied answer: choose "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Wahrheit. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'possessives: mein/dein/sein',
                          'explanation': 'Use only what the scene requires: possessives: '
                                         'mein/dein/sein.',
                          'examples': ['Familie', 'mein', 'dein', 'Hier', 'Dort', 'Links']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: possessives: mein/dein/sein. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Klara',
                         'line': 'Familie. mein. dein.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Familie'},
                                     {'id': 'b', 'text': 'mein'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_0',
                         'target': 'Familie',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Familie. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'mein'},
                                     {'id': 'b', 'text': 'dein'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_1',
                         'target': 'mein',
                         'native': 'usable German phrase',
                         'npc_reaction': 'mein. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'dein'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_2',
                         'target': 'dein',
                         'native': 'usable German phrase',
                         'npc_reaction': 'dein. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_3',
                         'target': 'Hier',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Hier. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_4',
                         'target': 'Dort',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Dort. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Rechts'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_5',
                         'target': 'Links',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Links. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Wie viel kostet das?'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_6',
                         'target': 'Rechts',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Rechts. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for possessives: mein/dein/sein: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Familie'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_13_7',
                         'target': 'Wie viel kostet das?',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Wie viel kostet das?. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Klara', 'Otto', 'Lina'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'item_moment',
                         'npc': 'Klara',
                         'situation': 'Klara stirs the pot. The house is poor, and every small '
                                      'thing changes the meal.',
                         'npc_line': 'Wenn du etwas zu essen hast, leg es auf den Tisch. In diesem '
                                     'Haus wird geteilt.',
                         'item_tag': 'comida',
                         'on_use': {'narrative': 'You take food from the backpack and put it '
                                                 'beside the bowls. Klara smiles like someone who '
                                                 'has decided something.',
                                    'npc_reaction': 'Gut. Wer etwas an einen fremden Tisch bringt, '
                                                    'bleibt nicht ganz fremd.',
                                    'bonus': 'relationship_boost'},
                         'on_skip': {'npc_reaction': 'Setz dich trotzdem. Die Suppe reicht.'}},
                        {'kind': 'scene',
                         'text': "Otto's Family - reinforcement and emotional echo"},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: Klara '
                                 'receives the group as family and recognizes Marta from somewhere '
                                 'old. The repeated words now carry relationship weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Reinforcement with consequence: choose German for "family".',
                         'options': [{'id': 'a', 'text': 'Familie'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_familie',
                         'target': 'Familie',
                         'native': 'family',
                         'npc_reaction': 'Familie. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Wahrheit. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "my".',
                         'options': [{'id': 'a', 'text': 'mein'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_mein',
                         'target': 'mein',
                         'native': 'my',
                         'npc_reaction': 'mein. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Reinforcement with consequence: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Siegel. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "brother".',
                         'options': [{'id': 'a', 'text': 'Bruder'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bruder',
                         'target': 'Bruder',
                         'native': 'brother',
                         'npc_reaction': 'Bruder. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "your".',
                         'options': [{'id': 'a', 'text': 'dein'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_dein',
                         'target': 'dein',
                         'native': 'your',
                         'npc_reaction': 'dein. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "good '
                                     'morning".',
                         'options': [{'id': 'a', 'text': 'Guten Morgen'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_guten_morgen',
                         'target': 'Guten Morgen',
                         'native': 'good morning',
                         'npc_reaction': 'Guten Morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Reinforcement with consequence: choose German for "thank '
                                     'you".',
                         'options': [{'id': 'a', 'text': 'Danke'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_danke',
                         'target': 'Danke',
                         'native': 'thank you',
                         'npc_reaction': 'Danke. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "family".',
                         'options': [{'id': 'a', 'text': 'Familie'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_familie',
                         'target': 'Familie',
                         'native': 'family',
                         'npc_reaction': 'Familie. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "my name '
                                     'is".',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_heisse',
                         'target': 'Ich heisse',
                         'native': 'my name is',
                         'npc_reaction': 'Ich heisse. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "what is '
                                     'your name?".',
                         'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_heisst_du',
                         'target': 'Wie heisst du?',
                         'native': 'what is your name?',
                         'npc_reaction': 'Wie heisst du?. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Klara', 'Otto', 'Lina'],
                        'story': 'Klara receives the group as family and recognizes Marta from '
                                 'somewhere old.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': "Otto's Family - gated close"},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: Klara receives '
                                 'the group as family and recognizes Marta from somewhere old.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 1: answer with "family".',
                         'options': [{'id': 'a', 'text': 'Familie'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_0',
                         'target': 'Familie',
                         'native': 'family',
                         'npc_reaction': 'The gate accepts Familie.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 2: answer with "my".',
                         'options': [{'id': 'a', 'text': 'mein'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_1',
                         'target': 'mein',
                         'native': 'my',
                         'npc_reaction': 'The gate accepts mein.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 3: answer with "your".',
                         'options': [{'id': 'a', 'text': 'dein'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_2',
                         'target': 'dein',
                         'native': 'your',
                         'npc_reaction': 'The gate accepts dein.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 4: answer with "here".',
                         'options': [{'id': 'a', 'text': 'Hier'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_3',
                         'target': 'Hier',
                         'native': 'here',
                         'npc_reaction': 'The gate accepts Hier.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 5: answer with "there".',
                         'options': [{'id': 'a', 'text': 'Dort'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_4',
                         'target': 'Dort',
                         'native': 'there',
                         'npc_reaction': 'The gate accepts Dort.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 6: answer with "left".',
                         'options': [{'id': 'a', 'text': 'Links'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_5',
                         'target': 'Links',
                         'native': 'left',
                         'npc_reaction': 'The gate accepts Links.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 7: answer with "right".',
                         'options': [{'id': 'a', 'text': 'Rechts'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_6',
                         'target': 'Rechts',
                         'native': 'right',
                         'npc_reaction': 'The gate accepts Rechts.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Klara',
                         'question': 'Gate 8: answer with "how much does it cost?".',
                         'options': [{'id': 'a', 'text': 'Wie viel kostet das?'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_13_7',
                         'target': 'Wie viel kostet das?',
                         'native': 'how much does it cost?',
                         'npc_reaction': 'The gate accepts Wie viel kostet das?.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': "Transition: the group leaves otto's family carrying the next "
                                 'problem toward phase 14.'}]}}]
