"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'Facing Marta - confront_marta - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'heilung',
                         'min_level': 2,
                         'uses_item_tag': 'remedio',
                         'success': 'You handle the injury cleanly before pain can take over the conversation.',
                         'fallback': 'You only manage basic care, but Marta steadies the moment and the phase continues.'},
                        {'kind': 'narrative',
                         'text': 'The group confronts Marta with questions. Her answers help, but '
                                 'never fully settle. This is the same ES canon beat, adapted for '
                                 'EN -> DE. English tells you what is happening; German is what '
                                 'the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is hard questions inside the group. The '
                                 'language focus is wenn clauses exposure. Nothing is presented as '
                                 'a lecture; every phrase is tied to a person, an object, or a '
                                 'risk in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'wenn. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'wenn. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: wenn.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Lina watches from the edge of the scene. The look is not random; '
                                 'it plants the next problem before you can name it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Kraut. Noch einmal.',
                         'translation': 'Kraut. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: wenn, Kraut, helfen.'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'wenn', 'native': 'when/if'},
                                       {'target': 'Kraut', 'native': 'herb'},
                                       {'target': 'helfen', 'native': 'help'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "when/if".',
                             'options': [{'id': 'a', 'text': 'wenn'},
                                         {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                         {'id': 'c', 'text': 'Morgen'},
                                         {'id': 'd', 'text': 'Bruder'}],
                             'correct': 'a',
                             'word_id': 'de_wenn',
                             'target': 'wenn',
                             'native': 'when/if',
                             'npc_reaction': 'Marta die Heilerin accepts the word: wenn.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "herb".',
                             'options': [{'id': 'a', 'text': 'Kraut'},
                                         {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                         {'id': 'c', 'text': 'Morgen'},
                                         {'id': 'd', 'text': 'Bruder'}],
                             'correct': 'a',
                             'word_id': 'de_kraut',
                             'target': 'Kraut',
                             'native': 'herb',
                             'npc_reaction': 'Marta die Heilerin accepts the word: Kraut.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Marta die Heilerin',
                             'question': 'The scene needs German for "help".',
                             'options': [{'id': 'a', 'text': 'helfen'},
                                         {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                         {'id': 'c', 'text': 'Morgen'},
                                         {'id': 'd', 'text': 'Bruder'}],
                             'correct': 'a',
                             'word_id': 'de_helfen',
                             'target': 'helfen',
                             'native': 'help',
                             'npc_reaction': 'Marta die Heilerin accepts the word: helfen.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Otto', 'Lina'],
                        'story': 'The group confronts Marta with questions. Her answers help, but '
                                 'never fully settle.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for Facing Marta. Earlier vocabulary returns because '
                                 'the situation asks for it, not because the interface changed '
                                 'modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Siegel'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kann_helfen',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'Otto nods. Ich kann helfen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "I do not '
                                     'remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Bruder'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_erinnere_mich_nicht',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'Otto nods. Ich erinnere mich nicht still belongs to '
                                         'you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Hallo'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Otto nods. Gestern still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Guten Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Otto nods. Heute still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Danke'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Otto nods. Morgen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Bitte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Otto nods. Wahrheit still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "lie".',
                         'options': [{'id': 'a', 'text': 'Luege'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Ich heisse'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_luege',
                         'target': 'Luege',
                         'native': 'lie',
                         'npc_reaction': 'Otto nods. Luege still belongs to you.'}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Otto', 'Lina'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'Facing Marta - applied practice'},
                        {'kind': 'item_moment',
                         'npc': 'Marta die Heilerin',
                         'situation': 'Marta opens her hand. She is more tired than she wants the '
                                      'group to see.',
                         'npc_line': 'Hast du Medizin oder ein Kraut? Wenn nicht, rede ich '
                                     'trotzdem.',
                         'item_tag': 'remedio',
                         'on_use': {'narrative': 'You take a remedy from the backpack and place it '
                                                 "in Marta's hand. Her guarded expression softens "
                                                 'for one breath.',
                                    'npc_reaction': 'Gut. Dann erzaehle ich mehr, als ich geplant '
                                                    'hatte.',
                                    'bonus': 'extra_dialogue'},
                         'on_skip': {'npc_reaction': 'Es ist in Ordnung. Ich rede, aber nicht '
                                                     'alles.'}},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Marta die Heilerin asks '
                                 'for language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'wenn. Sag es klar.',
                         'translation': 'wenn. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "when/if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wenn',
                         'target': 'wenn',
                         'native': 'when/if',
                         'npc_reaction': 'wenn. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Kraut. Sag es klar.',
                         'translation': 'Kraut. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "herb".',
                         'options': [{'id': 'a', 'text': 'Kraut'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kraut',
                         'target': 'Kraut',
                         'native': 'herb',
                         'npc_reaction': 'Kraut. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Lina',
                         'line': 'helfen. Sag es klar.',
                         'translation': 'helfen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Applied answer: choose "help".',
                         'options': [{'id': 'a', 'text': 'helfen'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_helfen',
                         'target': 'helfen',
                         'native': 'help',
                         'npc_reaction': 'helfen. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Bruder. Sag es klar.',
                         'translation': 'Bruder. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "brother".',
                         'options': [{'id': 'a', 'text': 'Bruder'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bruder',
                         'target': 'Bruder',
                         'native': 'brother',
                         'npc_reaction': 'Bruder. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Hallo. Sag es klar.',
                         'translation': 'Hallo. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "hello".',
                         'options': [{'id': 'a', 'text': 'Hallo'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hallo',
                         'target': 'Hallo',
                         'native': 'hello',
                         'npc_reaction': 'Hallo. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'wenn clauses exposure',
                          'explanation': 'Use only what the scene requires: wenn clauses exposure.',
                          'examples': ['wenn',
                                       'Kraut',
                                       'helfen',
                                       'Ich kann helfen',
                                       'Ich erinnere mich nicht',
                                       'Gestern']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: wenn clauses exposure. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'wenn. Kraut. helfen.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for wenn clauses exposure: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Kraut'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_21_0',
                         'target': 'wenn',
                         'native': 'usable German phrase',
                         'npc_reaction': 'wenn. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for wenn clauses exposure: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Kraut'},
                                     {'id': 'b', 'text': 'helfen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_21_1',
                         'target': 'Kraut',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Kraut. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Grammar-in-scene check for wenn clauses exposure: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'helfen'},
                                     {'id': 'b', 'text': 'Ich kann helfen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_21_2',
                         'target': 'helfen',
                         'native': 'usable German phrase',
                         'npc_reaction': 'helfen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for wenn clauses exposure: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_21_3',
                         'target': 'Ich kann helfen',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich kann helfen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for wenn clauses exposure: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_21_4',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Ich erinnere mich nicht. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Otto', 'Lina'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'scene',
                         'text': 'Facing Marta - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: The '
                                 'group confronts Marta with questions. Her answers help, but '
                                 'never fully settle. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "when/if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wenn',
                         'target': 'wenn',
                         'native': 'when/if',
                         'npc_reaction': 'wenn. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "please".',
                         'options': [{'id': 'a', 'text': 'Bitte'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bitte',
                         'target': 'Bitte',
                         'native': 'please',
                         'npc_reaction': 'Bitte. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "my name '
                                     'is".',
                         'options': [{'id': 'a', 'text': 'Ich heisse'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_ich_heisse',
                         'target': 'Ich heisse',
                         'native': 'my name is',
                         'npc_reaction': 'Ich heisse. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "herb".',
                         'options': [{'id': 'a', 'text': 'Kraut'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_kraut',
                         'target': 'Kraut',
                         'native': 'herb',
                         'npc_reaction': 'Kraut. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"stranger".',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_fremder',
                         'target': 'Fremder',
                         'native': 'stranger',
                         'npc_reaction': 'Fremder. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Lina',
                         'question': 'Reinforcement with consequence: choose German for "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_brot',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'Brot. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "help".',
                         'options': [{'id': 'a', 'text': 'helfen'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_helfen',
                         'target': 'helfen',
                         'native': 'help',
                         'npc_reaction': 'helfen. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Marta die Heilerin', 'Otto', 'Lina'],
                        'story': 'The group confronts Marta with questions. Her answers help, but '
                                 'never fully settle.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'Facing Marta - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: The group '
                                 'confronts Marta with questions. Her answers help, but never '
                                 'fully settle.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 1: answer with "when/if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_21_0',
                         'target': 'wenn',
                         'native': 'when/if',
                         'npc_reaction': 'The gate accepts wenn.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 2: answer with "herb".',
                         'options': [{'id': 'a', 'text': 'Kraut'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_21_1',
                         'target': 'Kraut',
                         'native': 'herb',
                         'npc_reaction': 'The gate accepts Kraut.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 3: answer with "help".',
                         'options': [{'id': 'a', 'text': 'helfen'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_21_2',
                         'target': 'helfen',
                         'native': 'help',
                         'npc_reaction': 'The gate accepts helfen.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 4: answer with "I can help".',
                         'options': [{'id': 'a', 'text': 'Ich kann helfen'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_21_3',
                         'target': 'Ich kann helfen',
                         'native': 'I can help',
                         'npc_reaction': 'The gate accepts Ich kann helfen.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Gate 5: answer with "I do not remember".',
                         'options': [{'id': 'a', 'text': 'Ich erinnere mich nicht'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_21_4',
                         'target': 'Ich erinnere mich nicht',
                         'native': 'I do not remember',
                         'npc_reaction': 'The gate accepts Ich erinnere mich nicht.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves facing marta carrying the next '
                                 'problem toward phase 22.'}]}}]
