"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'Before the Vogt - escort - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'ueberzeugung',
                         'min_level': 3,
                         'uses_item_tag': 'moneda',
                         'success': 'Your timing and tone make the villager listen before suspicion hardens.',
                         'fallback': 'The villager does not trust you yet, but Otto keeps the exchange from closing.'},
                        {'kind': 'narrative',
                         'text': 'The Inspector escorts the group before the Vogt. A coin can '
                                 'soften a guard, not the system. This is the same ES canon beat, '
                                 'adapted for EN -> DE. English tells you what is happening; '
                                 'German is what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is terms of the coming trial. The language '
                                 'focus is conditional exposure with wenn. Nothing is presented as '
                                 'a lecture; every phrase is tied to a person, an object, or a '
                                 'risk in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Inspektor',
                         'line': 'zeigen. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'zeigen. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: zeigen.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Otto watches from the edge of the scene. The look is not random; '
                                 'it plants the next problem before you can name it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Inspektor',
                         'line': 'Respekt. Noch einmal.',
                         'translation': 'Respekt. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: zeigen, Respekt, wenn.'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'zeigen', 'native': 'show'},
                                       {'target': 'Respekt', 'native': 'respect'},
                                       {'target': 'wenn', 'native': 'if'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Inspektor',
                             'question': 'The scene needs German for "show".',
                             'options': [{'id': 'a', 'text': 'zeigen'},
                                         {'id': 'b', 'text': 'Heute'},
                                         {'id': 'c', 'text': 'Luege'},
                                         {'id': 'd', 'text': 'Guten Morgen'}],
                             'correct': 'a',
                             'word_id': 'de_zeigen',
                             'target': 'zeigen',
                             'native': 'show',
                             'npc_reaction': 'Der Inspektor accepts the word: zeigen.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Inspektor',
                             'question': 'The scene needs German for "respect".',
                             'options': [{'id': 'a', 'text': 'Respekt'},
                                         {'id': 'b', 'text': 'Heute'},
                                         {'id': 'c', 'text': 'Luege'},
                                         {'id': 'd', 'text': 'Guten Morgen'}],
                             'correct': 'a',
                             'word_id': 'de_respekt',
                             'target': 'Respekt',
                             'native': 'respect',
                             'npc_reaction': 'Der Inspektor accepts the word: Respekt.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Der Inspektor',
                             'question': 'The scene needs German for "if".',
                             'options': [{'id': 'a', 'text': 'wenn'},
                                         {'id': 'b', 'text': 'Heute'},
                                         {'id': 'c', 'text': 'Luege'},
                                         {'id': 'd', 'text': 'Guten Morgen'}],
                             'correct': 'a',
                             'word_id': 'de_wenn',
                             'target': 'wenn',
                             'native': 'if',
                             'npc_reaction': 'Der Inspektor accepts the word: wenn.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Der Inspektor', 'Der Vogt', 'Otto'],
                        'story': 'The Inspector escorts the group before the Vogt. A coin can '
                                 'soften a guard, not the system.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for Before the Vogt. Earlier vocabulary returns '
                                 'because the situation asks for it, not because the interface '
                                 'changed modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Hallo'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_gestern',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'Otto nods. Gestern still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Guten Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Otto nods. Heute still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Danke'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Otto nods. Morgen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Bitte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Otto nods. Wahrheit still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "lie".',
                         'options': [{'id': 'a', 'text': 'Luege'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Ich heisse'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_luege',
                         'target': 'Luege',
                         'native': 'lie',
                         'npc_reaction': 'Otto nods. Luege still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Wie heisst du?'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Otto nods. Siegel still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "brother".',
                         'options': [{'id': 'a', 'text': 'Bruder'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Fremder'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bruder',
                         'target': 'Bruder',
                         'native': 'brother',
                         'npc_reaction': 'Otto nods. Bruder still belongs to you.'}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Der Inspektor', 'Der Vogt', 'Otto'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'Before the Vogt - applied practice'},
                        {'kind': 'item_moment',
                         'npc': 'Elias der Bauer',
                         'situation': 'A young guard waits near the town hall door. Elias lowers '
                                      'his voice.',
                         'npc_line': 'Wenn du eine Muenze hast, gib sie mir. Eine einzige kann '
                                     'Zeit kaufen.',
                         'item_tag': 'moneda',
                         'on_use': {'narrative': 'You pass a coin to Elias. He gives it to the '
                                                 'nervous guard, who looks away at exactly the '
                                                 'useful moment.',
                                    'npc_reaction': 'Gut. Wenn sie uns trennen wollen, sieht er '
                                                    'vielleicht nichts.',
                                    'bonus': 'reduce_gated'},
                         'on_skip': {'npc_reaction': 'Dann nehmen wir den langen Weg. Marta kennt '
                                                     'andere Wege.'}},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Der Inspektor asks for '
                                 'language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Inspektor',
                         'line': 'zeigen. Sag es klar.',
                         'translation': 'zeigen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Applied answer: choose "show".',
                         'options': [{'id': 'a', 'text': 'zeigen'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_zeigen',
                         'target': 'zeigen',
                         'native': 'show',
                         'npc_reaction': 'zeigen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Vogt',
                         'line': 'Respekt. Sag es klar.',
                         'translation': 'Respekt. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Applied answer: choose "respect".',
                         'options': [{'id': 'a', 'text': 'Respekt'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_respekt',
                         'target': 'Respekt',
                         'native': 'respect',
                         'npc_reaction': 'Respekt. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'wenn. Sag es klar.',
                         'translation': 'wenn. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wenn',
                         'target': 'wenn',
                         'native': 'if',
                         'npc_reaction': 'wenn. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Der Inspektor',
                         'line': 'Guten Morgen. Sag es klar.',
                         'translation': 'Guten Morgen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Applied answer: choose "good morning".',
                         'options': [{'id': 'a', 'text': 'Guten Morgen'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_guten_morgen',
                         'target': 'Guten Morgen',
                         'native': 'good morning',
                         'npc_reaction': 'Guten Morgen. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Vogt',
                         'line': 'Danke. Sag es klar.',
                         'translation': 'Danke. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Applied answer: choose "thank you".',
                         'options': [{'id': 'a', 'text': 'Danke'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_danke',
                         'target': 'Danke',
                         'native': 'thank you',
                         'npc_reaction': 'Danke. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'conditional exposure with wenn',
                          'explanation': 'Use only what the scene requires: conditional exposure '
                                         'with wenn.',
                          'examples': ['zeigen', 'Respekt', 'wenn', 'Gestern', 'Heute', 'Morgen']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: conditional exposure with wenn. This is the '
                                 'German-specific path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Der Inspektor',
                         'line': 'zeigen. Respekt. wenn.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Grammar-in-scene check for conditional exposure with wenn: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'zeigen'},
                                     {'id': 'b', 'text': 'Respekt'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_23_0',
                         'target': 'zeigen',
                         'native': 'usable German phrase',
                         'npc_reaction': 'zeigen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Grammar-in-scene check for conditional exposure with wenn: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Respekt'},
                                     {'id': 'b', 'text': 'wenn'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_23_1',
                         'target': 'Respekt',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Respekt. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for conditional exposure with wenn: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Gestern'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_23_2',
                         'target': 'wenn',
                         'native': 'usable German phrase',
                         'npc_reaction': 'wenn. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Grammar-in-scene check for conditional exposure with wenn: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_23_3',
                         'target': 'Gestern',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Gestern. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Grammar-in-scene check for conditional exposure with wenn: '
                                     'choose the phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_23_4',
                         'target': 'Heute',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Der Inspektor', 'Der Vogt', 'Otto'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'scene',
                         'text': 'Before the Vogt - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: The '
                                 'Inspector escorts the group before the Vogt. A coin can soften a '
                                 'guard, not the system. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Reinforcement with consequence: choose German for "show".',
                         'options': [{'id': 'a', 'text': 'zeigen'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_zeigen',
                         'target': 'zeigen',
                         'native': 'show',
                         'npc_reaction': 'zeigen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Reinforcement with consequence: choose German for "what is '
                                     'your name?".',
                         'options': [{'id': 'a', 'text': 'Wie heisst du?'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wie_heisst_du',
                         'target': 'Wie heisst du?',
                         'native': 'what is your name?',
                         'npc_reaction': 'Wie heisst du?. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"stranger".',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_fremder',
                         'target': 'Fremder',
                         'native': 'stranger',
                         'npc_reaction': 'Fremder. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Reinforcement with consequence: choose German for "respect".',
                         'options': [{'id': 'a', 'text': 'Respekt'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_respekt',
                         'target': 'Respekt',
                         'native': 'respect',
                         'npc_reaction': 'Respekt. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Vogt',
                         'question': 'Reinforcement with consequence: choose German for "water".',
                         'options': [{'id': 'a', 'text': 'Wasser'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wasser',
                         'target': 'Wasser',
                         'native': 'water',
                         'npc_reaction': 'Wasser. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I am '
                                     'hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hunger',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Reinforcement with consequence: choose German for "if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wenn',
                         'target': 'wenn',
                         'native': 'if',
                         'npc_reaction': 'wenn. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Der Inspektor', 'Der Vogt', 'Otto'],
                        'story': 'The Inspector escorts the group before the Vogt. A coin can '
                                 'soften a guard, not the system.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'Before the Vogt - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: The Inspector '
                                 'escorts the group before the Vogt. A coin can soften a guard, '
                                 'not the system.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Gate 1: answer with "show".',
                         'options': [{'id': 'a', 'text': 'zeigen'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_23_0',
                         'target': 'zeigen',
                         'native': 'show',
                         'npc_reaction': 'The gate accepts zeigen.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Gate 2: answer with "respect".',
                         'options': [{'id': 'a', 'text': 'Respekt'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_23_1',
                         'target': 'Respekt',
                         'native': 'respect',
                         'npc_reaction': 'The gate accepts Respekt.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Gate 3: answer with "if".',
                         'options': [{'id': 'a', 'text': 'wenn'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_23_2',
                         'target': 'wenn',
                         'native': 'if',
                         'npc_reaction': 'The gate accepts wenn.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Gate 4: answer with "yesterday".',
                         'options': [{'id': 'a', 'text': 'Gestern'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_23_3',
                         'target': 'Gestern',
                         'native': 'yesterday',
                         'npc_reaction': 'The gate accepts Gestern.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Der Inspektor',
                         'question': 'Gate 5: answer with "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_23_4',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'The gate accepts Heute.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves before the vogt carrying the next '
                                 'problem toward phase 24.'}]}}]
