"""
Materialized EN -> DE A1 T1 phase.
Expanded from the ES canon matrix with English support text and German target speech.
"""

SECTIONS = [{'section_number': 1,
  'section_type': 'narrativa',
  'content': {'beats': [{'kind': 'scene', 'text': 'The Eve - eve - first tableau'},
                        {'kind': 'skill_check',
                         'skill': 'waffen',
                         'min_level': 3,
                         'uses_item_tag': 'arma',
                         'success': 'You keep the tool low and steady, making the path safer without turning the scene into a fight.',
                         'fallback': 'The tool does not help much yet, but Otto finds another way forward.'},
                        {'kind': 'narrative',
                         'text': 'The eve of judgment prepares the final answers and makes sleep '
                                 'itself a tactical choice. This is the same ES canon beat, '
                                 'adapted for EN -> DE. English tells you what is happening; '
                                 'German is what the world answers to.'},
                        {'kind': 'narrative',
                         'text': 'The practical focus is last preparation before judgment. The '
                                 'language focus is sollen / should. Nothing is presented as a '
                                 'lecture; every phrase is tied to a person, an object, or a risk '
                                 'in the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Elias der Bauer',
                         'line': 'soll. Hoer zu, Fremder. Dieses Wort ist wichtig.',
                         'translation': 'soll. Listen, stranger. This word matters.',
                         'pace': 'slow'},
                        {'kind': 'player',
                         'text': 'You repeat it quietly. The village does not become friendly, but '
                                 'it becomes slightly less impossible.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'You say German, door opens little. Wrong word, people stare. '
                                 'First: soll.',
                         'translation': 'Otto bridges in imperfect English without removing the '
                                        'German pressure.',
                         'pace': 'slow'},
                        {'kind': 'narrative',
                         'text': 'Otto watches from the edge of the scene. The look is not random; '
                                 'it plants the next problem before you can name it.'},
                        {'kind': 'npc_speak',
                         'npc': 'Elias der Bauer',
                         'line': 'bereit. Noch einmal.',
                         'translation': 'bereit. Again.',
                         'pace': 'normal'},
                        {'kind': 'narrative',
                         'text': 'The old letter remains sealed. For now, the only way forward is '
                                 'through small words: soll, bereit, morgen.'}],
              'exercises': [{'kind': 'vocab_list',
                             'items': [{'target': 'soll', 'native': 'should'},
                                       {'target': 'bereit', 'native': 'ready'},
                                       {'target': 'morgen', 'native': 'tomorrow'}]},
                            {'kind': 'multiple_choice',
                             'npc': 'Elias der Bauer',
                             'question': 'The scene needs German for "should".',
                             'options': [{'id': 'a', 'text': 'soll'},
                                         {'id': 'b', 'text': 'Morgen'},
                                         {'id': 'c', 'text': 'Siegel'},
                                         {'id': 'd', 'text': 'Danke'}],
                             'correct': 'a',
                             'word_id': 'de_soll',
                             'target': 'soll',
                             'native': 'should',
                             'npc_reaction': 'Elias der Bauer accepts the word: soll.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Elias der Bauer',
                             'question': 'The scene needs German for "ready".',
                             'options': [{'id': 'a', 'text': 'bereit'},
                                         {'id': 'b', 'text': 'Morgen'},
                                         {'id': 'c', 'text': 'Siegel'},
                                         {'id': 'd', 'text': 'Danke'}],
                             'correct': 'a',
                             'word_id': 'de_bereit',
                             'target': 'bereit',
                             'native': 'ready',
                             'npc_reaction': 'Elias der Bauer accepts the word: bereit.'},
                            {'kind': 'multiple_choice',
                             'npc': 'Elias der Bauer',
                             'question': 'The scene needs German for "tomorrow".',
                             'options': [{'id': 'a', 'text': 'morgen'},
                                         {'id': 'b', 'text': 'Morgen'},
                                         {'id': 'c', 'text': 'Siegel'},
                                         {'id': 'd', 'text': 'Danke'}],
                             'correct': 'a',
                             'word_id': 'de_morgen',
                             'target': 'morgen',
                             'native': 'tomorrow',
                             'npc_reaction': 'Elias der Bauer accepts the word: morgen.'}]}},
 {'section_number': 2,  'section_type': 'revisao_srs',
  'content': {'recap': {'characters': ['Elias der Bauer', 'Marta die Heilerin', 'Otto'],
                        'story': 'The eve of judgment prepares the final answers and makes sleep '
                                 'itself a tactical choice.',
                        'now': 'Earlier vocabulary returns under pressure.'},
              'steps': [{'kind': 'narrative',
                         'text': 'Review loop for The Eve. Earlier vocabulary returns because the '
                                 'situation asks for it, not because the interface changed modes.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'Old words now. Fast, but not panic. I help little.',
                         'translation': 'Otto warns you that review is part of the story.',
                         'pace': 'normal'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Luege'},
                                     {'id': 'c', 'text': 'Guten Morgen'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_heute',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'Otto nods. Heute still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Siegel'},
                                     {'id': 'c', 'text': 'Danke'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'Otto nods. Morgen still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "truth".',
                         'options': [{'id': 'a', 'text': 'Wahrheit'},
                                     {'id': 'b', 'text': 'Bruder'},
                                     {'id': 'c', 'text': 'Bitte'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_wahrheit',
                         'target': 'Wahrheit',
                         'native': 'truth',
                         'npc_reaction': 'Otto nods. Wahrheit still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "lie".',
                         'options': [{'id': 'a', 'text': 'Luege'},
                                     {'id': 'b', 'text': 'Hallo'},
                                     {'id': 'c', 'text': 'Ich heisse'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_luege',
                         'target': 'Luege',
                         'native': 'lie',
                         'npc_reaction': 'Otto nods. Luege still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "seal".',
                         'options': [{'id': 'a', 'text': 'Siegel'},
                                     {'id': 'b', 'text': 'Guten Morgen'},
                                     {'id': 'c', 'text': 'Wie heisst du?'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_siegel',
                         'target': 'Siegel',
                         'native': 'seal',
                         'npc_reaction': 'Otto nods. Siegel still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "brother".',
                         'options': [{'id': 'a', 'text': 'Bruder'},
                                     {'id': 'b', 'text': 'Danke'},
                                     {'id': 'c', 'text': 'Fremder'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bruder',
                         'target': 'Bruder',
                         'native': 'brother',
                         'npc_reaction': 'Otto nods. Bruder still belongs to you.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Review under pressure: choose German for "hello".',
                         'options': [{'id': 'a', 'text': 'Hallo'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Brot'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hallo',
                         'target': 'Hallo',
                         'native': 'hello',
                         'npc_reaction': 'Otto nods. Hallo still belongs to you.'}]}},
 {'section_number': 3,
  'section_type': 'pratica_aplicada',
  'content': {'recap': {'characters': ['Elias der Bauer', 'Marta die Heilerin', 'Otto'],
                        'story': 'The scene narrows. Guessing is no longer enough.',
                        'now': 'Apply the phrase in context.'},
              'steps': [{'kind': 'scene', 'text': 'The Eve - applied practice'},
                        {'kind': 'item_moment',
                         'npc': 'Marta die Heilerin',
                         'situation': 'You need sleep. Tomorrow cannot be survived on fear alone.',
                         'npc_line': 'Nimm Medizin, wenn du sie hast. Oder Wasser. Aber schlaf.',
                         'item_tag': 'remedio',
                         'on_use': {'narrative': 'You use the remedy. Bitter herb, clean water, '
                                                 'one deep breath. The room finally becomes quiet.',
                                    'npc_reaction': 'Gut. Morgen gehorcht dein Kopf besser.',
                                    'bonus': 'reduce_gated'},
                         'on_skip': {'npc_reaction': 'Dann atme langsam. Es hilft auch, nur '
                                                     'weniger.'}},
                        {'kind': 'narrative',
                         'text': 'Now the phase stops being observation. Elias der Bauer asks for '
                                 'language that changes what the group can do next.'},
                        {'kind': 'npc_speak',
                         'npc': 'Elias der Bauer',
                         'line': 'soll. Sag es klar.',
                         'translation': 'soll. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Applied answer: choose "should".',
                         'options': [{'id': 'a', 'text': 'soll'},
                                     {'id': 'b', 'text': 'Bitte'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_soll',
                         'target': 'soll',
                         'native': 'should',
                         'npc_reaction': 'soll. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'bereit. Sag es klar.',
                         'translation': 'bereit. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "ready".',
                         'options': [{'id': 'a', 'text': 'bereit'},
                                     {'id': 'b', 'text': 'Ich heisse'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bereit',
                         'target': 'bereit',
                         'native': 'ready',
                         'npc_reaction': 'bereit. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Otto',
                         'line': 'morgen. Sag es klar.',
                         'translation': 'morgen. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Applied answer: choose "tomorrow".',
                         'options': [{'id': 'a', 'text': 'morgen'},
                                     {'id': 'b', 'text': 'Wie heisst du?'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'morgen. The answer fits the scene.',
                         'gated': True},
                        {'kind': 'npc_speak',
                         'npc': 'Elias der Bauer',
                         'line': 'Danke. Sag es klar.',
                         'translation': 'Danke. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Applied answer: choose "thank you".',
                         'options': [{'id': 'a', 'text': 'Danke'},
                                     {'id': 'b', 'text': 'Fremder'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_danke',
                         'target': 'Danke',
                         'native': 'thank you',
                         'npc_reaction': 'Danke. The answer fits the scene.'},
                        {'kind': 'npc_speak',
                         'npc': 'Marta die Heilerin',
                         'line': 'Bitte. Sag es klar.',
                         'translation': 'Bitte. Say it clearly.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Applied answer: choose "please".',
                         'options': [{'id': 'a', 'text': 'Bitte'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Falsch'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bitte',
                         'target': 'Bitte',
                         'native': 'please',
                         'npc_reaction': 'Bitte. The answer fits the scene.',
                         'gated': True}]}},
 {'section_number': 4,
  'section_type': 'gramatica_narrativa',
  'content': {'grammar': {'title': 'sollen / should',
                          'explanation': 'Use only what the scene requires: sollen / should.',
                          'examples': ['soll', 'bereit', 'morgen', 'Heute', 'Morgen', 'Wahrheit']},
              'steps': [{'kind': 'narrative',
                         'text': 'Pattern in use: sollen / should. This is the German-specific '
                                 'path, not a direct copy of Spanish grammar.'},
                        {'kind': 'npc_speak',
                         'npc': 'Elias der Bauer',
                         'line': 'soll. bereit. morgen.',
                         'translation': 'The pattern appears as usable speech.',
                         'pace': 'slow'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Grammar-in-scene check for sollen / should: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'soll'},
                                     {'id': 'b', 'text': 'bereit'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_24_0',
                         'target': 'soll',
                         'native': 'usable German phrase',
                         'npc_reaction': 'soll. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for sollen / should: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'bereit'},
                                     {'id': 'b', 'text': 'morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_24_1',
                         'target': 'bereit',
                         'native': 'usable German phrase',
                         'npc_reaction': 'bereit. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Grammar-in-scene check for sollen / should: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'morgen'},
                                     {'id': 'b', 'text': 'Heute'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_24_2',
                         'target': 'morgen',
                         'native': 'usable German phrase',
                         'npc_reaction': 'morgen. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Grammar-in-scene check for sollen / should: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Morgen'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_24_3',
                         'target': 'Heute',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Heute. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Grammar-in-scene check for sollen / should: choose the '
                                     'phrase that fits.',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Wahrheit'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_grammar_24_4',
                         'target': 'Morgen',
                         'native': 'usable German phrase',
                         'npc_reaction': 'Morgen. The answer fits the scene.'},
                        {'kind': 'narrative',
                         'text': 'The rule stays light. The phase wants recognition, not '
                                 'terminology.'}]}},
 {'section_number': 5,
  'section_type': 'reforco',
  'content': {'recap': {'characters': ['Elias der Bauer', 'Marta die Heilerin', 'Otto'],
                        'story': 'The group repeats the language in a quieter beat.',
                        'now': 'Reinforce before the obstacle.'},
              'steps': [{'kind': 'scene', 'text': 'The Eve - reinforcement and emotional echo'},
                        {'kind': 'narrative',
                         'text': 'The emotional purpose of this phase is still the ES one: The eve '
                                 'of judgment prepares the final answers and makes sleep itself a '
                                 'tactical choice. The repeated words now carry relationship '
                                 'weight.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Reinforcement with consequence: choose German for "should".',
                         'options': [{'id': 'a', 'text': 'soll'},
                                     {'id': 'b', 'text': 'Brot'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_soll',
                         'target': 'soll',
                         'native': 'should',
                         'npc_reaction': 'soll. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"stranger".',
                         'options': [{'id': 'a', 'text': 'Fremder'},
                                     {'id': 'b', 'text': 'Wasser'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_fremder',
                         'target': 'Fremder',
                         'native': 'stranger',
                         'npc_reaction': 'Fremder. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "bread".',
                         'options': [{'id': 'a', 'text': 'Brot'},
                                     {'id': 'b', 'text': 'Ich habe Hunger'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_brot',
                         'target': 'Brot',
                         'native': 'bread',
                         'npc_reaction': 'Brot. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Reinforcement with consequence: choose German for "ready".',
                         'options': [{'id': 'a', 'text': 'bereit'},
                                     {'id': 'b', 'text': 'Ich habe Durst'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_bereit',
                         'target': 'bereit',
                         'native': 'ready',
                         'npc_reaction': 'bereit. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Marta die Heilerin',
                         'question': 'Reinforcement with consequence: choose German for "I am '
                                     'hungry".',
                         'options': [{'id': 'a', 'text': 'Ich habe Hunger'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_hunger',
                         'target': 'Ich habe Hunger',
                         'native': 'I am hungry',
                         'npc_reaction': 'Ich habe Hunger. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Otto',
                         'question': 'Reinforcement with consequence: choose German for "I am '
                                     'thirsty".',
                         'options': [{'id': 'a', 'text': 'Ich habe Durst'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_durst',
                         'target': 'Ich habe Durst',
                         'native': 'I am thirsty',
                         'npc_reaction': 'Ich habe Durst. The answer fits the scene.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Reinforcement with consequence: choose German for '
                                     '"tomorrow".',
                         'options': [{'id': 'a', 'text': 'morgen'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Vielleicht'},
                                     {'id': 'd', 'text': 'Nicht jetzt'}],
                         'correct': 'a',
                         'word_id': 'de_morgen',
                         'target': 'morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'morgen. The answer fits the scene.'}]}},
 {'section_number': 6,
  'section_type': 'obstaculo',
  'content': {'recap': {'characters': ['Elias der Bauer', 'Marta die Heilerin', 'Otto'],
                        'story': 'The eve of judgment prepares the final answers and makes sleep '
                                 'itself a tactical choice.',
                        'now': 'Pass the gate to close the phase.'},
              'steps': [{'kind': 'scene', 'text': 'The Eve - gated close'},
                        {'kind': 'narrative',
                         'text': 'The closing gate preserves the canon transition: The eve of '
                                 'judgment prepares the final answers and makes sleep itself a '
                                 'tactical choice.'},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Gate 1: answer with "should".',
                         'options': [{'id': 'a', 'text': 'soll'},
                                     {'id': 'b', 'text': 'Der Weg'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_24_0',
                         'target': 'soll',
                         'native': 'should',
                         'npc_reaction': 'The gate accepts soll.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Gate 2: answer with "ready".',
                         'options': [{'id': 'a', 'text': 'bereit'},
                                     {'id': 'b', 'text': 'Der Wald'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_24_1',
                         'target': 'bereit',
                         'native': 'ready',
                         'npc_reaction': 'The gate accepts bereit.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Gate 3: answer with "tomorrow".',
                         'options': [{'id': 'a', 'text': 'morgen'},
                                     {'id': 'b', 'text': 'Hier'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_24_2',
                         'target': 'morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'The gate accepts morgen.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Gate 4: answer with "today".',
                         'options': [{'id': 'a', 'text': 'Heute'},
                                     {'id': 'b', 'text': 'Dort'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_24_3',
                         'target': 'Heute',
                         'native': 'today',
                         'npc_reaction': 'The gate accepts Heute.',
                         'gated': True},
                        {'kind': 'multiple_choice',
                         'npc': 'Elias der Bauer',
                         'question': 'Gate 5: answer with "tomorrow".',
                         'options': [{'id': 'a', 'text': 'Morgen'},
                                     {'id': 'b', 'text': 'Links'},
                                     {'id': 'c', 'text': 'Nein'},
                                     {'id': 'd', 'text': 'Ich weiss nicht'}],
                         'correct': 'a',
                         'word_id': 'de_gate_24_4',
                         'target': 'Morgen',
                         'native': 'tomorrow',
                         'npc_reaction': 'The gate accepts Morgen.',
                         'gated': True},
                        {'kind': 'narrative',
                         'text': 'Transition: the group leaves the eve carrying the next problem '
                                 'toward phase 25.'}]}}]
