import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingTop: SPACING["3xl"],
  },
  header: {
    gap: 4,
  },
  eyebrow: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  title: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "800",
    lineHeight: 36,
  },
  subtitle: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    lineHeight: 20,
  },
  summaryRow: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  summaryCard: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flex: 1,
    padding: SPACING.sm,
  },
  summaryValue: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.xl,
    fontWeight: "800",
  },
  summaryLabel: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    marginTop: 2,
  },
  filters: {
    gap: SPACING.sm,
    paddingRight: SPACING.lg,
  },
  filter: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.full,
    borderWidth: 2,
    flexDirection: "row",
    gap: 7,
    minHeight: 38,
    paddingHorizontal: SPACING.md,
  },
  selected: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primary,
  },
  filterText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
  },
  selectedText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
  },
  filterCount: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.full,
    color: COLORS.gray600,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  selectedCount: {
    backgroundColor: "rgba(20, 184, 166, 0.14)",
    borderRadius: RADIUS.full,
    color: COLORS.primary,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  card: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.sm,
    padding: SPACING.md,
  },
  cardTop: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  cardIcon: {
    alignItems: "center",
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.full,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  cardCopy: {
    flex: 1,
    gap: 4,
  },
  cardTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    lineHeight: 24,
  },
  cardDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    lineHeight: 20,
  },
  meta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  badge: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.full,
    color: COLORS.gray600,
    fontSize: FONT_SIZE.xs,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
  },
  remove: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: "#fecaca",
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    minHeight: 36,
    paddingHorizontal: SPACING.md,
  },
  removeText: {
    color: "#dc2626",
    fontSize: FONT_SIZE.sm,
    fontWeight: "800",
  },
  emptyCard: {
    alignItems: "center",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderStyle: "dashed",
    borderWidth: 1,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING["3xl"],
  },
  emptyIcon: {
    alignItems: "center",
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.full,
    height: 54,
    justifyContent: "center",
    marginBottom: SPACING.sm,
    width: 54,
  },
  emptyTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.lg,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    lineHeight: 20,
    marginTop: 4,
    textAlign: "center",
  },
  empty: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    paddingVertical: SPACING["3xl"],
    textAlign: "center",
  },
  state: {
    alignItems: "center",
    backgroundColor: COLORS.white,
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  stateText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
    textAlign: "center",
  },
});
