import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING } from "@linguaflow/shared-core";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingTop: SPACING["3xl"],
  },
  tabs: {
    gap: SPACING.sm,
    paddingBottom: SPACING.xs,
  },
  tab: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    color: COLORS.gray600,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    minHeight: 38,
    overflow: "hidden",
    paddingHorizontal: SPACING.md,
    paddingVertical: 9,
  },
  activeTab: {
    backgroundColor: COLORS.primaryLight,
    color: COLORS.primary,
  },
  header: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: SPACING.md,
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  headerText: {
    flex: 1,
  },
  eyebrow: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  title: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "700",
  },
  subtitle: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    marginTop: SPACING.xs,
  },
  count: {
    color: COLORS.primary,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  card: {
    alignItems: "flex-start",
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACING.md,
    padding: SPACING.md,
  },
  pressableCard: {
    backgroundColor: COLORS.white,
  },
  pressedCard: {
    borderColor: COLORS.primary,
    transform: [{ translateY: 1 }],
  },
  emoji: {
    backgroundColor: COLORS.gray100,
    borderRadius: RADIUS.sm,
    fontSize: 24,
    height: 42,
    overflow: "hidden",
    paddingTop: 7,
    textAlign: "center",
    width: 42,
  },
  cardText: {
    flex: 1,
    gap: SPACING.xs,
  },
  cardTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  cardDetail: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
  },
  meta: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  wordRow: {
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  wordTarget: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  wordNative: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
  },
  metric: {
    backgroundColor: COLORS.gray50,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexBasis: "47%",
    flexGrow: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  metricLabel: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.sm,
    fontWeight: "600",
  },
  metricValue: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  state: {
    color: COLORS.gray500,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
    paddingVertical: SPACING["3xl"],
    textAlign: "center",
  },
  modalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(18, 24, 40, 0.48)",
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  modalPanel: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.md,
    padding: SPACING.lg,
    width: "100%",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: COLORS.gray100,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    position: "absolute",
    right: SPACING.md,
    top: SPACING.md,
    width: 34,
    zIndex: 2,
  },
  closeButtonText: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    lineHeight: 24,
  },
  modalHero: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACING.md,
    paddingRight: 48,
  },
  modalHeroText: {
    flex: 1,
    gap: SPACING.xs,
  },
  modalEmoji: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: RADIUS.sm,
    fontSize: 34,
    height: 64,
    overflow: "hidden",
    paddingTop: 11,
    textAlign: "center",
    width: 64,
  },
  modalRole: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  modalTitle: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  quote: {
    borderLeftColor: COLORS.primary,
    borderLeftWidth: 3,
    color: COLORS.gray700,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
    lineHeight: 24,
    paddingLeft: SPACING.md,
  },
  modalDescription: {
    color: COLORS.gray600,
    fontSize: FONT_SIZE.base,
    lineHeight: 24,
  },
  factGrid: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  fact: {
    backgroundColor: COLORS.gray50,
    borderColor: COLORS.gray200,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flex: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  factLabel: {
    color: COLORS.gray400,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  factValue: {
    color: COLORS.gray900,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
});
