import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, RADIUS, SPACING, getAdventureColors } from "@linguaflow/shared-core";

const adventureTheme = getAdventureColors("ES", "dark");

export const styles = StyleSheet.create({
  container: {
    backgroundColor: adventureTheme.bgFrom,
    flex: 1,
  },
  content: {
    gap: SPACING.md,
    padding: SPACING.lg,
    paddingTop: SPACING["3xl"],
  },
  tabs: {
    gap: SPACING.sm,
    paddingBottom: SPACING.xs,
  },
  tab: {
    backgroundColor: adventureTheme.surface,
    borderRadius: RADIUS.sm,
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    minHeight: 38,
    overflow: "hidden",
    paddingHorizontal: SPACING.md,
    paddingVertical: 9,
  },
  activeTab: {
    backgroundColor: adventureTheme.goldAccentSoft,
    color: adventureTheme.parchment,
  },
  header: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: SPACING.md,
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  headerText: {
    flex: 1,
  },
  eyebrow: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  title: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE["3xl"],
    fontWeight: "700",
  },
  subtitle: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    fontWeight: "500",
    marginTop: SPACING.xs,
  },
  count: {
    color: adventureTheme.goldAccent,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  card: {
    alignItems: "flex-start",
    backgroundColor: adventureTheme.surface,
    borderColor: adventureTheme.borderFaint,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexDirection: "row",
    gap: SPACING.md,
    padding: SPACING.md,
  },
  pressableCard: {
    backgroundColor: adventureTheme.surface,
  },
  pressedCard: {
    borderColor: adventureTheme.goldAccent,
    transform: [{ translateY: 1 }],
  },
  emoji: {
    backgroundColor: adventureTheme.goldAccentSoft,
    borderRadius: RADIUS.sm,
    fontSize: 24,
    height: 42,
    overflow: "hidden",
    paddingTop: 7,
    textAlign: "center",
    width: 42,
  },
  cardText: {
    flex: 1,
    gap: SPACING.xs,
  },
  cardTitle: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  cardDetail: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
  },
  meta: {
    color: adventureTheme.textFaint,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  wordRow: {
    backgroundColor: adventureTheme.surface,
    borderColor: adventureTheme.borderFaint,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  wordTarget: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
  },
  wordNative: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.md,
  },
  metric: {
    backgroundColor: adventureTheme.surface,
    borderColor: adventureTheme.borderFaint,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flexBasis: "47%",
    flexGrow: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  metricLabel: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.sm,
    fontWeight: "600",
  },
  metricValue: {
    color: adventureTheme.parchment,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  state: {
    color: adventureTheme.textOnBg,
    fontSize: FONT_SIZE.base,
    fontWeight: "600",
    paddingVertical: SPACING["3xl"],
    textAlign: "center",
  },
  modalBackdrop: {
    alignItems: "center",
    backgroundColor: adventureTheme.surfaceMid,
    flex: 1,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  modalPanel: {
    backgroundColor: adventureTheme.parchment,
    borderColor: adventureTheme.parchmentBorder,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    gap: SPACING.md,
    padding: SPACING.lg,
    width: "100%",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: adventureTheme.goldAccentSoft,
    borderColor: adventureTheme.parchmentBorder,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    position: "absolute",
    right: SPACING.md,
    top: SPACING.md,
    width: 34,
    zIndex: 2,
  },
  closeButtonText: {
    color: adventureTheme.parchmentText,
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    lineHeight: 24,
  },
  modalHero: {
    alignItems: "center",
    flexDirection: "row",
    gap: SPACING.md,
    paddingRight: 48,
  },
  modalHeroText: {
    flex: 1,
    gap: SPACING.xs,
  },
  modalEmoji: {
    backgroundColor: adventureTheme.goldAccentSoft,
    borderRadius: RADIUS.sm,
    fontSize: 34,
    height: 64,
    overflow: "hidden",
    paddingTop: 11,
    textAlign: "center",
    width: 64,
  },
  modalRole: {
    color: adventureTheme.parchmentSubtext,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
  modalTitle: {
    color: adventureTheme.parchmentText,
    fontSize: FONT_SIZE["2xl"],
    fontWeight: "700",
  },
  quote: {
    borderLeftColor: adventureTheme.goldAccent,
    borderLeftWidth: 3,
    color: adventureTheme.parchmentText,
    fontSize: FONT_SIZE.base,
    fontWeight: "700",
    lineHeight: 24,
    paddingLeft: SPACING.md,
  },
  modalDescription: {
    color: adventureTheme.parchmentText,
    fontSize: FONT_SIZE.base,
    lineHeight: 24,
  },
  factGrid: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  fact: {
    backgroundColor: adventureTheme.goldAccentSoft,
    borderColor: adventureTheme.parchmentBorder,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    flex: 1,
    gap: SPACING.xs,
    padding: SPACING.md,
  },
  factLabel: {
    color: adventureTheme.parchmentSubtext,
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  factValue: {
    color: adventureTheme.parchmentText,
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
  },
});
